### ISSUE TITLE
No authentication handler is configured to handle the scheme: idsrv.external

### ISSUE THREAD

**Issue by tweek82** [IdentityServer/IdentityServer4#1058]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I'm following the documentation (identityserver4.readthedocs.io) to step-by-step setup an IdentityServer. The one thing I've changed is the name of the cookies. As soon as I added the Google-middleware this exception is shown. 

If I don't change the AuthenticationScheme, it works.

How can I change the default cookie name from 'Idsrv' to something else and still be able to use Google authentication middleware?

I have added the following code to override the default cookiename:
```
public void ConfigureServices(IServiceCollection services)
{
            var idsrv = services.AddIdentityServer(SetIdentityServerOptions)
                .AddTemporarySigningCredential()
                .AddInMemoryApiResources(ApiResourcesConfiguration.GetApiResources())
                .AddInMemoryClients(ClientsConfiguration.GetClients())
                .AddInMemoryIdentityResources(IdentityResourcesConfiguration.GetIdentityResources())
                .AddTestUsers(UsersConfiguration.GetUsers());

            services.AddAntiforgery(opts => opts.CookieName = $"{CookiePrefixName}.antiforgery");
            services.AddMvc();
}

private void SetIdentityServerOptions(IdentityServerOptions identityServerOptions)
{
        identityServerOptions.Authentication.AuthenticationScheme = CookiePrefixName;
}
```

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(LogLevel.Debug);
    app.UseDeveloperExceptionPage();

    app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationScheme = CookiePrefixName,
        CookieName = $"{CookiePrefixName}.auth",
        ExpireTimeSpan = TimeSpan.FromMinutes(20),
        SlidingExpiration = true
    });
    app.UseIdentityServer();

    app.UseGoogleAuthentication(new GoogleOptions
    {
        AccessType = "offline",
        AuthenticationScheme = "Google",
        SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
        ClientId = "7<...>-<...>r.apps.googleusercontent.com",
        ClientSecret = "Y<...>V",
        Scope = {
            "https://www.googleapis.com/auth/plus.me",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
        }
    });
    app.UseStaticFiles();
    app.UseMvcWithDefaultRoute();
}
```

### Relevant parts of the log file

```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method SocsAuth.Idsrv.Controllers.AccountController.ExternalLogin (SocsAuth.Idsrv) with arguments (Google, /connect/authorize/login?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636276691974986322.MDIxNTFjYWMtYmIzMi00Mzg3LWExN2QtMmQ2MjA5OWEzMTg0ZmUzMGQ3YmItNTdjZi00N2U4LWEzN2ItOGUyZjc1YzY5MGMz&state=CfDJ8O86qU2K7_dMs-x49MyCm-uyJ1u7aiktdiFkARSQUiUyr8ty7NZfv6clSFoe2XxOO3aTZ5cWSZC113QLAA47hSaWE3QDIAtlASHNWwLSC96NtZpeGm6oebK6smV3menQpsLtr4ZP7v-lPTw1th0C37SzoGvLOo6E_ntE_yN4EoU3fSEqm6imrTQsdh5O4Pkajzeknva0WGh5Hntq6dIcBEaE-1aqP2JaUx3znupn-U7BAg9sV4MdT29OU5LxRDFl0nUSBdqTygtjdH8zhsgofE5pdflYRdYWqTWFXW4bxambjeVKeFqROEcLklD1ydDbxA) - ModelState is Valid
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL428UTPCM7C" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL428UTPCM7B" stopped.
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method SocsAuth.Idsrv.Controllers.AccountController.ExternalLogin (SocsAuth.Idsrv), returned result Microsoft.AspNetCore.Mvc.ChallengeResult.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes (Google).
info: Microsoft.AspNetCore.Authentication.Google.GoogleMiddleware[12]
      AuthenticationScheme: Google was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action SocsAuth.Idsrv.Controllers.AccountController.ExternalLogin (SocsAuth.Idsrv) in 148.075ms
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL428UTPCM7A" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 162.3368ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/signin-google?state=CfDJ8<..>&code=<...>j-M8&authuser=0&session_state=1d5<...>94fd&prompt=none
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[9]
      AuthenticationScheme: SocsAuthentication was not authenticated.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: No authentication handler is configured to handle the scheme: idsrv.external
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.FederatedSignOutMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL428UTPCM7A" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1167.3081ms 500 text/html; charset=utf-8
```

**Comment by leastprivilege** [comment]
You also need to setup cookie middleware for the external sign in.

https://identityserver4.readthedocs.io/en/release/topics/signin_external_providers.html

**Comment by tweek82** [comment]
Thank you for your very quick response. I understand things a bit better now. Below is my working code if anyone is interested.

```
public void ConfigureServices(IServiceCollection services)
{
    var idsrv = services.AddIdentityServer(SetIdentityServerOptions)
        .AddTemporarySigningCredential()
        .AddInMemoryApiResources(ApiResourcesConfiguration.GetApiResources())
        .AddInMemoryClients(ClientsConfiguration.GetClients())
        .AddInMemoryIdentityResources(IdentityResourcesConfiguration.GetIdentityResources())
        .AddTestUsers(UsersConfiguration.GetUsers());

    services.AddAntiforgery(opts => opts.CookieName = $"{AuthenticationSchemeConstants.CookiePrefixName}.antiforgery");
    services.AddMvc();
}

private void SetIdentityServerOptions(IdentityServerOptions identityServerOptions)
{
    identityServerOptions.Authentication.AuthenticationScheme = AuthenticationSchemeConstants.DefaultCookieAuthenticationScheme;
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(LogLevel.Debug);
    app.UseDeveloperExceptionPage();

    app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationScheme = AuthenticationSchemeConstants.DefaultCookieAuthenticationScheme,
        CookieName = $"{AuthenticationSchemeConstants.CookiePrefixName}.auth",
        ExpireTimeSpan = TimeSpan.FromMinutes(20),
        SlidingExpiration = true,
        AutomaticAuthenticate = false,
        AutomaticChallenge = false
    });

    app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationScheme = AuthenticationSchemeConstants.ExternalCookieAuthenticationScheme,
        AutomaticAuthenticate = false,
        AutomaticChallenge = false
    });

    app.UseIdentityServer();

    app.UseGoogleAuthentication(new GoogleOptions
    {
        AuthenticationScheme = "Google",
        SignInScheme = AuthenticationSchemeConstants.ExternalCookieAuthenticationScheme,
        AccessType = "offline",
        ClientId = "<..>",
        ClientSecret = "<..>",
        Scope =
        {
            "https://www.googleapis.com/auth/plus.me",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
        }
    });

    app.UseMicrosoftAccountAuthentication(new MicrosoftAccountOptions
    {
        //https://apps.dev.microsoft.com/?mkt=en-us#/appList
        AuthenticationScheme = "Microsoft",
        SignInScheme = AuthenticationSchemeConstants.ExternalCookieAuthenticationScheme,
        ClientId = "<..>",
        ClientSecret = "<..>",
    });

    app.UseTwitterAuthentication(new TwitterOptions
    {
        AuthenticationScheme = "Twitter",
        SignInScheme = AuthenticationSchemeConstants.ExternalCookieAuthenticationScheme,
        ConsumerKey = "<..>",
        ConsumerSecret = "<..>",
    });

    app.UseStaticFiles();
    app.UseMvcWithDefaultRoute();
}
```

**Comment by ardalis** [comment]
Is AuthenticationSchemeConstants your own code, @tweek82 ? I'm not finding it anywhere in IdentityServer's namespaces.

**Comment by NickBrooks** [comment]
Further to this - I've done as followed and configured CookieAuth as follows:

```C#
app.UseGoogleAuthentication(new GoogleOptions
            {
                AuthenticationScheme = "Google",
                DisplayName = "Google",
                AccessType = "offline",
                SignInScheme = "Identity.External",
                ClientId = "id",
                ClientSecret = "supersecret",
                Scope =
                {
                    "https://www.googleapis.com/auth/plus.me",
                    "https://www.googleapis.com/auth/userinfo.email",
                    "https://www.googleapis.com/auth/userinfo.profile"
                }
            });

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "idsrv.external",
                AutomaticAuthenticate = true,
                AutomaticChallenge = true
            });
```

I'm using ASP.NET Identity so my `SignInScheme` is set to `"Identity.External"` as per QuickStart documentation, however my code hits [this exception in AccountController](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountController.cs#L173-#L179):

```C#
// read external identity from the temporary cookie
            var info = await HttpContext.Authentication.GetAuthenticateInfoAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme);
            var tempUser = info?.Principal;
            if (tempUser == null)
            {
                throw new Exception("External authentication error");
            }
```

Basically, `HttpContext.Authentication.GetAuthenticateInfoAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme)` returns null... I tried changing the param to "Identity.External" but that doesn't work either....

Any ideas???

**Comment by brockallen** [comment]
When you set `identityServerOptions.Authentication.AuthenticationScheme = CookiePrefixName;` IdSvr does not create any cookie middleware for you (including the external temp cookie).
