### ISSUE TITLE
Exception when using with ASP.NET Core "1.0.0-rc3-21080" and NETCore.App "1.0.0-rc3-002857"

### ISSUE THREAD

**Issue by trystando** [IdentityServer/IdentityServer4#109]
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at IdentityServer4.Core.Hosting.CookieMiddlewareExtensions.ConfigureCookies(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app)
...

**Comment by leastprivilege** [comment]
post RC2 is nothing we test - you are on your own.
