### ISSUE TITLE
Service Fabric IdentityServer4 and ASP.Net Core WebAPI IDX10803: Unable to obtain configuration from: 'https://localhost:xxxx/.well-known/openid-configuration'.

### ISSUE THREAD

**Issue by neil445** [IdentityServer/IdentityServer4#1178]
- [x ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Hi, I'm not sure if this is repetitive, I've read a lot of threads about this error.

I'm using the ASP.NET Core Identity on top of IdentityServer4 as Stateless Reliable ASP.Net Core Service on Service Fabric.

The WebAPI that's being protected is also on Service Fabric as a Stateless Reliable ASP.Net Core Service.

The AngularJS client is all good, we get a 401 upon accessing the API, we get redirected to the login page, we login, we get the token and now we get an error 500 saying that the API is unable to obtain the configurations from the IdentityServer

Both the API and IdentityServer4 are on HTTPS. All of the above is happening while developing in my local computer. Haven't tried to deploy it properly.

I can also get to https://localhost:9999/.well-known/openid-configuration via the browser though.

I'm not sure if this has something to do with my ServiceFabric Setup or something with HTTPS.

Thanks in advance.

### Relevant parts of the log file

I have log file, but I don't see anything telling me that the API made a request for the configuration.
Here's what I'm getting from the API debug output.
```
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 OPTIONS https://localhost:433/api/SampleControllerB  
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 9.3652ms 204 
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 OPTIONS https://localhost:433/api/SampleController  
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 2.4064ms 204 
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET https://localhost:433/api/SampleControllerB  
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET https://localhost:433/api/SampleController  
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Error: Exception occurred while processing message.

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://localhost:9999/.well-known/openid-configuration'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware: Error: Exception occurred while processing message.

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://localhost:9999/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'https://localhost:9999/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
Microsoft.AspNetCore.Server.WebListener.MessagePump: Error: ProcessRequestAsync

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://localhost:9999/.well-known/openid-configuration'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<InitializeAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleInjector.SimpleInjectorAspNetCoreIntegrationExtensions.RequestScopingStartupFilter.<<ConfigureRequestScoping>b__3_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.ServiceFabricMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__23.MoveNext()
Microsoft.AspNetCore.Server.WebListener.MessagePump: Error: ProcessRequestAsync

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://localhost:9999/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'https://localhost:9999/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<InitializeAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimpleInjector.SimpleInjectorAspNetCoreIntegrationExtensions.RequestScopingStartupFilter.<<ConfigureRequestScoping>b__3_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.ServiceFabricMiddleware.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.WebListener.MessagePump.<ProcessRequestAsync>d__23.MoveNext()
```

**Comment by neil445** [comment]
I think I know what's the problem now. I'm gonna get a certificate and I'll update on this.

**Comment by Mardoxx** [comment]
I would hazard a guess that the node your API is running on is not the same as the node your IDSrv is running on.

So naturally when Bearer middleware (running on node_0, e.g.) looks for idsrv localhost:9999 (which is running on node_1) it can not resolve it.

A solution would be to use external IP in your bearer middleware (IdentityServer4.AccessTokenValidation e.g.)  (or some clever DNS, I am not good with networking so can not advise here!)

**Comment by Mardoxx** [comment]
A couple of roadblocks that I came across:

Each node needs access to the same SigningCredentials. E.g. pull from KeyVault, or provision each node in the cluster with your certificate. N.B Ensure `NETWORK_SERVICE` account has ACLing for private key read. Either that, or do something like this https://github.com/IdentityServer/IdentityServer4/issues/1159#issuecomment-301241891

You may need to set up DPAPI. Although I'm still unsure as to what configurations need this, see [here](http://docs.identityserver.io/en/release/topics/crypto.html#data-protection).  Each node _will_ need certificate in the certificate store, see https://github.com/aspnet/DataProtection/issues/139#issuecomment-205898117 as to why.

**Comment by neil445** [comment]
@Mardoxx
Thanks!
 The API and IdentityServer4 is on the same node. My SF local cluster is set on 1 Node.

I now used 127.0.0.1 instead of localhost, but still doesn't work in HTTPS.

I'll try to add NETWORK_SERVICE account to the ACL of the certs. I added 'NETWORK SERVICE' not 'NETWORK_SERVICE'. I'll update back.

API App Manifest
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="ConnectIoT.BackOffice.AdminApiAppType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="AdminApi_InstanceCount" DefaultValue="1" />
  </Parameters>
  
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ConnectIoT.BackOffice.AdminApiPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      </ConfigOverride>
    </ConfigOverrides>
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpointHttps" CertificateRef="Cert" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    
    <Service Name="AdminApi">
      <StatelessService ServiceTypeName="AdminApiType" InstanceCount="[AdminApi_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Certificates>
    <EndpointCertificate X509FindValue="somevaluehere" Name="Cert" />
  </Certificates>
</ApplicationManifest>

==============================================

IdentityServer4 AppManifest

<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="ConnectIoT.AuthenticationServerAppType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="AuthenticationServer_InstanceCount" DefaultValue="1" />
  </Parameters>
  
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ConnectIoT.AuthenticationServerPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      </ConfigOverrides>
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpointHttps" CertificateRef="Cert" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    
    <Service Name="AuthenticationServer">
      <StatelessService ServiceTypeName="AuthenticationServerType" InstanceCount="[AuthenticationServer_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Certificates>
    <EndpointCertificate X509FindValue="somevaluehere" Name="Cert" />
  </Certificates>
</ApplicationManifest>

**Comment by neil445** [comment]
API Appmanifest

<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="ConnectIoT.BackOffice.AdminApiAppType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="AdminApi_InstanceCount" DefaultValue="1" />
  </Parameters>
  
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ConnectIoT.BackOffice.AdminApiPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      </ConfigOverride>
    </ConfigOverrides>
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpointHttps" CertificateRef="Cert" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    
    <Service Name="AdminApi">
      <StatelessService ServiceTypeName="AdminApiType" InstanceCount="[AdminApi_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Certificates>
    <EndpointCertificate X509FindValue="somevaluehere" Name="Cert" />
  </Certificates>
</ApplicationManifest>

**Comment by neil445** [comment]
API App Manifest
`<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="ConnectIoT.BackOffice.AdminApiAppType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="AdminApi_InstanceCount" DefaultValue="1" />
  </Parameters>
  
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ConnectIoT.BackOffice.AdminApiPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      </ConfigOverride>
    </ConfigOverrides>
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpointHttps" CertificateRef="Cert" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    
    <Service Name="AdminApi">
      <StatelessService ServiceTypeName="AdminApiType" InstanceCount="[AdminApi_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Certificates>
    <EndpointCertificate X509FindValue="somevaluehere" Name="Cert" />
  </Certificates>
</ApplicationManifest>`

**Comment by neil445** [comment]
API APP MANIFEST

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="ConnectIoT.BackOffice.AdminApiAppType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="AdminApi_InstanceCount" DefaultValue="1" />
  </Parameters>
  <!-- Import the ServiceManifest from the ServicePackage. The ServiceManifestName and ServiceManifestVersion 
       should match the Name and Version attributes of the ServiceManifest element defined in the 
       ServiceManifest.xml file. -->
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ConnectIoT.BackOffice.AdminApiPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      </ConfigOverride>
    </ConfigOverrides>
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpointHttps" CertificateRef="Cert" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    <!-- The section below creates instances of service types, when an instance of this 
         application type is created. You can also create one or more instances of service type using the 
         ServiceFabric PowerShell module.
         
         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
    <Service Name="AdminApi">
      <StatelessService ServiceTypeName="AdminApiType" InstanceCount="[AdminApi_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Certificates>
    <EndpointCertificate X509FindValue="somevaluehere" Name="Cert" />
  </Certificates>
</ApplicationManifest>
```

**Comment by neil445** [comment]
IdentityServer4 AppManifest

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ApplicationTypeName="ConnectIoT.AuthenticationServerAppType" ApplicationTypeVersion="1.0.0" xmlns="http://schemas.microsoft.com/2011/01/fabric">
  <Parameters>
    <Parameter Name="AuthenticationServer_InstanceCount" DefaultValue="1" />
  </Parameters>
  <!-- Import the ServiceManifest from the ServicePackage. The ServiceManifestName and ServiceManifestVersion 
       should match the Name and Version attributes of the ServiceManifest element defined in the 
       ServiceManifest.xml file. -->
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="ConnectIoT.AuthenticationServerPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides>
      </ConfigOverrides>
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpointHttps" CertificateRef="Cert" />
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    <!-- The section below creates instances of service types, when an instance of this 
         application type is created. You can also create one or more instances of service type using the 
         ServiceFabric PowerShell module.
         
         The attribute ServiceTypeName below must match the name defined in the imported ServiceManifest.xml file. -->
    <Service Name="AuthenticationServer">
      <StatelessService ServiceTypeName="AuthenticationServerType" InstanceCount="[AuthenticationServer_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
  <Certificates>
    <EndpointCertificate X509FindValue="somevaluehere" Name="Cert" />
  </Certificates>
</ApplicationManifest>
```

**Comment by neil445** [comment]
errr NETWORK SERVICE is the right name.

**Comment by Mardoxx** [comment]
My apologies, it is `NETWORK SERVICE` without the underscore.

What are your ServiceManifest.xml's like? Any what is your API Client config like -- specifically the Allowed CORS origins?

**Comment by neil445** [comment]
I allowed CORS in the API Startup.cs

`            services.AddCors(options =>
            {
                // this defines a CORS policy called "default"
                options.AddPolicy("default", policy =>
                {
                    policy.WithOrigins("*")
                        .AllowAnyHeader()
                        .AllowAnyMethod();
                });
            });`

If you mean the JS Client Config

`
                new Client
                {
                    ClientId = "adminApp.client",
                    ClientName = "adminApp.client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    RequireConsent = false,

                    RedirectUris =           { "http://localhost:8210/#/auth/callback/" },
                    PostLogoutRedirectUris = { "http://localhost:8210/index.html" },
                    AllowedCorsOrigins =     { "http://localhost:8210" },
                    AlwaysIncludeUserClaimsInIdToken = true,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1",
                        "adminApp.api"
                    }
                }
`

API Service Manifest

```
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="ConnectIoT.BackOffice.AdminApiPkg"
                 Version="1.0.0"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <!-- This is the name of your ServiceType. 
         This name must match the string used in RegisterServiceType call in Program.cs. -->
    <StatelessServiceType ServiceTypeName="AdminApiType" />
  </ServiceTypes>

  <!-- Code package is your service executable. -->
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>ConnectIoT.BackOffice.AdminApi.exe</Program>
        <WorkingFolder>CodePackage</WorkingFolder>
      </ExeHost>
    </EntryPoint>
  </CodePackage>

  <!-- Config package is the contents of the Config directoy under PackageRoot that contains an 
       independently-updateable and versioned set of custom configuration settings for your service. -->
  <ConfigPackage Name="Config" Version="1.0.0" />

  <Resources>
    <Endpoints>
      <!-- This endpoint is used by the communication listener to obtain the port on which to 
           listen. Please note that if your service is partitioned, this port is shared with 
           replicas of different partitions that are placed in your code. -->
      <Endpoint Protocol="https" Name="ServiceEndpointHttps" Type="Input" Port="433" />
    </Endpoints>
  </Resources>
</ServiceManifest>
```

=======
IS4 ServiceManifest
```
<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="ConnectIoT.AuthenticationServerPkg"
                 Version="1.0.0"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    <!-- This is the name of your ServiceType. 
         This name must match the string used in RegisterServiceType call in Program.cs. -->
    <StatelessServiceType ServiceTypeName="AuthenticationServerType" />
  </ServiceTypes>

  <!-- Code package is your service executable. -->
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      <ExeHost>
        <Program>ConnectIoT.AuthenticationServer.exe</Program>
        <WorkingFolder>CodePackage</WorkingFolder>
      </ExeHost>
    </EntryPoint>
  </CodePackage>

  <!-- Config package is the contents of the Config directoy under PackageRoot that contains an 
       independently-updateable and versioned set of custom configuration settings for your service. -->
  <ConfigPackage Name="Config" Version="1.0.0" />

  <Resources>
    <Endpoints>
      <!-- This endpoint is used by the communication listener to obtain the port on which to 
           listen. Please note that if your service is partitioned, this port is shared with 
           replicas of different partitions that are placed in your code. -->
      <Endpoint Protocol="https" Name="ServiceEndpointHttps" Type="Input" Port="9999" />
    </Endpoints>
  </Resources>
</ServiceManifest>
```

**Comment by neil445** [comment]
BTW, both the API and IS4 are using the same certificate.

**Comment by Mardoxx** [comment]
```cs
RedirectUris =           { "http://localhost:8210/#/auth/callback/" },
PostLogoutRedirectUris = { "http://localhost:8210/index.html" },
AllowedCorsOrigins =     { "http://localhost:8210" },
```

Should these not be `https://localhost:443` ?

**Comment by Mardoxx** [comment]
Are they self-signed SSL certificates? Perhaps your computer doesn't trust them so middleware is rejecting them!

**Comment by neil445** [comment]
The thing is, the certificate I'm using is issued for another domain, like *.sample.com
This is outright invalid for the browser, so sometimes when accessing the API, I need to hit the API URL with the browser and deal with the "Your connection is not private" thingy.

I've tried to create a self-signed certificate for 127.0.0.1. I got the thumbprint and used it. However, both the API and IS4 are on error status in SF local cluster manager.

**Comment by Mardoxx** [comment]
I suspect this will be the issue then. For the self signed certificates they need to be installed in LocalMachine/My and have NETWORK SERVICE ACLing. Not entirely sure how you add it as a trusted certificate in windows, I think you just export the cert (without private key) and ad it to Trusted Root CA store.

Try running Idsrv on http and set `RequireHttpsMetadata = false` in your `IdentityServerAuthenticationOptions`.

**Comment by neil445** [comment]
I've done everything with the self-signed certs. Yes, you're right on how to trust the cert. I'll have look around.

Thanks a lot.

**Comment by Mardoxx** [comment]
Not sure what else to suggest, sorry! I have it working in an SF cluster, but I think during local development I did everything over http. I now have it deployed to a standalone SF cluster running inside a dev server however it runs under https with a certificate for `*.ourdomain.com` which points to our IP.

**Comment by neil445** [comment]
@Mardoxx 

no worries, I really appreciate what you have offered.

I was kinda thinking of this also, like what if I deploy in the actual SF Cluster in Azure it would then work.
"Not sure what else to suggest, sorry! I have it working in an SF cluster, but I think during local development I did everything over http. I now have it deployed to a standalone SF cluster running inside a dev server however it runs under https with a trusted certificate for *.ourdomain.com which points to our IP."

for the thumbprint, I don't think I'm copying that hidden character. I am pasting it first in notepad and then remove the spaces before actually pasting it in the manifest.

Again, thanks a lot.

**Comment by Mardoxx** [comment]
I would definitely give it a try!

I would also try over http only, then you can rule out the certificate (or something to do with https) being an issue.

**Comment by neil445** [comment]
I'll close this for now.

**Comment by neil445** [comment]
closing for now
