### ISSUE TITLE
identityserver not authenticating after enable consent screen 

### ISSUE THREAD

**Issue by empitegayan** [IdentityServer/IdentityServer4#1325]
### Issue / Steps to reproduce the problem

I have used identityserver without enabling consent screen and it authenticated user via username password as well as google external provider.

then tried to enable consent screen once i got enable the screen once i confirm consent screen with YES it redirect to {domian}/signin-oidc page but with access_denied  error as i shown below. i directly used sample consent controller am i  missing something after submit consent response?

```
public async Task<IActionResult> Index(ConsentInputModel model)
{
    var result = await _consent.ProcessConsent(model);

    if (result.IsRedirect)
    {
        return Redirect(result.RedirectUri);
    }

    if (result.HasValidationError)
    {
        ModelState.AddModelError("", result.ValidationError);
    }

    if (result.ShowView)
    {
        return View("Index", result.ViewModel);
    }

    return View("Error");
}
```
Thanks 

![internal server error](https://user-images.githubusercontent.com/22542431/28164666-0727dd64-67ee-11e7-8522-748408b741c4.png)
### Relevant parts of the log file

```

      Request starting HTTP/1.1 POST http://localhost:5055/signin-oidc application/x-www-form-urlencoded 373
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[12]
      Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[4]
      Error from RemoteAuthentication: Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'..
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.AggregateException: Unhandled remote failure. (Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.) ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Web.BrowserLink.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
---> (Inner Exception #0) Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.<---

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 73.4381ms 500 text/html; charset=utf-8

```

**Comment by brockallen** [comment]
You need your IdSvr logs, not the client logs

**Comment by empitegayan** [comment]
OK i got the issue i have changed consent UI after change values not properly submitted.

**Comment by bluebaroncanada** [comment]
Had the same problem.  identityserver4_log.txt showed `Error: User denied consent`.  Output from the console was `An error was encountered while handling the remote login. ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'access_denied'`

The problem was, I recreated the login page.  The login button wasn't named `login`.  The `AccountController` checks this and assumes you clicked cancel if it's anything but `login`.

**Comment by Rathavithey** [comment]
![image](https://user-images.githubusercontent.com/29189233/70204948-f7c81c80-1754-11ea-86ff-21a115b02bda.png)

The error had happened after I don't accept consent.
Anyone can help me ?
