### ISSUE TITLE
Exception when posting wrong Content-Type header to introspection

### ISSUE THREAD

**Issue by jwholme2** [IdentityServer/IdentityServer4#1371]
Greetings!

### Issue / Steps to reproduce the problem
There is an unhandled exception when the wrong Content-Type header is specified while POSTing to the introspection endpoint.

Steps to reproduce
Clone the https://github.com/IdentityServer/IdentityServer4.Samples repo
Modify the GetApiResources method to the following:
```
public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource
                {
                           Name = "api1",
                           DisplayName = "api1",
                           Description = "test",
                           ApiSecrets = new List<Secret> {new Secret("secret".Sha256()) },
                           Scopes =
                           {
                               new Scope("test", "Test")
                               {
                                   Description = "test2",
                                   ShowInDiscoveryDocument = false
                               }
                    }
                }
            };
        }
```

POST the following payload
```
POST http://localhost:5000/connect/introspect HTTP/1.1
cache-control: no-cache
Postman-Token: a9b9362f-47ee-4658-957b-c385c889ea48
Content-Type: application/json
Authorization: Basic YXBpMTpzZWNyZXQ=
User-Agent: PostmanRuntime/6.1.6
Accept: */*
Host: localhost:5000
accept-encoding: gzip, deflate
content-length: 0
Connection: keep-alive
```
You should receive a 500 response back and corresponding stacktrace.

### Relevant parts of the log file

```
info: IdentityServer4.Startup[0]
      You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
dbug: IdentityServer4.Hosting.CookieMiddlewareExtensions[0]
      Using built-in CookieAuthentication middleware with scheme: idsrv
dbug: IdentityServer4.Hosting.CookieMiddlewareExtensions[0]
      Adding CookieAuthentication middleware for external authentication with scheme: idsrv.external
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\john.holmes\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
Hosting environment: Development
Content root path: C:\code\IdentityServer4.Samples\Quickstarts\1_ClientCredentials\src\QuickstartIdentityServer
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HL6NNDF8T63S" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HL6NNDF8T63T" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[6]
      Connection id "0HL6NNDF8T63T" received FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HL6NNDF8T63T" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel[7]
      Connection id "0HL6NNDF8T63T" sending FIN.
dbug: Microsoft.AspNetCore.Server.Kestrel[8]
      Connection id "0HL6NNDF8T63T" sent FIN with status "0".
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HL6NNDF8T63T" stopped.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/connect/introspect application/json 0
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[9]
      AuthenticationScheme: idsrv was not authenticated.
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /connect/introspect matched to endpoint type Introspection
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Introspection, creating handler: IdentityServer4.Endpoints.IntrospectionEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.IntrospectionEndpoint for /connect/introspect
trce: IdentityServer4.Endpoints.IntrospectionEndpoint[0]
      Processing introspection request.
dbug: IdentityServer4.Endpoints.IntrospectionEndpoint[0]
      Starting introspection request.
trce: IdentityServer4.Validation.ApiSecretValidator[0]
      Start API validation
dbug: IdentityServer4.Validation.BasicAuthenticationSecretParser[0]
      Start parsing Basic Authentication secret
dbug: IdentityServer4.Validation.SecretParser[0]
      Parser found secret: BasicAuthenticationSecretParser
dbug: IdentityServer4.Validation.SecretParser[0]
      Secret id found: api1
dbug: IdentityServer4.Validation.SecretValidator[0]
      Secret validator success: HashedSharedSecretValidator
dbug: IdentityServer4.Validation.ApiSecretValidator[0]
      API resource validation success
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.InvalidOperationException: Incorrect Content-Type: application/json
         at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Endpoints.IntrospectionEndpoint.<ProcessIntrospectionRequestAsync>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Endpoints.IntrospectionEndpoint.<ProcessAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: Incorrect Content-Type: application/json
   at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.IntrospectionEndpoint.<ProcessIntrospectionRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.IntrospectionEndpoint.<ProcessAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.FederatedSignOutMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL6NNDF8T63S" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 704.4651ms 500 text/html; charset=utf-8

```

Thank you!

**Comment by leastprivilege** [comment]
Thanks for reporting. We'll have a look.

**Comment by brockallen** [comment]
This should be fixed in the latest release. What are you using?

**Comment by jwholme2** [comment]
Hi! Sorry - should of included that. Using IdentityServer4 1.5.0

**Comment by brockallen** [comment]
Then check a later version -- I think it should be already fixed.

**Comment by brockallen** [comment]
I'll close for now -- if you test and it's still not working, please reopen.

**Comment by jwholme2** [comment]
Hi! Finally got around to retesting with IdentityServer4 1.5.2 - and I get the same behavior as 1.5.0. 

Thanks!

**Comment by brockallen** [comment]
I just added a test (https://github.com/IdentityServer/IdentityServer4/commit/a7fbd6e8fc34a761c2fdc216444faf7abae0c1ba) to confirm that this is fixed. I'm not sure why you're still seeing this behavior.

Mind testing against this branch one more time?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
