### ISSUE TITLE
identity server 4 exception with .NET Framework 4.5.2

### ISSUE THREAD

**Issue by jgilbert1** [IdentityServer/IdentityServer4#138]
I am attempting to write an API using identity server 4 for the authorization server.  If I create my project based on ASP.Net Core Web Application (.NET Core) all works well.  If I create my project based on ASP.NET Core Web Application (.NET Framework) it generates the following exception when I attempt to call the API (note this is after a successful call to get a token).

System.AggregateException: One or more errors occurred. (A call to SSPI failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm

I need access from the framework since the database drivers that I need are not supported on .netcore.  What can be done to correct this problem (or any suggestions on how to debug it)?

**Comment by jgilbert1** [comment]
I tried this with 4.6.1 and received the below.  The error still acts like it is around the ssl communication, but it is different.

fail: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[0]
      ConnectionFilter.OnConnection
System.AggregateException: One or more errors occurred. (The handshake failed due to an unexpected packet format.) ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__3.MoveNext()<---

**Comment by leastprivilege** [comment]
please try again with RTM

**Comment by jgilbert1** [comment]
Same result on RTM .netcore with beta4

**Comment by imperugo** [comment]
Same here. Seems it doesn't happen with IISExpress so probably is related to Kestrel.
@jgilbert1 did u find a workaround?

**Comment by imperugo** [comment]
I find a solution with this code

```
.UseKestrel(options =>
				{
					options.NoDelay = true;
					options.UseHttps(new HttpsConnectionFilterOptions()
					{
						SslProtocols = SslProtocols.Tls,
						CheckCertificateRevocation = false,
						ClientCertificateMode = ClientCertificateMode.AllowCertificate,
						ServerCertificate = new System.Security.Cryptography.X509Certificates.X509Certificate2("my.pfx", "certpsw")
					});
				})
```

**Comment by jgilbert1** [comment]
I had to use 4.6.1 to get it to work.  The latest release seems to be 4.5.2
based and might have better luck.  I haven't had a chance to try it yet.
