### ISSUE TITLE
IHttpAuthenticationFeature.Handler is null when

### ISSUE THREAD

**Issue by mfidemraizer** [IdentityServer/IdentityServer4#1403]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

When I try to perform an HTTP/POST against `/connect/token` endpoint, I get a `NullReferenceException` with the following stack trace:

> at IdentityServer4.Hosting.AuthenticationHandler.AuthenticateAsync(AuthenticateContext
> context) 
> at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<GetAuthenticateInfoAsync>d__12.MoveNext()

Debugging into the IdentityServer4's source code I've found that this happens becuase `IHttpAuthenticationFeature` from `HttpContext.Features` is `null`, thus the code falls into the `if(auth == null)` case (see the source code [here](https://github.com/IdentityServer/IdentityServer4/blob/75ac815e744051d8150274743cdd8588eb68abb0/src/IdentityServer4/Hosting/AuthenticationHandler.cs)):

        IHttpAuthenticationFeature GetAuthentication()
        {
            var auth = _context.HttpContext.Features.Get<IHttpAuthenticationFeature>();
            if (auth == null)
            {
                auth = new HttpAuthenticationFeature();
                _context.HttpContext.Features.Set(auth);
            }
            return auth;
        }

My `Startup.ConfigureServices(...)` looks as follows:

    services.AddTransient<IUserStore<IdentityUser>, CustomStore>
    (
        provider => new CustomStore
        (
            Configuration["company:data:legacy:connectionString"]
        )
    );
    
    services.AddIdentity<IdentityUser, IdentityRole>()
            .AddUserManager<IdentityUserManager>()
            .AddDefaultTokenProviders();
    
    services.AddIdentityServer()
            .AddTemporarySigningCredential()
            .AddInMemoryApiResources(IdentityConfig.GetApiResources())
            .AddInMemoryClients(IdentityConfig.GetClients())
            .AddAspNetIdentity<IdentityUser>();

I can't figure out if I'm missing some service registration or configuration.

### Relevant parts of the log file

```
2017-08-09 12:45:47.207 +02:00 [Information] You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
2017-08-09 12:45:47.529 +02:00 [Debug] Using hosting application's CookieAuthentication middleware with scheme: "Identity.Application"
2017-08-09 12:46:25.342 +02:00 [Information] Request starting HTTP/1.1 POST http://localhost:9999/connect/token application/x-www-form-urlencoded 104
2017-08-09 12:46:25.520 +02:00 [Debug] CORS request made for path: "/connect/token" from origin: "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop"
2017-08-09 12:46:25.554 +02:00 [Debug] Client list checked and origin: "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop" is not allowed
2017-08-09 12:46:25.562 +02:00 [Warning] CorsPolicyService did not allow origin: "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop"
2017-08-09 12:46:25.952 +02:00 [Error] Connection id ""0HL6V2FGK0VT3"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer4.Hosting.AuthenticationHandler.AuthenticateAsync(AuthenticateContext context)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<GetAuthenticateInfoAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Extensions.HttpContextExtensions.<GetIdentityServerUserInfoAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Services.DefaultSessionIdService.<GetCurrentSessionIdAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Services.DefaultSessionIdService.<EnsureSessionCookieAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationHandler.<InitAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
2017-08-09 12:46:27.118 +02:00 [Information] Request finished in 2080.643ms 500 
```

**Comment by brockallen** [comment]
Are you working under AspNetCore 2?

**Comment by mfidemraizer** [comment]
@brockallen Nope, it's 1.1

**Comment by brockallen** [comment]
Did you call AddIdentity in the MW pipeline (in `Configure`), and is it prior to `AddIdentityServer`?

**Comment by mfidemraizer** [comment]
Yes, as I've already demonstrated in my initial comment (you can see there a code snippet).

**Comment by brockallen** [comment]
What you showed above was the DI config, not the MW pipeline config.

**Comment by leastprivilege** [comment]
You need to make a repro available.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
