### ISSUE TITLE
Preview 3 - Exception using ConfigurationStore

### ISSUE THREAD

**Issue by rpannell** [IdentityServer/IdentityServer4#1427]
I am working on the latest preview and I am getting an exception when using a ConfigurationStore and OperationalStore.  If I remove them and use the InMemory* it works.

```
services.AddIdentityServer(options =>
				{
					options.Events.RaiseSuccessEvents = true;
					options.Events.RaiseFailureEvents = true;
					options.Events.RaiseErrorEvents = true;
				})
				//.AddTemporarySigningCredential()
				.AddSigningCredential(cert)
				.AddConfigurationStore(builder =>
					builder.UseSqlServer(connectionString, options =>
						options.MigrationsAssembly(migrationsAssembly)))
				.AddOperationalStore(builder =>
					builder.UseSqlServer(connectionString, options =>
						options.MigrationsAssembly(migrationsAssembly)))
				.AddProfileService<WebFrameworkProfileService>()
				.AddResourceOwnerValidator<WebFrameworkPasswordValidator>();
```

Here is the exception.

```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`1<Microsoft.EntityFrameworkCore.DbContextOptionsBuilder>, Microsoft.Extensions.DependencyInjection.ServiceLifetime)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.IdentityServerEntityFrameworkBuilderExtensions.AddConfigurationStore(IIdentityServerBuilder builder, Action`1 dbContextOptionsAction, Action`1 storeOptionsAction)
   at Login.Service.Startup.ConfigureServices(IServiceCollection services) in C:\Code\Testing\Research\IdentityServer4\Login.Service\Login.Service\Startup.cs:line 97
```

I know Preview3 is beta.  But I wanted to make sure this error was known, or am I using the ConfigurationStore and OperationalStore incorrectly for .NET Core 2.0.

Thanks!

**Comment by lpghartz** [comment]
For what its worth, I'm in the midst of upgrading some prototype code that was written earlier this year against netcore 1.1 to 2.0, and I'm seeing the same error on 1.5.2, so it may not be related to the preview version vs release version of IS4, but rather something specific to the 1.1->2.0 changes.

**Comment by leastprivilege** [comment]
The EF repos are not updated to 2.0 yet.
