### ISSUE TITLE
asp.net core  upgrade to 2.0 error

### ISSUE THREAD

**Issue by springe2004** [IdentityServer/IdentityServer4#1447]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

+		$exception	{System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthenticationServiceCollectionExtensions.AddAuthentication(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCore.AddRequiredPlatformServices(IIdentityServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.IdentityServerServiceCollectionExtensions.AddIdentityServer(IServiceCollection services)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by springe2004** [comment]
$exception	{System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthenticationServiceCollectionExtensions.AddAuthentication(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCore.AddRequiredPlatformServices(IIdentityServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.IdentityServerServiceCollectionExtensions.AddIdentityServer(IServiceCollection services)

**Comment by leastprivilege** [comment]
invalid.
