### ISSUE TITLE
Using TestUsers for password flow causes `ArgumentNullException`

### ISSUE THREAD

**Issue by tymarats** [IdentityServer/IdentityServer4#1461]
### Issue / Steps to reproduce the problem

When using `TestUser` list, password flow does not work.

`Startup.cs/ConfigureServices.cs`:

            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddTestUsers(Config.GetTestUsers())
                .AddInMemoryClients(Config.GetClients());

`Config.cs`:

        public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "web",

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPasswordAndClientCredentials,

                    // secret for authentication
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    // scopes that client has access to
                    AllowedScopes = { "api1" }
                }
            };
        }

        public static List<TestUser> GetTestUsers()
        {
            return new[] {
                new TestUser
                {
                    Username = "admin",
                    Password = "secret",
                    Claims = new[]
                    {
                        new Claim(ClaimTypes.Name, "Administrator"),
                        new Claim(ClaimTypes.Role, "Administrator"),
                        new Claim(ClaimTypes.Email, "admin@test.com"),
                        // Also tried this one, but to no avail:
                        new Claim("AspNet.Identity.SecurityStamp", Guid.NewGuid().ToString())
                    },
                }
            }.ToList();
        }

When POST-ing correct client_id, client_secret, scope, username and password to the http://localhost:5000/connect/token (with `grant_type` of `password`), `ArgumentNullException` occurs in `System.Security.Claims.Claim..ctor`.

### Relevant parts of the log file

```
IdentityServer4.Hosting.IdentityServerMiddleware:Critical: Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
   at System.Security.Claims.Claim..ctor(String type, String value)
   at IdentityServer4.Validation.GrantValidationResult..ctor(String subject, String authenticationMethod, DateTime authTime, IEnumerable`1 claims, String identityProvider, Dictionary`2 customResponse)
   at IdentityServer4.Test.TestUserResourceOwnerPasswordValidator.ValidateAsync(ResourceOwnerPasswordValidationContext context)
   at IdentityServer4.Validation.TokenRequestValidator.<ValidateResourceOwnerCredentialRequestAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Validation.TokenRequestValidator.<RunValidationAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Validation.TokenRequestValidator.<ValidateRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.TokenEndpoint.<ProcessTokenRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.TokenEndpoint.<ProcessAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__4.MoveNext()

```

**Comment by tymarats** [comment]
Oops, seems like I missed to set `SubjectId`. Maybe the error message should be a bit more descriptive?

**Comment by leastprivilege** [comment]
Thanks. I added an additional check,
