### ISSUE TITLE
get token exception

### ISSUE THREAD

**Issue by cnblogsTim** [IdentityServer/IdentityServer4#1495]
```
 Microsoft.EntityFrameworkCore.Database.Command[200102]
      Failed executing DbCommand (34ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [x].[Id], [x].[AbsoluteRefreshTokenLifetime], [x].[AccessTokenLifetime], [x].[AccessTokenType], [x].[AllowAccessTokensViaBrowser], [x].[AllowOfflineAccess], [x].[AllowPlainTextPkce], [x].[AllowRememberConsent], [x].[AlwaysIncludeUserClaimsInIdToken], [x].[AlwaysSendClientClaims], [x].[AuthorizationCodeLifetime], [x].[BackChannelLogoutSessionRequired], [x].[BackChannelLogoutUri], [x].[ClientId], [x].[ClientName], [x].[ClientUri], [x].[ConsentLifetime], [x].[Description], [x].[EnableLocalLogin], [x].[Enabled], [x].[FrontChannelLogoutSessionRequired], [x].[FrontChannelLogoutUri], [x].[IdentityTokenLifetime], [x].[IncludeJwtId], [x].[LogoUri], [x].[NormalizedClientId], [x].[PrefixClientClaims], [x].[ProtocolType], [x].[RefreshTokenExpiration], [x].[RefreshTokenUsage], [x].[RequireClientSecret], [x].[RequireConsent], [x].[RequirePkce], [x].[SlidingRefreshTokenLifetime], [x].[UpdateAccessTokenClaimsOnRefresh]
      FROM [Clients] AS [x]
      WHERE [x].[ClientId] = @__clientId_0
      ORDER BY [x].[Id]
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'BackChannelLogoutSessionRequired'.
Invalid column name 'BackChannelLogoutUri'.
Invalid column name 'ConsentLifetime'.
Invalid column name 'Description'.
Invalid column name 'FrontChannelLogoutSessionRequired'.
Invalid column name 'FrontChannelLogoutUri'.
Invalid column name 'NormalizedClientId'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
........
```
I used the postman to get the token with the above error
![image](https://user-images.githubusercontent.com/31572788/30099804-639a07ce-9319-11e7-81a0-dc733841920c.png)

### Identity server configuration
```
 services.AddIdentityServer(options =>
            {
                options.IssuerUri = Configuration["ApplicationDTO:IssuerUri"];
                options.UserInteraction.LoginUrl = Configuration["ApplicationDTO:LoginUrl"];
                options.UserInteraction.LogoutUrl =Configuration["ApplicationDTO:LogoutUrl"];
                options.InputLengthRestrictions=new InputLengthRestrictions()
                {
                    UserName = 600,
                    Password = 600,
                };
            })
            .AddSigningCredential(
                    new SigningCredentials(new X509SecurityKey(certkey), SecurityAlgorithms.RsaSha256))
                 .AddConfigurationStore(options =>
                 {
                     options.ConfigureDbContext = builder =>
                         builder.UseSqlServer(connectionString,
                             sql => sql.MigrationsAssembly(migrationsAssembly));
                 })
                 .AddOperationalStore(options =>
                 {
                     options.ConfigureDbContext = builder =>
                         builder.UseSqlServer(connectionString,
                             sql => sql.MigrationsAssembly(migrationsAssembly));
                     options.EnableTokenCleanup = true;
                     options.TokenCleanupInterval = 30;
                 });
```

**Comment by brockallen** [comment]
I guess you didn't do add a migration from your 1.x DB to 2.0?

**Comment by cnblogsTim** [comment]
Thank you for reminding.migration to 2.0,it is ok.

**Comment by odysseus1973** [comment]
Have same problem, how you do migrations ?

**Comment by cnblogsTim** [comment]
@odysseus1973 My data is relatively small,I used the latest idsv4 to generate the database

**Comment by levinhtin** [comment]
@odysseus1973 https://github.com/IdentityServer/IdentityServer4.EntityFramework/tree/dev/src/Host/Migrations

**Comment by LindaLawton** [comment]
Any additional information on how to preform these migrations?

**Comment by wklingler** [comment]
@LindaLawton Did you ever get info about what tables have been changed?  We can't use the migration method so we need to know what columns need to be updated/added.

**Comment by wklingler** [comment]
I compared the two Client files between the two different versions and found these differences:

LogoutUri was replaced by FrontChannelLogoutUri and BackChannelLogoutUri
LogoutSessionRequired was replaced by FrontChannelLogoutSessionRequired and BackChannelLogoutSessionRequired
ConsentLifetime was added (nullable int)
PrefixClientClaims was changed to ClientClaimsPrefix
PairWiseSubjectSalt was added (string)
Properties was added (Dictionary<string, string>)

Does anyone know if I missed anything?  I'm assuming if I update our Clients table with this info then it should work.

**Comment by LindaLawton** [comment]
umm trying to think back.   

add-migration UpgradeIDS4 --context ConfigurationDbContext
add-migration UpgradeIDS4 --context PersistedGrantDbContext
add-migration UpgradeIDS4 -context ApplicationDbContext

You basically just need to add a new migration step for each of your dbcontext.  Then run the application and the migrations should be applied to your database.
