### ISSUE TITLE
The client and server cannot communicate, because they do not possess a common algorithm

### ISSUE THREAD

**Issue by snowjim** [IdentityServer/IdentityServer4#1544]
Hi,

I have a Windows client that uses webRequestHandler and certificate to communicate with the IdentityService4. This as worked fine but now the login have stoped working with the exception :  System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm

I can´t find why. There might be changes in my code that creates this problem but Im not able to find it. This is the client code : 

```
var handler = new WebRequestHandler();
                handler.ServerCertificateValidationCallback = PinPublicKey;
                var loginType = LoginTypeBase.FromLoginType(Business.Entity.Enums.LoginType.SmartCard);
                var client = loginType.GetTokenClient(identityServiceURL, certificate);
                var token = client.RequestCustomGrantAsync(ClientTypes.Siths, "MyApp.wcf offline_access").Result;
```

```
public override TokenClient GetTokenClient(string host, byte[] rawClientCertificate)
        {
            var certificate = new X509Certificate2(rawClientCertificate);
            if (certificate == null)
                throw new Exception("Certificate is missing");

            var handler = new WebRequestHandler();
            handler.ServerCertificateValidationCallback = PinPublicKey;
            var url = $"https://{host}/connect/token";

            handler.ClientCertificates.Add(certificate);

            return new TokenClient(url, ClientTypes.Siths, "secret12312e2", handler);
        }
```

The token will get this exception : Authentication failed because the remote party has closed the transport stream.

After some reading it seems to have something to do with SSL 3.0, TLS 1.0, TLS 1.1 or TLS 1.2? But I dont know how I make sure that the client and service is using the same protocol?

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      ConnectionFilter.OnConnection
System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionFilter.<OnConnectionAsync>d__6.MoveNext()<---
```

**Comment by leastprivilege** [comment]
That's probably more a question for Microsoft. Try the Kestrel repo.
