### ISSUE TITLE
Problem when calling the  services..AddAspNetIdentity<ApplicationUser>()

### ISSUE THREAD

**Issue by ccebreros1** [IdentityServer/IdentityServer4#1586]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Ran the Identity server, and on the Startup.cs the following problem happens. Appears to be when calling the following: 
- services..AddAspNetIdentity<ApplicationUser>()

Using Asp.Net Core 2.0 and the Identity Server 4 2.0 

### Relevant parts of the log file

{System.ArgumentException: GenericArguments[1], 'Project.Identity.Models.ApplicationUser', on 'IdentityServer4.AspNetIdentity.Decorator`2[TService,TImpl]' violates the constraint of type 'TImpl'. ---> System.TypeLoadException: GenericArguments[1], 'Project.Identity.Models.ApplicationUser', on 'IdentityServer4.AspNetIdentity.Decorator`2[TService,TImpl]' violates the constraint of type parameter 'TImpl'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddDecorator[TService](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddTransientDecorator[TService,TImplementation](IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddAspNetIdentity[TUser](IIdentityServerBuilder builder)
   at Project.Identity.Startup.ConfigureServices(IServiceCollection services)

**Comment by brockallen** [comment]
Can you move this to the appropriate repo, please? https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/
