### ISSUE TITLE
Getting 401 Unauthorized when doing a patch from a React frontend

### ISSUE THREAD

**Issue by gdubs** [IdentityServer/IdentityServer4#1769]
I wouldn't ask if I got answered from SO. But I'm getting an Unauthorized response whenever I do a patch (and post) from my js frontend. I tried the same request on postman with the same access token and it would successfully go to the controller. Meanwhile, the get with the same token on both frontend and postman would go through the request 

Also included below are the responses that I got during the preflight of CORS and then  the unauthorized response.

Here's the code of the frontend and the request sent to postman

Postman request

```
http://localhost:90909/api/products/3434

    Headers =  { 
       Authorization: Bearer <token>
       Content-Type: application/json-patch+json
    }

    Body: 
    [
        {
         "op" : "replace",
         "path" : "/DESCRIPTION",
         "value" : "bruhhh"
        }
    ]
```
React

 ```
static update(data){
            let config = {
                data : [],
                headers: { 
                    'Authorization' : 'Bearer ' + data.access_token,
                    'Content-Type' : 'application/json-patch+json'           
                }     
            }

            config.data.push(
                    {
                     "op" : "replace",
                     "path" : "/DESCRIPTION",
                     "value" : "you da best"
                    }

            )

            return axios.patch(root + '/api/products/' + data.product.id, config);

    }

```

This is the error on my api part after the CORS preflight succeeds

FYI, this is the script I followed to enable the logging for Identity Server

```
 public Startup(ILoggerFactory loggerFactory, IHostingEnvironment environment)
        {
            Log.Logger = new LoggerConfiguration()
                            .MinimumLevel.Debug()
                            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                            .MinimumLevel.Override("System", LogEventLevel.Warning)
                            .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
                            .Enrich.FromLogContext()
                            .WriteTo.LiterateConsole(outputTemplate: "IDENTITY SERVER : {Timestamp:HH:mm} [{Level}] ({Name:l}){NewLine} {Message}{NewLine}{Exception}")
                            .CreateLogger();

        }
```

### Relevant parts of the log file

```
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 204.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.HandleNonBodyResponseWrite()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.<WriteAsyncAwaited>d__199.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InventoryApi.Utilities.LogResponseMiddleware.<Invoke>d__4.MoveNext() in F:\My Site Projects\TestProjects\InventoryApi\LogResponseMiddleware.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at InventoryApi.Utilities.LogRequestMiddleware.<Invoke>d__4.MoveNext() in F:\My Site Projects\TestProjects\InventoryApi\LogRequestMiddleware.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

A little below that error is this

```
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2017-11-17T06:41:29.8707635Z","tags":{"ai.cloud.roleInstance":"yay-PC","ai.operation.parentId":"|991e3c32-48996467406a21a4.","ai.operation.name":"PATCH Products/Update [id]","ai.location.ip":"127.0.0.1","ai.operation.id":"991e3c32-48996467406a21a4","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.internal.nodeName":"yay-PC","ai.application.ver":"1.0.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"AuthenticationScheme: Bearer was challenged.","severityLevel":"Information","properties":{"AuthenticationScheme":"Bearer","CategoryName":"Microsoft.AspNetCore.Builder.IdentityServerAuthenticationHandler","AspNetCoreEnvironment":"Development","DeveloperMode":"true","{OriginalFormat}":"AuthenticationScheme: {AuthenticationScheme} was challenged."}}}}
Microsoft.AspNetCore.Builder.IdentityServerAuthenticationHandler:Information: AuthenticationScheme: Bearer was challenged.
```
And then this

```
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2017-11-17T06:41:29.8847643Z","tags":{"ai.cloud.roleInstance":"yay-PC","ai.operation.parentId":"|991e3c32-48996467406a21a4.","ai.operation.name":"PATCH Products/Update [id]","ai.location.ip":"127.0.0.1","ai.operation.id":"991e3c32-48996467406a21a4","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.internal.nodeName":"yay-PC","ai.application.ver":"1.0.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Request finished in 61.62ms 401","severityLevel":"Information","properties":{"StatusCode":"401","ElapsedMilliseconds":"61.62","CategoryName":"Microsoft.AspNetCore.Hosting.Internal.WebHost","AspNetCoreEnvironment":"Development","DeveloperMode":"true"}}}}
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 61.62ms 401 
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2017-11-17T06:41:29.8237608Z","tags":{"ai.cloud.roleInstance":"yay-PC","ai.operation.name":"PATCH Products/Update [id]","ai.location.ip":"127.0.0.1","ai.operation.id":"991e3c32-48996467406a21a4","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.internal.nodeName":"yay-PC","ai.application.ver":"1.0.0.0"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|991e3c32-48996467406a21a4.","name":"PATCH Products/Update [id]","duration":"00:00:00.0711386","success":false,"responseCode":"401","url":"http://localhost:90909/api/products/1020","properties":{"httpMethod":"PATCH","AspNetCoreEnvironment":"Development","DeveloperMode":"true"}}}}
```

Here's the responses during the CORS preflight and after the real request

This is the response when the 204 invalid exception happens

```
General
Request URL:http://localhost:90909/api/products/1020
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:[::1]:90909
Referrer Policy:no-referrer-when-downgrade
Response:
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:content-type
Access-Control-Allow-Methods:PATCH
Access-Control-Allow-Origin:http://localhost:99999
Date:Wed, 15 Nov 2017 04:24:24 GMT
Server:Kestrel
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?RjpcTXkgU2l0ZSBQcm9qZWN0c1xUZXN0UHJvamVjdHasdfaseemVudG9yeUFwaVxhcGlccHJvZHVjdHNcMTAyMA==?=
Request Header:
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:PATCH
Connection:keep-alive
Host:localhost:90909
Origin:http://localhost:99999
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

This is the response of the 401

```
General
Request URL:http://localhost:90909/api/products/1020
Request Method:PATCH
Status Code:401 Unauthorized
Remote Address:[::1]:90909
Referrer Policy:no-referrer-when-downgrade
Response Header
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:99999
Content-Length:0
Date:Wed, 15 Nov 2017 04:24:24 GMT
Server:Kestrel
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?RjpcTXkgU2l0ZSBQcm9qZWN0c1xUZXN0UHJvamVjdHasdfaseemVudG9yeUFwaVxhcGlccHJvZHVjdHNcMTAyMA==?=
Request Header
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
Content-Length:850
Content-Type:application/json;charset=UTF-8
Host:localhost:90909
Origin:http://localhost:99999
Referer:http://localhost:99999/inventory/products
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Request Payload
{data: [{op: "replace", path: "/DESCRIPTION", value: "you da best"}], headers: {,…}}
data
:
[{op: "replace", path: "/DESCRIPTION", value: "you da best"}]
headers
:
{,…}
```

If I did not configure the logging please let me know. I just want to know what's causing the 401 on the Identity Server. I was assuming that the access token was not getting passed after the preflight. But I don't know how to check if it does go through. 

Here's a more complete description of the problem https://stackoverflow.com/questions/47299422/cors-on-net-core-api-returns-401-unauthorized-from-axios-request

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
