### ISSUE TITLE
Discovery endpoint https://xxx/.well-known/openid-configuration is unavailable - Certificate doesn't work on azure server with azure webapp and certstore

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer4#1804]
- [x ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I created self-signed certificate and followed this to use azure cert store (I used this many times, it just doesn't work with IdentityServer):
https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/

I tried to even use  `.AddDeveloperSigningCredential();` and `.AddTemporarySigningCredential();` with no luck. I can access endpoint via browser, but not via api.

It works on localhost and this is how I load it:
```
        public static X509Certificate2 GetCertificate(IHostingEnvironment environment, string thumbprint)
        {
            if (environment.IsDevelopment())
            {
                return new X509Certificate2(Path.Combine(environment.ContentRootPath, "testtest.pfx"), "testtest", X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);
            }

            X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
            try
            {
                store.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection col = store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, false); // Don't validate certs, since the test root isn't installed.
                if (col == null || col.Count == 0)
                    return null;
                return col[0];
            }
            finally
            {
                store.Dispose();
            }
        }
```
For production I use cert store as you can see, but still getting error below.

Startup:
```
            services.AddIdentityServer()
                .AddInMemoryClients(Config.GetClients(Configuration.GetSection("HostSettings:WebAppClientUrl").Value.ToString()))
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddAspNetIdentity<ApplicationUser>()
                .AddProfileService<ProfileService>()
                .AddSigningCredential(Certificate.GetCertificate(_environment, Configuration.GetSection("CertificateSettings:Thumbprint").Value.ToString()));
```

### Relevant parts of the log file

```
Discovery endpoint https://devauth.mygymrr.com/.well-known/openid-configuration is unavailable: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
 at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
 --- End of inner exception stack trace ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
 at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
 at System.Net.Http.HttpClient.<GetContentAsync>d__32`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware.<GetIntrospectionEndpointFromDiscoveryDocument>d__6.MoveNext()
```

**Comment by leastprivilege** [comment]
These logs are not from IdentityServer. You need logging around your code that gets the certs - as well as error logs.

**Comment by nukec** [comment]
Actually chrome is throwing this:
ERR_INSECURE_RESPONSE

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by nukec** [comment]
@brockallen there were issues not related to Idsrv. I had fiddler opened which corrupted access to idsrv. Then I closed fiddler and other issue was that database on api and database on idsrv were different. Close not related.
