### ISSUE TITLE
BackchannelLogoutClient throws exception while generating the logout token

### ISSUE THREAD

**Issue by theofanis** [IdentityServer/IdentityServer4#1824]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I am using the AspNetIdentity Quickstart and am setting up the backchannel for my MvcClient by setting the BackChannelLogoutUri. The BackChannelLogoutClient seems to be called as expected. It appears the HttpContextAccessor injected in IdentityServerTools is unable to get the Issuer Uri.

The problem seems to be in the IdentityServerTools, this [line ](https://github.com/IdentityServer/IdentityServer4/blob/b5dc778874d1344041ed97a843646dac5827abb7/src/IdentityServer4/IdentityServerTools.cs#L49) specifically.

I can make the same call and it works when done inside one of my controllers. Is this maybe related to the fact that the endpoint is registered as singleton and the injected context accessor is problematic?

### Relevant parts of the log file

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5001/connect/endsession/callback?endSessionId=CfDJ8JfvNtWcHLJNr1p_Q044WU-7GEesA6XYh7cfBzKgsu62BgOILSptUvXz6l1n3V0zhpfWiApvFMsGAsLWzmNPFt7PkteeM7ZSx1spqtC5GfTTeYiMGbFgk0bijbtjl7u0uC0KuwhcfDXMmWHUGdbl3eW-4Kp5BemYSC0RP71WIJndw1EwCaIa4XXxqwoV1MFdi9G-bkAvXl4OxnXjHhwUorQXsegvDk9_goBob2lTKhv6fi8eFLvghDRBEJs19xQQl6qSBQDbfUSOXkffjyDKfnQX-qyPZ5xMCyQN1SZ4vfzKBlU-8Q4xy6PXpva7jsBTmg
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /connect/endsession/callback matched to endpoint type Endsession
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Endpoint enabled: Endsession, successfully created handler: IdentityServer4.Endpoints.EndSessionCallbackEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.EndSessionCallbackEndpoint for /connect/endsession/callback
dbug: IdentityServer4.Endpoints.EndSessionCallbackEndpoint[0]
      Processing signout callback request
dbug: IdentityServer4.Validation.EndSessionRequestValidator[0]
      No client front-channel logout URLs
dbug: IdentityServer4.Validation.EndSessionRequestValidator[0]
      Client back-channel logout URLs: http://localhost:5002/signout-oidc
info: IdentityServer4.Endpoints.EndSessionCallbackEndpoint[0]
      Successful signout callback.
dbug: IdentityServer4.Endpoints.EndSessionCallbackEndpoint[0]
      No client front-channel iframe urls
dbug: IdentityServer4.Endpoints.EndSessionCallbackEndpoint[0]
      Client back-channel iframe urls: http://localhost:5002/signout-oidc
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 199.4046ms 200 text/html; charset=UTF-8
fail: IdentityServer4.Endpoints.EndSessionCallbackEndpoint[0]
      Error calling backchannel sign-out urls
System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at IdentityServer4.Extensions.HttpContextExtensions.GetIdentityServerIssuerUri(HttpContext context)
   at IdentityServer4.IdentityServerTools.<IssueJwtAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Infrastructure.BackChannelLogoutClient.<CreateLogoutTokenAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Infrastructure.BackChannelLogoutClient.<SendLogoutAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Endpoints.EndSessionCallbackEndpoint.<>c__DisplayClass5_0.<<InvokeBackChannelClients>b__0>d.MoveNext()
```

**Comment by brockallen** [comment]
Confirmed bug. Something about how our integration tests work doesn't seem to surface this. I'm working on a fix.

**Comment by brockallen** [comment]
Pushed a branch for fixing this: https://github.com/IdentityServer/IdentityServer4/tree/backchannel_bug

@leastprivilege I branched from the last release, not from dev. We could push this in a 2.0.5 patch that way.

**Comment by brockallen** [comment]
Merged. Will release a patch soon.
