### ISSUE TITLE
Chaining multiple WSFederationproviders fails

### ISSUE THREAD

**Issue by Compufreak345** [IdentityServer/IdentityServer4#1855]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

When adding multiple WSFederation-providers and signing in with one, the authenticationprocess fails, because the WSFederation-provider that was not responsible for handling the request throws an error (e.g. "Unsolicited logins are not allowed.") instead of returning false.

I use the following code for adding multiple WSFederation-providers:
```
services.AddAuthentication()
.AddWsFederation("WsFederation_LocalHost", "WsFederation_LocalHost", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.Wtrealm = "urn:aspnetcorerp";
                    options.MetadataAddress = "http://localhost:5000/wsfederation";
                    options.Events.OnTicketReceived += OnTicketReceived;
                    options.RequireHttpsMetadata = false;
                })
                .AddWsFederation("WsFederation_SVN", "WsFederation_SVN", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.Wtrealm = realm;
                    options.MetadataAddress = metadata;
                    options.Events.OnTicketReceived += OnTicketReceived;
                    options.Events.OnSecurityTokenReceived += OnSecurityTokenReceived;
                })
  /// <summary>
        /// Transform the UPN-claim to the sub-claim to be compatible with IdentityServer4
        /// </summary>
        private async Task OnTicketReceived(TicketReceivedContext ticketReceivedContext)
        {
            // Only one identity supported by the current implementation of IdentityServer4
            if (ticketReceivedContext.Principal.Identities.Count() != 1) throw new InvalidOperationException("only a single identity supported");

            var oldIdentity = ticketReceivedContext.Principal.Identity as ClaimsIdentity;
            var oldPrincipal = ticketReceivedContext.Principal;
            oldPrincipal.Clone();
            var claims = new List<Claim>();
            claims.AddRange(oldPrincipal.Claims);
            claims.Add(new Claim("sub", ticketReceivedContext.Principal.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn")));
            var newIdentity = new ClaimsIdentity(claims,oldIdentity.AuthenticationType, oldIdentity.NameClaimType, oldIdentity.RoleClaimType);
            newIdentity.Actor = oldIdentity.Actor;
            ticketReceivedContext.Principal = new ClaimsPrincipal(newIdentity);
        }
```

### Relevant parts of the log file
This is the error that occures:
```
System.Exception: Unsolicited logins are not allowed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.<HandleRequestAsync>d__7.MoveNext() in C:\Develop\git\github\IdentityServer4\src\IdentityServer4\Hosting\FederatedSignOut\AuthenticationRequestHandlerWrapper.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\Develop\git\github\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

The reason for this is [here](https://github.com/IdentityServer/IdentityServer4/blob/81c9c0a428cf75307f20125843ac2a3d4221f5a1/src/IdentityServer4/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs#L39) .
If I replace the line linked with this code:
```
 var result = false;
 try
 {
      result = await _inner.HandleRequestAsync();
  } catch (Exception) { }
```

The authentication succeeds - but I'm not sure if there are security-relevant side effects.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Compufreak345** [comment]
If anyone else stumbles accross this issue, I finally figured it out:

You have to [add different CallbackPaths to your WSFederation-Providers](https://stackoverflow.com/a/47798431/3085985).
