### ISSUE TITLE
A lot of errors from IdentityServer4.EntityFramework.TokenCleanup

### ISSUE THREAD

**Issue by neyromant** [IdentityServer/IdentityServer4#1869]
Hi all.

I am using IdentityServer4 in my .net core 2.0 application which hosted on CentOs and uses **Postgre** as database.
I have a lot of errors in my logs like this: 
```

"LoggerName" : "IdentityServer4.EntityFramework.TokenCleanup"

Exception clearing tokens: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

and 

```
"LoggerName" : "Microsoft.EntityFrameworkCore.Update",
"Message" : "An exception occurred in the database while saving changes for context type 'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext'.\nMicrosoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.\n   at Microsoft.EntityFrameworkCore.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)\n   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)",
        "Exception" : {
            "Type" : "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException",
            "Message" : "Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.",
            "StackTrace" : "   at Microsoft.EntityFrameworkCore.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)\n   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at IdentityServer4.EntityFramework.TokenCleanup.ClearTokens()",
            "InnerException" : null,
            "InnerExceptions" : null
        },
```

**My services works on 2 nodes.**
I suppose the cause of the issue is that there are two nodes the application is working on, so there are two background processes that try to remove expaired tokens from database.

Is the any setting which I can use to modify such kind of behaviour?
Is there a way to ajast  such kind of behaviour so that IdentityServer4 will correctly process such situation?
I wouldn't like to see a lot of error messages in the log file. At the same time I wouldn't lose another really important error messages.

**Comment by brockallen** [comment]
> Is the any setting which I can use to modify such kind of behaviour?

IIRC, in our 2.1 release of the EF library we changed that to be less noisy. Did you try that version?

**Comment by neyromant** [comment]
Thank you for answer.
I am use
```
<PackageReference Include="IdentityServer4" Version="2.0.3" />
<PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.0.0" />
<PackageReference Include="IdentityServer4.EntityFramework" Version="2.0.0" />
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
```

Ok, I will try to use 2.1 release

**Comment by neyromant** [comment]
I was try 2.1 release, but now I have a lot of errors like this:

```
{
    "_id" : ObjectId("5a339d85c759b200e08e4f47"),
    "LocalWriteDate" : ISODate("2017-12-15T13:01:41.085Z"),
    "UTCWriteDate" : ISODate("2017-12-15T10:01:41.085Z"),
    "RemoteIPAddress" : "10.2.62.242",
    "Body" : {
        "Level" : "Error",
        "LocalDate" : "2017-12-15T13:01:35.9496165+03:00",
        "UTCDate" : "2017-12-15T10:01:35.949617Z",
        "LoggerName" : "Microsoft.EntityFrameworkCore.Update",
        "Message" : "An exception occurred in the database while saving changes for context type 'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext'.\nMicrosoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.\n   at Microsoft.EntityFrameworkCore.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)\n   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)",
        "Exception" : {
            "Type" : "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException",
            "Message" : "Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.",
            "StackTrace" : "   at Microsoft.EntityFrameworkCore.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)\n   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at IdentityServer4.EntityFramework.TokenCleanup.ClearTokens()",
            "InnerException" : null,
            "InnerExceptions" : null
        },
        "EventId" : 10000,
        "EventName" : "Microsoft.EntityFrameworkCore.Update.SaveChangesFailed",
        "MachineName" : null,
        "Version" : "1.1.0.14",
        "Parameters" : [ 
            {
                "Key" : "contextType",
                "Value" : "IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext, IdentityServer4.EntityFramework, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null"
            }, 
            {
                "Key" : "newline",
                "Value" : "\n"
            }, 
            {
                "Key" : "error",
                "Value" : {
                    "ClassName" : "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException",
                    "Message" : "Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.",
                    "Data" : null,
                    "InnerException" : null,
                    "HelpURL" : null,
                    "StackTraceString" : "   at Microsoft.EntityFrameworkCore.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)\n   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)\n   at IdentityServer4.EntityFramework.TokenCleanup.ClearTokens()",
                    "RemoteStackTraceString" : null,
                    "RemoteStackIndex" : 0,
                    "ExceptionMethod" : null,
                    "HResult" : -2146233088,
                    "Source" : "Npgsql.EntityFrameworkCore.PostgreSQL",
                    "WatsonBuckets" : null
                }
            }
        ]
    }
}
```

**Comment by brockallen** [comment]
> I was try 2.1 release, but now I have a lot of errors like this:

Sure, but you have to keep in mind: http://docs.identityserver.io/en/release/reference/ef.html#database-creation-and-schema-changes-across-different-versions-of-identityserver

So there have been schema changes.

**Comment by neyromant** [comment]
I tried to create a migration, but Ef generated empty migrations
for both contexts. So, there was no change in the scheme ...

**Comment by brockallen** [comment]
Do you have a callstack for that most recent error?

**Comment by neyromant** [comment]
Yes.
```
An exception occurred in the database while saving changes for context type 'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext'

at Microsoft.EntityFrameworkCore.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader)
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
at IdentityServer4.EntityFramework.TokenCleanup.ClearTokens()
```

**Comment by neyromant** [comment]
A part of my csproj file:
```
<PropertyGroup>
		<TargetFramework>netcoreapp2.0</TargetFramework>
		<RuntimeIdentifiers>win7-x64;win81-x64;linux-x64</RuntimeIdentifiers>
</PropertyGroup>
<ItemGroup>
<PackageReference Include="IdentityServer4" Version="2.0.5" />
<PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.0.0" />
<PackageReference Include="IdentityServer4.EntityFramework" Version="2.1.0" />
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
</ItemGroup>
```

**Comment by brockallen** [comment]
> IIRC, in our 2.1 release of the EF library we changed that to be less noisy. Did you try that version?

Ok, so I found it. Yes, we did change this so it would be less noisy in 2.1, and thus the debug log entry (as opposed to the error log entry). In general, you'd not run in production with debug logging enabled.

**Comment by neyromant** [comment]
I'm sorry, I did not understand. I'm already using <PackageReference Include="IdentityServer4.EntityFramework" Version="2.1.0" />.  I exclude Debug messages from logs.
The above error with Error level.
Could you explain what I'm doing wrong?

**Comment by neyromant** [comment]
Still very strange, that from time to time these errors disappear. And then they reappear. Given that the load on both my nodes is constant.

**Comment by brockallen** [comment]
> Still very strange, that from time to time these errors disappear.

Well, this is understandable, as it's timing based.

>  I exclude Debug messages from logs.

This is the line of code that's emitting that log: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/TokenCleanup.cs#L132, so I'm confused.

**Comment by neyromant** [comment]
I seem to understand.
This messages from inside Ef logger named Microsoft.EntityFrameworkCore.Update

**Comment by Mah3** [comment]
Hi Scott

We are facing the same issue, Using (IdentityServer4.EntityFramework 2.1.1).

I think this happens in case the application works with a load balancer (because it appears only on production ).

 Is there any suggested solution.

**Comment by brockallen** [comment]
You don't have to host the cleanup in IdentityServer. Build a different dedicated host for this function.

**Comment by voroninp** [comment]
@Mah3  We have this issue only in TST, but nothin in ACC and PRD =)

ASP.NET Core 3

```
An exception occurred while iterating over the results of a query for context type 
'IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext'. Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired. 
The timeout period elapsed prior to completion of the operation or the server is not responding.

Exception removing expired grants: Execution Timeout Expired. 
The timeout period elapsed prior to completion of the operation or the server is not responding.

Failed executing DbCommand (30,002ms)

[Parameters=[@__p_0='?' (DbType = Int32)], 
CommandType='Text', 
CommandTimeout='30'] 
SELECT TOP(@__p_0) 
    [p].[Key], [p].[ClientId], [p].[CreationTime], [p].[Data], [p].[Expiration], [p].[SubjectId], [p].[Type] 
FROM [PersistedGrants] AS [p] 
WHERE [p].[Expiration] < GETUTCDATE() 
ORDER BY [p].[Key]
```

And from SSMS similar command executes instantly returning no expired tokens.
