### ISSUE TITLE
Trigger external authentication under Resource Owner Password grant

### ISSUE THREAD

**Issue by stt106** [IdentityServer/IdentityServer4#1929]
### Issue / Steps to reproduce the problem
Sorry if this is really basic; but what's the url for redirecting to the external authentication when using resource owner password grant? Following the doc, I am trying to add Google and then localhost:5001/signin-google returns an error. I did register localhost:5001 in the Google console Authorized JavaScript origins.

This is my config:

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = _authority;
                    options.ApiName = "badders-rank-api";
                    options.RequireHttpsMetadata = false;
                    //options.ApiSecret = "dragonfly";
                    options.SupportedTokens = SupportedTokens.Both;
                });

            // add google
            services.AddAuthentication()
                .AddGoogle("Google", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.ClientId = "myClientId";
                    options.ClientSecret = "myClientSecret";
                });
```

### Relevant parts of the log file

```
2017-12-30 21:43:45.783 +00:00 [INF] You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
2017-12-30 21:43:45.824 +00:00 [DBG] Using Bearer as default scheme for authentication
2017-12-30 21:43:45.825 +00:00 [DBG] Using Bearer as default scheme for sign-in
2017-12-30 21:43:45.825 +00:00 [DBG] Using Bearer as default scheme for sign-out
2017-12-30 21:43:45.826 +00:00 [DBG] Using Bearer as default scheme for challenge
2017-12-30 21:43:45.826 +00:00 [DBG] Using Bearer as default scheme for forbid
2017-12-30 21:43:50.641 +00:00 [INF] Error from RemoteAuthentication: The oauth state was missing or invalid..
2017-12-30 21:43:50.646 +00:00 [ERR] An unhandled exception has occurred while executing the request
System.Exception: The oauth state was missing or invalid.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.<HandleRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by stt106** [comment]
Reported here https://stackoverflow.com/questions/48038353/resource-owner-password-grant-with-external-authentication

Thanks.
