### ISSUE TITLE
Illegal characters in request causes exception while logging

### ISSUE THREAD

**Issue by dskornalijnslijper** [IdentityServer/IdentityServer4#1931]
### Issue / Steps to reproduce the problem
Request an authorisation code and a closing curly bracket to one of the parameter values. For example, added to the response_mode:

connect/authorize?
client_id=testClient&
response_type=code+id_token&
scope=openid+offline_access&
redirect_uri=https%3A%2F%2Ftestclient.somewhere.com%2Fsignin-oidc&
state=123&
nonce=456&
prompt=none&
response_mode=form_post}

AuthorizeRequestValidator.ValidateCoreParameters correctly handles the getting of the response mode and logs the error by calling LogError("Unsupported response_mode: " + responseMode, request);

The characters in responseMode are: "form_post}"

### Relevant parts of the log file

System.AggregateException
  HResult=0x80131500
  Message=An error occurred while writing to logger(s). (Input string was not in a correct format.) (Input string was not in a correct format.) (Input string was not in a correct format.) (Input string was not in a correct format.) (Input string was not in a correct format.)
  Source=Microsoft.Extensions.Logging
  StackTrace:
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
   at IdentityServer4.Validation.AuthorizeRequestValidator.LogError(String message, ValidatedAuthorizeRequest request) in C:\IdentityServer4-dev\src\IdentityServer4\Validation\AuthorizeRequestValidator.cs:line 630

Inner Exception 1:
FormatException: Input string was not in a correct format.

**Full Stack Trace**

crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.AggregateException: An error occurred while writing to logger(s). (Input string was not in a correct format.) (Input string was not in a correct format.) (Input string was not in a correct format.) (Input string was not in a correct format.) (Input string was not in a correct format.) ---> System.FormatException: Input string was not in a correct format.
         at System.Text.StringBuilder.FormatError()
         at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object[] args)
         at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
         at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
         at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
         at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         --- End of inner exception stack trace ---
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
         at IdentityServer4.Validation.AuthorizeRequestValidator.LogError(String message, ValidatedAuthorizeRequest request) in C:\IdentityServer4-dev\src\IdentityServer4\Validation\AuthorizeRequestValidator.cs:line 630
         at IdentityServer4.Validation.AuthorizeRequestValidator.ValidateCoreParameters(ValidatedAuthorizeRequest request) in C:\IdentityServer4-dev\src\IdentityServer4\Validation\AuthorizeRequestValidator.cs:line 278
         at IdentityServer4.Validation.AuthorizeRequestValidator.<ValidateAsync>d__9.MoveNext() in C:\IdentityServer4-dev\src\IdentityServer4\Validation\AuthorizeRequestValidator.cs:line 72
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at IdentityServer4.Endpoints.AuthorizeEndpointBase.<ProcessAuthorizeRequestAsync>d__14.MoveNext() in C:\IdentityServer4-dev\src\IdentityServer4\Endpoints\AuthorizeEndpointBase.cs:line 67
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at IdentityServer4.Endpoints.AuthorizeEndpoint.<ProcessAsync>d__1.MoveNext() in C:\IdentityServer4-dev\src\IdentityServer4\Endpoints\AuthorizeEndpoint.cs:line 55
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\IdentityServer4-dev\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 54
      ---> (Inner Exception #0) System.FormatException: Input string was not in a correct format.
         at System.Text.StringBuilder.FormatError()
         at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object[] args)
         at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
         at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
         at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
         at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

      ---> (Inner Exception #1) System.FormatException: Input string was not in a correct format.
         at System.Text.StringBuilder.FormatError()
         at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object[] args)
         at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
         at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
         at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
         at Microsoft.Extensions.Logging.Debug.DebugLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

      ---> (Inner Exception #2) System.FormatException: Input string was not in a correct format.
         at System.Text.StringBuilder.FormatError()
         at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object[] args)
         at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
         at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
         at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
         at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

      ---> (Inner Exception #3) System.FormatException: Input string was not in a correct format.
         at System.Text.StringBuilder.FormatError()
         at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object[] args)
         at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
         at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
         at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
         at Microsoft.Extensions.Logging.Debug.DebugLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

      ---> (Inner Exception #4) System.FormatException: Input string was not in a correct format.
         at System.Text.StringBuilder.FormatError()
         at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object[] args)
         at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.Format(Object[] values)
         at Microsoft.Extensions.Logging.Internal.FormattedLogValues.ToString()
         at Microsoft.Extensions.Logging.LoggerExtensions.MessageFormatter(Object state, Exception error)
         at Microsoft.ApplicationInsights.AspNetCore.Logging.ApplicationInsightsLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---

**Comment by leastprivilege** [comment]
Interesting - I forwarded this to Microsoft so see if they have an opinion.

**Comment by epignosisx** [comment]
Isn’t the problem here that the message template is being constructed dynamically? My understanding is that message templates should be hard-coded with placeholders that will be passed in from the *params* args (similar to string.Format). See here:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-message-template

**Comment by leastprivilege** [comment]
Yes - that's the problem.

**Comment by leastprivilege** [comment]
Fixed. Will be part of 2.1 - thanks for reporting!

**Comment by dskornalijnslijper** [comment]
Thanks for fixing and creating a fantastic piece of software!
