### ISSUE TITLE
Getting System.Exception: Value cannot be null 

### ISSUE THREAD

**Issue by ryanhmaas** [IdentityServer/IdentityServer4#1932]
### Issue

I'm using Identity Server with Web API. I'm currently working on getting both to work on IIS. I can access the `/.well-known/openid-configuration` endpoint and everything works when I run both solutions locally (changed needed urls to localhost/port combos), however when using the deployed Web API I keep getting 500 errors.

Here is the controller class (matches `/identity` at the controller level) which is intended to support anonymous tokens and resource-password tokens.

```
        [Route("identity")]
    public class IdentityController : ControllerBase
    {
        [HttpPost]
        public async Task<IActionResult> RequestTokenAsync([FromBody] AuthorizationJsonPayload payload)
        {
            //if internal, proceed. Otherwise return an error
            var disco = await DiscoveryClient.GetAsync("https://mydomain.com");
            var tokenClient = new TokenClient(disco.TokenEndpoint, "ro.client", "secret");
            var tokenResponse = tokenClient.RequestResourceOwnerPasswordAsync(payload.Username, payload.Password, "api1").Result;

            if (tokenResponse.IsError)
            {
                return new JsonResult(tokenResponse.Error);
            }
            else
            {
                return new JsonResult(tokenResponse.Json);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            try
            {
                //if internal, proceed. Otherwise return an error
                var disco = await DiscoveryClient.GetAsync("https://mydomain.com");
                //var disco = await DiscoveryClient.GetAsync("http://localhost:5000");

                var tokenClient = new TokenClient(disco.TokenEndpoint, "client", "secret");
                var tokenResponse = tokenClient.RequestClientCredentialsAsync("api1").Result;

                if (tokenResponse.IsError)
                {
                    return new JsonResult(tokenResponse.Error);
                }
                else
                {
                    return new JsonResult(tokenResponse.Json);
                }
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message.ToString(), ex.InnerException);
            }

        }
    }
```
And here is the ConfigureServices method in **Startup.cs**

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials());
            })
                .AddMvcCore()
                .AddAuthorization()
                .AddJsonFormatters();

            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = "https://mydomain.com";
                    options.RequireHttpsMetadata = false;
                    options.ApiName = "api1";
                });
        }
```
Moreover, here is the middleware logging class (since you will see references to it in the log subsequently provided).

**SerilogMiddleware.cs**
```
    class SerilogMiddleware
    {
        const string MessageTemplate = "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms";

        static readonly ILogger Log = Serilog.Log.ForContext<SerilogMiddleware>();

        readonly RequestDelegate _next;

        public SerilogMiddleware(RequestDelegate next)
        {
            if (next == null) throw new ArgumentNullException(nameof(next));
            _next = next;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            if (httpContext == null) throw new ArgumentNullException(nameof(httpContext));

            var start = Stopwatch.GetTimestamp();
            try
            {
                await _next(httpContext);
                var elapsedMs = GetElapsedMilliseconds(start, Stopwatch.GetTimestamp());

                var statusCode = httpContext.Response?.StatusCode;
                var level = statusCode > 499 ? LogEventLevel.Error : LogEventLevel.Information;

                var log = level == LogEventLevel.Error ? LogForErrorContext(httpContext) : Log;
                log.Write(level, MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, statusCode, elapsedMs);
            }
            // Never caught, because `LogException()` returns false.
            catch (Exception ex) when (LogException(httpContext, GetElapsedMilliseconds(start, Stopwatch.GetTimestamp()), ex)) { }
        }

        static bool LogException(HttpContext httpContext, double elapsedMs, Exception ex)
        {
            LogForErrorContext(httpContext)
                .Error(ex, MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, 500, elapsedMs);

            return false;
        }

        static ILogger LogForErrorContext(HttpContext httpContext)
        {
            var request = httpContext.Request;

            var result = Log
                .ForContext("RequestHeaders", request.Headers.ToDictionary(h => h.Key, h => h.Value.ToString()), destructureObjects: true)
                .ForContext("RequestHost", request.Host)
                .ForContext("RequestProtocol", request.Protocol);

            if (request.HasFormContentType)
                result = result.ForContext("RequestForm", request.Form.ToDictionary(v => v.Key, v => v.Value.ToString()));

            return result;
        }

        static double GetElapsedMilliseconds(long start, long stop)
        {
            return (stop - start) * 1000 / (double)Stopwatch.Frequency;
        }
    }
```

I am using Entity as part of this as well (for the Resource Ownership bit) and have noticed that there are similar errors, such as [this](https://stackoverflow.com/questions/16281133/value-cannot-be-null-parameter-name-source). Perhaps it's an issue with the connection string instead of a setting, or configuration setup, of Identity? Or maybe it's data-related? I am using an existing DB with fields that may be null...

Any thoughts would be greatly appreciated, thank you!

### Relevant parts of the log file

```
2018-01-01 12:08:29.728 -05:00 [ERR] HTTP GET /identity responded 500 in 164.5745 ms
System.Exception: Value cannot be null.
Parameter name: address
   at IdentityAPI.Controllers.IdentityController.<Get>d__1.MoveNext() in C:\wsp\Dev WorkSpace\TFS\WSPCode\ObjectCode\WSPObjects\Main\IdentityAuthentication\IdentityAPI\Controllers\IdentityController.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityAPI.SerilogMiddleware.<Invoke>d__4.MoveNext()
```

**Comment by leastprivilege** [comment]
well - looks like you need to do some null checking..

also check `disco.IsError`

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by ryanhmaas** [comment]
Sorry for the delay - been working on other items. I realized my logging got rid of some important lines in the logs, so now the log looks like the following: 

```
  System.ArgumentNullException: Value cannot be null.
Parameter name: address
   at IdentityModel.Client.TokenClient..ctor(String address, HttpMessageHandler innerHttpMessageHandler)
   at IdentityModel.Client.TokenClient..ctor(String address, String clientId, String clientSecret, HttpMessageHandler innerHttpMessageHandler, AuthenticationStyle style)
   at IdentityAPI.Controllers.IdentityController.<Get>d__2.MoveNext()...
```

That gave me the information I needed - the application couldn't resolve the address itself (DNS lookup issue). I updated my hosts file and voila, finally got some responses.

**Comment by Robban1980** [comment]
@ryanhmaas thanks for the update, I intermittently experience this issue where address i null, not thinking that it was the disco.TokenEndpoint that was null.
Now i can solve these issue :)
