### ISSUE TITLE
PersistentGrantDbContext migrations fail when retrying after initial failure.

### ISSUE THREAD

**Issue by Bobby-Schmitt** [IdentityServer/IdentityServer4#1941]
Hello,

### Background
I am running IdentityServer4 in a docker container. 

I am following the directions from https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html for using EntityFramework. 

I am using MySql as the backing store for the operational store. I am using the Pomelo.EntityFrameworkCore.MySql provider, version 2.0.1.

I am running MySql as a separate docker container. I do not think Docker plays into the issue, but I haven't tried running completely without Docker.

### Issue / Steps to reproduce the problem
The start of the issue was sometimes the identity server container would start up and call the Migrate function before MySql was ready for connections. As part of our plan to mitigate this issue, I added a retry policy around the call to Migrate during startup, to wait and try again if the call fails.

The issue I ran into trying this was if the initial call to Migrate fails, all calls to Migrate after that fail with the same exception.

I tried to minimize down to the simplest code to reproduce the issue and here is some code that shows the issue:
```
private void InitializeDatabase(IApplicationBuilder app)
{
	bool initialized = false;
	var retryDelay = TimeSpan.FromSeconds(15);

	while (!initialized)
	{
		try
		{
			using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
			{
				using (var persistentGrantDbContext =
					serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>())
				{
					persistentGrantDbContext.Database.Migrate();
					initialized = true;
				}
			}
		}
		catch (Exception exception)
		{
			this.logger.LogWarning(exception, $"Unable to initialize persistent grant database: {exception.Message}. Retrying again in {retryDelay}.");
			Thread.Sleep(retryDelay);
		}
	}
}
```

To reproduce this, I have two docker containers, one for identity server and one for MySql. 
I start only the identity server container and wait for it to hit the retry loop and fail at least once. 
I then start the MySql container. 
Once the MySql container is ready, I would expect the call to migrate to start working. 
Instead, it continues to fail with the same exception.

Here is the exception I am getting back:
```
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Unable to connect to any of the specified MySQL hosts.
  Source=MySqlConnector
  StackTrace:
"   at MySqlConnector.Core.ServerSession.<ConnectAsync>d__56.MoveNext() in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\Core\\ServerSession.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__77.MoveNext() in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\MySql.Data.MySqlClient\\MySqlConnection.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__19.MoveNext() in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\MySql.Data.MySqlClient\\MySqlConnection.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\\projects\\mysqlconnector\\src\\MySqlConnector\\MySql.Data.MySqlClient\\MySqlConnection.cs:line 137
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlConnectionSettings.<>c__DisplayClass2_0.<GetSettings>b__0(String key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlSmartTypeMapper.MaybeConvertMapping(RelationalTypeMapping mapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapper.IsTypeMapped(Type clrType)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.IsCandidatePrimitiveProperty(PropertyInfo propertyInfo)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Identity.Server.Startup.InitializeDatabase(IApplicationBuilder app) in C:\\code\\ccp-identity\\src\\Identity.Server\\Startup.cs:line 228"
```

I did try debugging into the issue and found some interesting things, but nothing to show why it is failing.

1. If I create a connection to MySql manually in code, it works the way I expect: when the server is down, it fails, and when the server is up, it works.
```
var connectionStringBuilder = CreateMySqlConnectionStringBuilder();
using (var connection = new MySqlConnection(connectionStringBuilder.ToString()))
{
    connection.Open();
}
```

2. If I create a separate ```DbContext```, not the IdentityServer's ```PersistedGrantDbContext```, and use that in the loop instead, it works correctly.

3. I pulled the code for MySqlConnection from GitHub and built a debug version and used it. I set breakpoints in the MySqlConnection.Open() function listed in the callstack. When I step through the code, I get the first call into Migrate() hitting MySqlConnection.Open(). After that first failure, the second call to Migrate does not hit the breakpoint in MySqlConnection.Open(), but the callstack I get back shows it in there. As far as I can tell from the MySql server, I did not see any actual connection attempt made after the first failure. It almost feels like the exception is being saved and rethrown after the first failure.

4. After the first failure attempt, after I wait for the MySql server to be ready, I can connect to the MySql server just fine from other applications and code. If I restart the identity server docker container, it connects just fine.

5. As far as I can tell, each time through the loop I am getting a new instance of the ```PersistedGrantDbContext``` class, it is not reusing an instance from a previous failure.

There are 4 main places I can see this issue coming from:
1. Entity Framework
2. MySqlConnector
3. Pomelo.EntityFrameworkCore.MySql provider
4. IdentityServer

I don't feel like it is the entity framework itself, because if I create a simple DbContext and use that to call .Migrate(), it works as I expect it. Going that route, it is using Entity Framework, MySqlConnector, and Pomelo.EntityFrameworkCore.MySql provider without issue. I only see the issue when using ```PersistedGrandDbContext```.

I have not tried building and debugging IdentityServer DLLs to see where it is failing.

### Relevant parts of the log file
I did not see anything in the log file from this.

**Comment by brockallen** [comment]
My initial design of that `InitializeDatabase` in the samples was not well done. Mainly because there's a chicken and egg issue, which is what I think you have run into. The samples have since been changed/updated with a slightly better workflow. Have a look and see if those work better for you.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by Bobby-Schmitt** [comment]
Do you have a link to the sample you are referring to? I'm still using the code from https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html and can still reproduce the issue. 

I've added a check to make sure the MySql server is available before making the .Migrate() call which does prevent this specific issue from happening.

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Program.cs

**Comment by navidehsa** [comment]
I am also using MySql and IdentityServer4 ,it seem persistedGrantDbContext.Database.Migrate doesn't create the table for me.when I use Sql server it works perfect but not in Mysql.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
