### ISSUE TITLE
Unable to resolve type: IdentityServer4.Endpoints.TokenEndpoint

### ISSUE THREAD

**Issue by StanislavChankov** [IdentityServer/IdentityServer4#2144]
System.InvalidOperationException: Unable to resolve type: IdentityServer4.Endpoints.TokenEndpoint, service name:  ---> System.InvalidOperationException: Unresolved dependency [Target Type: IdentityServer4.Endpoints.TokenEndpoint], [Parameter: requestValidator(IdentityServer4.Validation.ITokenRequestValidator)], [Requested dependency: ServiceType:IdentityServer4.Validation.ITokenRequestValidator, ServiceName:] ---> System.InvalidOperationException: Unresolved dependency [Target Type: IdentityServer4.Validation.TokenRequestValidator], [Parameter: tokenValidator(IdentityServer4.Validation.ITokenValidator)], [Requested dependency: ServiceType:IdentityServer4.Validation.ITokenValidator, ServiceName:] ---> System.InvalidOperationException: Unresolved dependency [Target Type: IdentityServer4.Validation.TokenValidator], [Parameter: keys(IdentityServer4.Services.IKeyMaterialService)], [Requested dependency: ServiceType:IdentityServer4.Services.IKeyMaterialService, ServiceName:] ---> System.InvalidOperationException: Unresolved dependency [Target Type: IdentityServer4.Services.DefaultKeyMaterialService], [Parameter: signingCredential(IdentityServer4.Stores.ISigningCredentialStore)], [Requested dependency: ServiceType:IdentityServer4.Stores.ISigningCredentialStore, ServiceName:]
   at LightInject.ServiceContainer.GetEmitMethodForDependency(Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter)
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateInstanceDelegateIndex(Action`1 emitMethod)
   at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass147_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter)
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateInstanceDelegateIndex(Action`1 emitMethod)
   at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass147_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter)
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateInstanceDelegateIndex(Action`1 emitMethod)
   at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass147_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency)
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter)
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateInstanceDelegateIndex(Action`1 emitMethod)
   at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass147_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
   at LightInject.ServiceContainer.TryGetInstance(Type serviceType)
   at LightInject.Scope.WithThisScope[T](Func`1 function)
   at IdentityServer4.Hosting.EndpointRouter.GetEndpointHandler(Endpoint endpoint, HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\EndpointRouter.cs:line 52
   at IdentityServer4.Hosting.EndpointRouter.Find(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\EndpointRouter.cs:line 39
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\IdentityServerMiddleware.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

### Issue / Steps to reproduce the problem
I am trying to retrieve the token from: http://localhost:5014/connect/token. The application used to return access_token before I add/remove something that is breaking it.
It doesn't matter which end point of IdentityServer I am trying to hit - the exception is the same. The controller end-points are working fine.
Code in Startup.cs
private readonly IConfigurationRoot _configuration;

        public Startup(IHostingEnvironment env)
        {
            _configuration = env.BuildAppConfigurations(DataProtectionConstants.IS_DISCRIMINATOR);
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.ConfigureOptions(_configuration);

            services.AddIdentityServer()
                .AddProfileService<IdentityProfileService>()
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
                .AddInMemoryCaching();

            services.AddMvc();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
            });

            // Add data protection. Isolate the application from other applications.
            //services.AddDataProtection();

            AddIdentityDependencies(services);

            services.AddCorsProvider();

            // Setup all common ScorePoint options and services.
            services.SetupCommonServices(_configuration);

            return services.CreateLightInjectProvider();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();

            app.UseIdentityServer();

            UseSwagger(app);
        }

        private static void AddIdentityDependencies(IServiceCollection services)
        {
            services.AddTransient<IClaimsService, IdentityClaimsService>();
            services.AddSingleton<IResourceStore, ResourcesStore>();
            services.AddSingleton<IClientStore, ClientStore>();
        }
### Relevant package references
    <PackageReference Include="IdentityServer4" Version="2.1.2" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="2.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
```
<log goes here>
```

**Comment by StanislavChankov** [comment]
Relevant references are:    
<PackageReference Include="IdentityServer4" Version="2.1.2" />
<PackageReference Include="IdentityServer4.AccessTokenValidation" Version="2.4.0" />
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />

**Comment by StanislavChankov** [comment]
services.AddIdentityServer()
                .AddProfileService<IdentityProfileService>()
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
                .AddInMemoryCaching();
to:
            services.AddIdentityServer()
                **.AddDeveloperSigningCredential()**
                .AddProfileService<IdentityProfileService>()
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
                .AddInMemoryCaching();
Solved my problem.
