### ISSUE TITLE
NullReferenceException - IdentityServerWithAspIdAndEF Quickstart

### ISSUE THREAD

**Issue by klanglie** [IdentityServer/IdentityServer4#2168]
When I attempt to change the database for 'Quickstarts\Combined_AspNetIdentity_and_EntityFrameworkStorage' from using SqlLite to Sql Server, I get the following error.

Update - This is similar to [https://github.com/IdentityServer/IdentityServer4/issues/2156](url)

`
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer("Data Source=localhost;Initial Catalog=AngularImplicitFlow;User Id=angular;Password=angular;MultipleActiveResultSets=True;"));
`
-----------------------

`{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 keyValuePair)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.SaveChangesFailed(IDiagnosticsLogger`1 diagnostics, DbContext context, Exception exception)
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.<UpdateAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Identity.UserManager`1.<UpdateUserAsync>d__171.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Identity.UserManager`1.<AddClaimsAsync>d__99.MoveNext()}`

**Comment by MPapst** [comment]
HI @klanglie, 
as you updated it. Its the same as #2156, if you dig deeper into the exception you will get the one that states the identity column may not be null.

**Comment by klanglie** [comment]
Okay. Then I will mark this as closed. I fixed the problem in my repo. [https://github.com/klanglie/IdentityServerAngularImplicitFlow](https://github.com/klanglie/IdentityServerAngularImplicitFlow)
