### ISSUE TITLE
integration with IS3

### ISSUE THREAD

**Issue by xunqinbo** [IdentityServer/IdentityServer4#2187]
We have a legacy MVC client based on IS3.
SSO login worked fine, but we encounted an error on AuthorizationCodeReceived event.
we got a 'invalid_client' response.
Is there my config mistake or a compatibility issue?
### here is the code

```
 AuthorizationCodeReceived = async n =>
                    {
                        // use the code to get the access and refresh token
                        var tokenClient = new TokenClient(
                            options.Authority + "/connect/token",
                           options.ClientId,
                            options.ClientSecret);
                        logger.Info(() => JsonConvert.SerializeObject(tokenClient));
                        var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);
                        if (tokenResponse.IsError)
                        {
                            throw new Exception(tokenResponse.Error);
                        }
                        // ...
                    }
```
###  OpenIdConnectAuthenticationOptions
```
{
  "Authority": "http://10.32.153.63:5000",
  "ClientId": "WMS.Admin",
  "ClientSecret": "plain_text",
  "RedirectUri": "http://10.32.153.63/",
  "PostLogoutRedirectUri": "http://10.32.153.63/",
  "ResponseType": "code id_token",
  "TokenValidationParameters": {
    "NameClaimType": "name",
    "RoleClaimType": "role"
  },
  "SignInAsAuthenticationType": "Cookies",
  "Scope": "openid profile"
}
```

###  the client config on server side

```
  {
      "Enabled": true,
      "ClientId": "WMS.Admin",
      "ProtocolType": "oidc",
      "RequireClientSecret": true,
      "ClientName": "WMS admin pane",
      "RequireConsent": false,
      "AllowRememberConsent": false,
      "AllowedGrantTypes": [
        "hybrid",
        "client_credentials"
      ],
      "RequirePkce": false,
      "AllowPlainTextPkce": false,
      "AllowAccessTokensViaBrowser": true,
      "RedirectUris": [
        "http://10.32.153.63/"
      ],
      "PostLogoutRedirectUris": [
        "http://10.32.153.63/"
      ],
      "LogoutSessionRequired": true,
      "AllowOfflineAccess": true,
      "AllowedScopes": [
        "openid",
        "profile",
        "proxy"
      ],
      "AlwaysIncludeUserClaimsInIdToken": true,
      "RefreshTokenUsage": 1,
      "UpdateAccessTokenClaimsOnRefresh": false,
      "RefreshTokenExpiration": 1,
      "AccessTokenType": 0,
      "EnableLocalLogin": true,
      "IncludeJwtId": false,
      "AlwaysSendClientClaims": false,
      "PrefixClientClaims": true,
      "AllowedCorsOrigins": [
        "http://10.32.153.63/"
      ]
    }

```
with hashed secret added programmatically
```
ClientSecrets.Add(new Secret(Config.DefaultPassword.Sha256()));
```

### logs

```
2018-03-30 17:57:33.6772|50|WARN|Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository|Using an in-memory repository. Keys will not be persisted to storage. |url: |action: 
2018-03-30 17:57:33.7406|59|WARN|Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. |url: |action: 
2018-03-30 17:57:33.7631|35|WARN|Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|No XML encryptor configured. Key {c11bf5b1-0acb-4627-91cf-4856d6215cc1} may be persisted to storage in unencrypted form. |url: |action: 
2018-03-30 17:57:33.7914||INFO|IdentityServer4.Startup|You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation. |url: |action: 
2018-03-30 17:57:33.8227||DEBUG|IdentityServer4.Startup|Using Identity.Application as default scheme for authentication |url: |action: 
2018-03-30 17:57:33.8227||DEBUG|IdentityServer4.Startup|Using Identity.External as default scheme for sign-in |url: |action: 
2018-03-30 17:57:33.8227||DEBUG|IdentityServer4.Startup|Using Identity.External as default scheme for sign-out |url: |action: 
2018-03-30 17:57:33.8227||DEBUG|IdentityServer4.Startup|Using Identity.Application as default scheme for challenge |url: |action: 
2018-03-30 17:57:33.8227||DEBUG|IdentityServer4.Startup|Using Identity.Application as default scheme for forbid |url: |action: 
2018-03-30 17:57:34.7328|5|WARN|Microsoft.AspNetCore.Identity.UserManager|User bd789524-78e2-46cf-b0c7-f2eb3f6a967e is already in role administrator. |url: |action: 
2018-03-30 17:57:35.1576||DEBUG|IdentityServer4.Hosting.EndpointRouter|Request path /connect/authorize matched to endpoint type Authorize |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.1742||DEBUG|IdentityServer4.Hosting.EndpointRouter|Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeEndpoint |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.1742||INFO|IdentityServer4.Hosting.IdentityServerMiddleware|Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.1820||DEBUG|IdentityServer4.Endpoints.AuthorizeEndpoint|Start authorize request |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.1977||DEBUG|IdentityServer4.Endpoints.AuthorizeEndpoint|No user present in authorize request |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.1977||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|Start authorize request protocol validation |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.2299||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|Checking for PKCE parameters |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.2299||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|No PKCE used. |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.2807||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.3754||INFO|IdentityServer4.Endpoints.AuthorizeEndpoint|ValidatedAuthorizeRequest
{
  "ClientId": "WMS.Admin",
  "ClientName": "WMS admin pane",
  "RedirectUri": "http://10.32.153.63/",
  "AllowedRedirectUris": [
    "http://10.32.153.63/"
  ],
  "SubjectId": "anonymous",
  "ResponseType": "code id_token",
  "ResponseMode": "form_post",
  "GrantType": "hybrid",
  "RequestedScopes": "openid profile",
  "State": "OpenIdConnect.AuthenticationProperties=TOCmn3FAoIP_37domT2uVbRUx_5tcoIQCE1HtjC_eEBB1Moci8QY4osvg0D3ulgLupZOZXNMbHjZNGdmo9Kx3Eonuxdxa52v_qH1ghj7w6i1qd2lDhmwrHIx-D9TvzyOg4VKaD6Ex5v8u28J7ZTwDvbPYFtJvsXNyWtlkrG1Izvn_6K28NOySVPr64ysj5Sz",
  "Nonce": "636580005129740859.YzcxY2U2NGQtYWUxNy00ZDllLTgyMGMtN2M5YjEyNGNjZDBiZTdkNjZlZDMtNzhiMS00ZTdiLTlkZjMtZjAxMzcwMDE5NzY5",
  "Raw": {
    "client_id": "WMS.Admin",
    "redirect_uri": "http://10.32.153.63/",
    "response_mode": "form_post",
    "response_type": "code id_token",
    "scope": "openid profile",
    "state": "OpenIdConnect.AuthenticationProperties=TOCmn3FAoIP_37domT2uVbRUx_5tcoIQCE1HtjC_eEBB1Moci8QY4osvg0D3ulgLupZOZXNMbHjZNGdmo9Kx3Eonuxdxa52v_qH1ghj7w6i1qd2lDhmwrHIx-D9TvzyOg4VKaD6Ex5v8u28J7ZTwDvbPYFtJvsXNyWtlkrG1Izvn_6K28NOySVPr64ysj5Sz",
    "nonce": "636580005129740859.YzcxY2U2NGQtYWUxNy00ZDllLTgyMGMtN2M5YjEyNGNjZDBiZTdkNjZlZDMtNzhiMS00ZTdiLTlkZjMtZjAxMzcwMDE5NzY5",
    "x-client-SKU": "ID_NET451",
    "x-client-ver": "5.2.1.0"
  }
} |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.3871||INFO|IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator|Showing login: User is not authenticated |url: http://10.32.153.63/connect/authorize|action: 
2018-03-30 17:57:35.7992|7|ERROR|Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery|An exception was thrown while deserializing the token. System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {02b2ef60-0634-4085-b9b1-1bd5bace204d} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)|url: http://10.32.153.63/account/login|action: Login
2018-03-30 17:57:39.3481||DEBUG|IdentityServer4.Hosting.IdentityServerAuthenticationService|Augmenting SignInContext |url: http://10.32.153.63/Account/Login|action: Login
2018-03-30 17:57:39.3481||DEBUG|IdentityServer4.Hosting.IdentityServerAuthenticationService|Adding idp claim with value: local |url: http://10.32.153.63/Account/Login|action: Login
2018-03-30 17:57:39.3481||DEBUG|IdentityServer4.Hosting.IdentityServerAuthenticationService|Adding amr claim with value: pwd |url: http://10.32.153.63/Account/Login|action: Login
2018-03-30 17:57:39.3559||DEBUG|IdentityServer4.Hosting.IdentityServerAuthenticationService|Adding auth_time claim with value: 1522403859 |url: http://10.32.153.63/Account/Login|action: Login
2018-03-30 17:57:39.3559||INFO|Intime.Identity.Server.Controllers.AccountController|User logged in. |url: http://10.32.153.63/Account/Login|action: Login
2018-03-30 17:57:39.5414||DEBUG|IdentityServer4.Hosting.EndpointRouter|Request path /connect/authorize/callback matched to endpoint type Authorize |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5414||DEBUG|IdentityServer4.Hosting.EndpointRouter|Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5414||INFO|IdentityServer4.Hosting.IdentityServerMiddleware|Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5414||DEBUG|IdentityServer4.Endpoints.AuthorizeCallbackEndpoint|Start authorize callback request |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5610||DEBUG|IdentityServer4.Endpoints.AuthorizeCallbackEndpoint|User in authorize request: bd789524-78e2-46cf-b0c7-f2eb3f6a967e |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5610||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|Start authorize request protocol validation |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5610||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|Checking for PKCE parameters |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5610||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|No PKCE used. |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5610||DEBUG|IdentityServer4.Validation.AuthorizeRequestValidator|Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.5610||INFO|IdentityServer4.Endpoints.AuthorizeCallbackEndpoint|ValidatedAuthorizeRequest
{
  "ClientId": "WMS.Admin",
  "ClientName": "WMS admin pane",
  "RedirectUri": "http://10.32.153.63/",
  "AllowedRedirectUris": [
    "http://10.32.153.63/"
  ],
  "SubjectId": "bd789524-78e2-46cf-b0c7-f2eb3f6a967e",
  "ResponseType": "code id_token",
  "ResponseMode": "form_post",
  "GrantType": "hybrid",
  "RequestedScopes": "openid profile",
  "State": "OpenIdConnect.AuthenticationProperties=TOCmn3FAoIP_37domT2uVbRUx_5tcoIQCE1HtjC_eEBB1Moci8QY4osvg0D3ulgLupZOZXNMbHjZNGdmo9Kx3Eonuxdxa52v_qH1ghj7w6i1qd2lDhmwrHIx-D9TvzyOg4VKaD6Ex5v8u28J7ZTwDvbPYFtJvsXNyWtlkrG1Izvn_6K28NOySVPr64ysj5Sz",
  "Nonce": "636580005129740859.YzcxY2U2NGQtYWUxNy00ZDllLTgyMGMtN2M5YjEyNGNjZDBiZTdkNjZlZDMtNzhiMS00ZTdiLTlkZjMtZjAxMzcwMDE5NzY5",
  "SessionId": "d1a9416b9077d41a6928e064e2aa7b4a",
  "Raw": {
    "client_id": "WMS.Admin",
    "redirect_uri": "http://10.32.153.63/",
    "response_mode": "form_post",
    "response_type": "code id_token",
    "scope": "openid profile",
    "state": "OpenIdConnect.AuthenticationProperties=TOCmn3FAoIP_37domT2uVbRUx_5tcoIQCE1HtjC_eEBB1Moci8QY4osvg0D3ulgLupZOZXNMbHjZNGdmo9Kx3Eonuxdxa52v_qH1ghj7w6i1qd2lDhmwrHIx-D9TvzyOg4VKaD6Ex5v8u28J7ZTwDvbPYFtJvsXNyWtlkrG1Izvn_6K28NOySVPr64ysj5Sz",
    "nonce": "636580005129740859.YzcxY2U2NGQtYWUxNy00ZDllLTgyMGMtN2M5YjEyNGNjZDBiZTdkNjZlZDMtNzhiMS00ZTdiLTlkZjMtZjAxMzcwMDE5NzY5",
    "x-client-SKU": "ID_NET451",
    "x-client-ver": "5.2.1.0"
  }
} |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.6068||DEBUG|IdentityServer4.Services.DefaultConsentService|Client is configured to not require consent, no consent is required |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.6068||DEBUG|IdentityServer4.ResponseHandling.AuthorizeResponseGenerator|Creating Hybrid Flow response. |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.6654||DEBUG|IdentityServer4.ResponseHandling.AuthorizeResponseGenerator|Creating Implicit Flow response. |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.6801||DEBUG|IdentityServer4.Services.DefaultClaimsService|Getting claims for identity token for subject: bd789524-78e2-46cf-b0c7-f2eb3f6a967e and client: WMS.Admin |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.8139||INFO|IdentityServer4.Endpoints.AuthorizeCallbackEndpoint|Authorize endpoint response
{
  "SubjectId": "bd789524-78e2-46cf-b0c7-f2eb3f6a967e",
  "ClientId": "WMS.Admin",
  "RedirectUri": "http://10.32.153.63/",
  "State": "OpenIdConnect.AuthenticationProperties=TOCmn3FAoIP_37domT2uVbRUx_5tcoIQCE1HtjC_eEBB1Moci8QY4osvg0D3ulgLupZOZXNMbHjZNGdmo9Kx3Eonuxdxa52v_qH1ghj7w6i1qd2lDhmwrHIx-D9TvzyOg4VKaD6Ex5v8u28J7ZTwDvbPYFtJvsXNyWtlkrG1Izvn_6K28NOySVPr64ysj5Sz",
  "Scope": "openid profile"
} |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:39.8373||DEBUG|IdentityServer4.Hosting.IdentityServerAuthenticationService|Augmenting SignInContext |url: http://10.32.153.63/connect/authorize/callback|action: 
2018-03-30 17:57:40.1772||DEBUG|IdentityServer4.Hosting.EndpointRouter|Request path /connect/token matched to endpoint type Token |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.1840||DEBUG|IdentityServer4.Hosting.EndpointRouter|Endpoint enabled: Token, successfully created handler: IdentityServer4.Endpoints.TokenEndpoint |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.1840||INFO|IdentityServer4.Hosting.IdentityServerMiddleware|Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.1840||DEBUG|IdentityServer4.Endpoints.TokenEndpoint|Start token request. |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2074||DEBUG|IdentityServer4.Validation.ClientSecretValidator|Start client validation |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2152||DEBUG|IdentityServer4.Validation.BasicAuthenticationSecretParser|Start parsing Basic Authentication secret |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2152||DEBUG|IdentityServer4.Validation.SecretParser|Parser found secret: BasicAuthenticationSecretParser |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2152||DEBUG|IdentityServer4.Validation.SecretParser|Secret id found: WMS.Admin |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2289||DEBUG|IdentityServer4.Validation.HashedSharedSecretValidator|No matching hashed secret found. |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2289||DEBUG|IdentityServer4.Validation.SecretValidator|Secret validators could not validate secret |url: http://10.32.153.63/connect/token|action: 
2018-03-30 17:57:40.2289||ERROR|IdentityServer4.Validation.ClientSecretValidator|Client secret validation failed for client: WMS.Admin. |url: http://10.32.153.63/connect/token|action: 
```

**Comment by brockallen** [comment]
You should look into the exceptions in your log file

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
