### ISSUE TITLE
IDX10803: Unable to obtain configuration from CurlException SSL connect error

### ISSUE THREAD

**Issue by vaustral** [IdentityServer/IdentityServer4#2195]
I have a host setup as the following:  asp.net core 2.0.5 - IdentityServer4 | https - obtained from lets Encrypt | load balanced | data protection key stored in azure | docker deployed, 3 containers.

asp.net core 2.0.6 - API | http | docker deployed, 2 containers

All hosted in azure container engine on ACS.

### Issue / Steps to reproduce the problem

Unfortunately i'm not able to reproduce this consistently, but during usage after about 3-5 requests the SSL connect error starts.  See below.

![image](https://user-images.githubusercontent.com/5386554/38278791-b6048968-375a-11e8-9c63-f04ea9d18d65.png)

- If i get on the container deployed and manually execute the curl statement with curl -v [site]/.well-known..] it succeeds.
- Subsequent requests going back to no -v fails, 2 out of 5 times on average.

I realize this may not be part of IdentityServer, but i'm wondering if there's something setup incorrectly in the TLS cipher that could be causing problems with the cert from lets encrypt?

### Relevant parts of the log file

This is the only part of the log i can find that even attributes to the same information.

```
[22:19:06 INF] Failed to authenticate HTTPS connection.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__12.MoveNext()
?[40m?[37mdbug?[39m?[22m?[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[7]
      Connection id "0HLCOT51PFBI8" sending FIN.
?[40m?[37mdbug?[39m?[22m?[49m: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLCOT51PFBI8" stopped.

```

**Comment by vaustral** [comment]
* TCP_NODELAY set
* Connected to id.login.com (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to id.login.com:443 
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0

**Comment by vaustral** [comment]
Mmm, It looks like it's because of a 4096 bit key.

**Comment by vaustral** [comment]
Confirmed, 4k key in kestrel.

**Comment by fshin123** [comment]
Hey vaustral,
I’m having a similar issue as you had here. 

https://github.com/IdentityServer/IdentityServer4/issues/2401

Any chance you can give me some insight into the root cause for your issue and the exact fix you made for this? Any help would be greatly appreciated!

**Comment by ciptoj** [comment]
I've got same issue, any enlightenment how you solve this @vaustral
