### ISSUE TITLE
IdentityServerMiddleware Unhandled exception: auth_time is missing. System.InvalidOperationException: auth_time is missing.

### ISSUE THREAD

**Issue by martindrlik** [IdentityServer/IdentityServer4#2382]
Hello guys, we are using IdentityServer4 version 2.2.0 and at some point (I have no steps to reproduce) we are getting following log entry:

```
IdentityServerMiddleware Unhandled exception: auth_time is missing. System.InvalidOperationException: auth_time is missing.
   at IdentityServer4.Extensions.PrincipalExtensions.GetAuthenticationTimeEpoch(IIdentity identity)
   at IdentityServer4.Services.DefaultClaimsService.GetStandardSubjectClaims(ClaimsPrincipal subject)
   at IdentityServer4.Services.DefaultClaimsService.<GetIdentityTokenClaimsAsync>d__3.MoveNext()
```

I'll improve issue description if needed, but currently I have no more information :-(

**Comment by martindrlik** [comment]
Not an issue. Authentication time was really missing.

**Comment by martindrlik** [comment]
We are still getting `auth_time is missing` critical log entry. It seems only while user is logging in.
Except that critical log entry there seems to be no other issue.

Might be that I missed something but otherwise it looks like we are setting authentication time anywhere relevant.

I did reopen this issue. I still looking for clarification or otherwise to get rid of this issue.

**Comment by brockallen** [comment]
You still have no steps to repro, so there's nothing we can do to investigate.

**Comment by martindrlik** [comment]
Sorry but still no update. We have no steps to reproduce.

**Comment by logcorner** [comment]
Hi, I have the same issue , with identity server version 2.0.0-rc1
![1](https://user-images.githubusercontent.com/5066547/44147483-a2bcab58-a094-11e8-86a5-4bb7ef48e125.png)
![2](https://user-images.githubusercontent.com/5066547/44147484-a2dbc83a-a094-11e8-962f-fcc14a8010f2.png)

**Comment by brockallen** [comment]
@logcorner this might be the issue? https://github.com/IdentityServer/IdentityServer4/issues/2510#issuecomment-411871543

**Comment by logcorner** [comment]
Hi,
I tried this but it does not work.
It works very well if I run it without docker (F5)

But if I run it using docker ( docker-compose ) , I have an exception.

I think I have some configuartion issues
Regards





Le mer. 15 août 2018 à 16:53, Brock Allen <notifications@github.com> a
écrit :

**Comment by SolarMaximus** [comment]
I'm facing this issue when I run IdentityServer site with IISExpress. My client is an angular app with implicit grant flow. First authentication always happens without mistakes. To reproduce it I set small lifetime for id_token and access_token (60s and 180s), login in my application, then close tab with angular app. Then I open my angular app 15-30 mins later and try to login once again and that's how I usually reproduce it.

**Comment by packe100** [comment]
I'm facing the same issue.
