### ISSUE TITLE
Microsoft.IdentityModel is broken for Azure Deployment

### ISSUE THREAD

**Issue by Dark-Bond** [IdentityServer/IdentityServer4#2390]
I have a Cloud Service (Worker Role) that works just great in the development environment using the Cloud emulator.  When I deploy that service to Azure, the call to validate the security token on the server side fails.  It throws several exceptions which the client process.  Digging into the inner exception stack, the first important one is:

`IDX20804: Unable to retrieve document from: '[PII is hidden]'.
`
```
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__23.MoveNext()

```
Digging deeper, we get:

`The type initializer for 'Microsoft.IdentityModel.Protocols.HttpDocumentRetriever' threw an exception.
`
with a stack trace of:

`   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
`

And finally, there's this inner exception:

`Could not load type 'System.FormattableString' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
`
with

```
   at System.Net.Http.HttpMessageHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at System.Net.Http.HttpClient..ctor()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever..cctor()

```
Again, can't stress this enough, works great on the simulator.  Blows up in the cloud.  Did no one consider that we might be using this library in a Cloud Service?

**Comment by leastprivilege** [comment]
Please open an issue with Microsoft.

**Comment by Dark-Bond** [comment]
Who is the party responsible for Microsoft.IdentityModel?

**Comment by brockallen** [comment]
> Microsoft.IdentityModel

https://www.nuget.org/packages/Microsoft.IdentityModel

**Comment by leastprivilege** [comment]
that's the right repo

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
