### ISSUE TITLE
Linux dockerized .netcore 2.0 API tries to contact IdentityServer generating error: System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.at System.Security.Principal.WindowsIdentity.GetCurrent()

### ISSUE THREAD

**Issue by Tigro90** [IdentityServer/IdentityServer4#2464]
### Issue / Steps to reproduce the problem
I have my .netcore WebApi that is accessible only through IdentityServer authentication.
I am trying to dockerize this application in a Linux Container.
The Startup.cs of my API looks like this:

```
        public virtual void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddAuthorization(options =>
            {
                options.AddPolicy("CaseApiPolicy", builder => builder.RequireScope("caseapi"));
            });

            services.AddAuthentication("Bearer").AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Configuration["AuthorityUrl"];
                    options.ApiName = "caseapi";
                    options.LegacyAudienceValidation = true;
                    //options.RequireHttpsMetadata = !_environment.IsDevelopment();
                    options.RequireHttpsMetadata = false;
                }
            );
        }
```

Everything works fine and correctly if I just run the API in a windows environment.
Likewise if I use docker for Windows and I dockerize it in a Linux container (inside a Windows environment.)
As soon as I bring the docker image/container inside a Linux environment it breaks with the error:

```
[19:53:41 INF] Executing action method Friss.CaseApi.Web.Controllers.CaseController.Get (Friss.CaseApi.Web) with arguments (["33185"]) - ModelState is Valid
System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.
   at System.Security.Principal.WindowsIdentity.GetCurrent()
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Friss.CaseApi.Web.DataAccess.Repositories.Cases.FactsCaseRepository.Get(Int64 id)

```

This seems an already existing problem discussed here (https://github.com/dotnet/corefx/issues/7325) since long time but without a solution/explanation. Can anyone please tell me if there is a resolution? Thanks in advance!

**Comment by leastprivilege** [comment]
As you can see from the stack trace - this is coming fro Entity Framework and is completely unrelated to IdentityServer.

Will leave it open for a day - but then close if no-one replies.

**Comment by Tigro90** [comment]
@leastprivilege But if I comment out in the Startup.cs that chunk of code about the initial authorization towards IdentityServer, everything works!

Talking about this part:

```
services.AddAuthentication("Bearer").AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Configuration["AuthorityUrl"];
                    options.ApiName = "caseapi";
                    options.LegacyAudienceValidation = true;
                    //options.RequireHttpsMetadata = !_environment.IsDevelopment();
                    options.RequireHttpsMetadata = false;
                }
            );
```

The way I read it, I can be wrong, and they point it out here (https://github.com/dotnet/corefx/issues/7325) is that the problem is with trying to connect to IdentityServer

**Comment by leastprivilege** [comment]
We are not using Entity Framework. Do you?
