### ISSUE TITLE
PublicOrigin ignored for Discovery?

### ISSUE THREAD

**Issue by i8beef** [IdentityServer/IdentityServer4#2481]
### Issue / Steps to reproduce the problem

I have a project that contains IdentityServer4 as well as a protected API in a single ASP.NET Core project. The whole thing is hosted in a Docker container on port 5000. I have an nginx proxy in front of it that which is forwarding https://MYURL/sub/url to this Docker container. After I authenticate on this URL, and try to use the resulting token, it seems to fail to get the ".well-known/openid-configuration" during the validation (404 in log, see below)

app.UsePathBase(/sub/url) works for the application forwarding all requests to the docker container at the right place.

For IdentityServer4, I have the following:

    var authority = "https://MYURL";
    services.AddIdentityServer(options =>
        {
            options.IssuerUri = authority;
            options.PublicOrigin = authority;
        })

When I hit https://MYURL/sub/url/.well-known/openid-configuration, I get back a document, and all the URLs look correct (i.e., https://MYURL/sub/url prefixes everything).

I also verified that I can hit the full URL and download that document from INSIDE of the container ok.

So it APPEARS that during the validation of the token, when it goes to grab this, it is attempting to grab a different URL (i.e., ignoring PublicOrigin and not building the URL base the same way it does for the openid-configuration doc itself).

### Relevant parts of the log file

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden by default. Set the 'ShowPII' flag in IdentityModelEventSource.cs to true to reveal it.]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by i8beef** [comment]
I can confirm that that PII URL its not showing is the https://MYURL/.well-known/openid-configuration rather than https://MYURL/sub/url/.well-known/openid-configuration when I can see the full log.

Also, Identity Server options for "Authority" is set to "https://MYURL" on the client, and the IssuerUri is also set to that on the server.

**Comment by i8beef** [comment]
I believe I've figured out the issue. Documenting here in case someone else hits it when working with Docker on this:

1. Issuer and Authority MUST match, but do not need to be JUST a HOST address, it can include a full path.
2. Authority is used by the client as the *base address* of the calls it makes for discovery (and possibly others). As such, if you are proxying the app at some subpath like above, the Authority (client) and Issuer (server) should both be set to the *full* path to the root of your server (i.e. above: "http://MYURL/sub/url"). 
3. The "PublicOrigin" on the server is used to build the URLs in the .well-known/openid-configuration endpoint, however, it DOES take into account any configured PathBase (i.e., "app.UsePathBase()"). So if you are using that, as I am because that's how you need to allow a proxy to expose it at a different URL than the host site root, then you actually need to set this to JUST the host portion of the public URL (i.e., "http://MYURL" above. 

I had to segregate the two URLs, using the full public path to the app's root at "Authority" and "Issuer", and just the host portion of that without the relative URL portion for "PublicOrigin".

I do not know if this is necessary when not using app.UsePathBase, but that seemed the .NET Core supported way to allow mvc routes / api redirects, etc., to function when proxied.
