### ISSUE TITLE
Login Page - Http 400 when multiple tabs are open

### ISSUE THREAD

**Issue by prateeknair** [IdentityServer/IdentityServer4#2484]
Getting HTTP 400 when trying to login when I have multiple tabs open.

Steps to reproduce as below:
1. Open "https://demo.identityserver.io/account/login?returnUrl=%2Fgrants" in tab 1.
2. Open "https://demo.identityserver.io/account/login?returnUrl=%2Fgrants" in tab 2.
3. Login on tab 1. This works and the user is redirected.
4. Login on tab 2. Fails - HTTP 400.

While debugging in my code, got the following trace:
`trce: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector[5]
      Performing unprotect operation to key {d688b232-943b-4560-8200-2c9c2b0f78a1} with purposes ('D:\Prateek\Code\Web\IdentityServer\IdentityServer', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'idsrv', 'v2').`

`info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: idsrv was successfully authenticated.`

`info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: idsrv was successfully authenticated.`

`trce: IdentityServer4.Hosting.EndpointRouter[0]
      No endpoint entry found for request path: /account/login`

`dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.`

`dbug: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[2]
      Action 'IdentityServer.AccountController.Login (IdentityServer)' with id 'acf0d7f8-d49b-442e-bfcf-0a1c9b51767e' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint'`

`dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action IdentityServer.AccountController.Login (IdentityServer)`

`dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HLFIBB6KV32T", Request id "0HLFIBB6KV32T:00000008": started reading request body.`

`dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HLFIBB6KV32T", Request id "0HLFIBB6KV32T:00000008": done reading request body.`

`trce: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector[5]
      Performing unprotect operation to key {d688b232-943b-4560-8200-2c9c2b0f78a1} with purposes ('D:\Prateek\Code\Web\IdentityServer\IdentityServer', 'Microsoft.AspNetCore.Antiforgery.AntiforgeryToken.v1').`

`trce: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector[5]
      Performing unprotect operation to key {d688b232-943b-4560-8200-2c9c2b0f78a1} with purposes ('D:\Prateek\Code\Web\IdentityServer\IdentityServer', 'Microsoft.AspNetCore.Antiforgery.AntiforgeryToken.v1').`

`info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The provided antiforgery token was meant for a different claims-based user than the current user.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()`

**Comment by blowdart** [comment]
And it's not a scenario we want to change either, the protections are there for good reasons.

**Comment by brockallen** [comment]
My above comment updated.
