### ISSUE TITLE
DistributedCacheStateDataFormatter tries to unprotect null string

### ISSUE THREAD

**Issue by mantasaudickas** [IdentityServer/IdentityServer4#2504]
We are using IdentityServer4 v2.2.0 with .net core 2.x.
In addition we have enabled distributed SQL server cache, data protection and also AddOidcStateDataFormatterCache:
```
services.AddOidcStateDataFormatterCache(Settings.AzureAdfsProvider);
```

All works fine in load balanced environment. However sometimes we have strange errors like:
```
Connection id "0HLFO8036COUA", Request id "0HLFO8036COUA:00000368": An unhandled exception was thrown by the application.
System.Exception: An error was encountered while handling the remote login. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
  at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
  at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
  at IdentityServer4.Infrastructure.DistributedCacheStateDataFormatter.Unprotect(String protectedText, String purpose)
  at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ReadPropertiesAndClearState(OpenIdConnectMessage message)
  at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

By looking to the code it seems like distributed cache does not return anything:
https://github.com/IdentityServer/IdentityServer4/blob/75b1a660c3cab2580112e6e0288f3f6bed8189f9/src/Infrastructure/DistributedCacheStateDataFormatter.cs#L90

That's why error happens. So now not sure if such case is valid and it is possible that item is not in the cache (so null check is missing in DistributedCacheStateDataFormatter), or we have some issues with our environments and maybe any hints where to start looking?

Any feedback is appreciated.

with best regards
Mantas

**Comment by brockallen** [comment]
Yes, I think this is a bug. It looks like from Microsoft's implementation that the text being passed in is allowed to be null. Fixed on dev.
