### ISSUE TITLE
Error parsing discovery document when using SSL

### ISSUE THREAD

**Issue by ramanathants** [IdentityServer/IdentityServer4#2551]
Hello,

I am running IdentityServer4 and WebApi in the same project.  The site is configured to run using SSL.  I am able to hit the token endpoint successfully and get a token back using the SSL token endpoint.  However when I use the generated token to call my api resource, I am getting an exception in reading discovery document using SSL.
The same thing works when I turn-off SSL and use the normal http.  I have attached the error message below for your reference.  Also I am using .Net Core 2.1 deployed in Ubuntu.  

Help please!!
*********************************************************************************
**An unhandled exception was thrown by the application.
System.InvalidOperationException: Error parsing discovery document from https://{mydomain}/.well-known/openid-configuration: Error connecting to https://{mydomain}/.well-known/openid-configuration: The SSL connection could not be established, see inner exception.
   at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.GetIntrospectionEndpointFromDiscoveryDocument(OAuth2IntrospectionOptions Options) in C:\local\identity\model\AspNetCore.OAuth2Introspection\src\IdentityModel.AspNetCore.OAuth2Introspection\PostConfigureOAuth2IntrospectionOptions.cs:line 62
   at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.InitializeIntrospectionClient(OAuth2IntrospectionOptions Options) in C:\local\identity\model\AspNetCore.OAuth2Introspection\src\IdentityModel.AspNetCore.OAuth2Introspection\PostConfigureOAuth2IntrospectionOptions.cs:line 83
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token) in C:\local\identity\model\AspNetCore.OAuth2Introspection\src\IdentityModel.AspNetCore.OAuth2Introspection\OAuth2IntrospectionHandler.cs:line 142
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.HandleAuthenticateAsync() in C:\local\identity\model\AspNetCore.OAuth2Introspection\src\IdentityModel.AspNetCore.OAuth2Introspection\OAuth2IntrospectionHandler.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync() in C:\local\identity\server4\AccessTokenValidation\src\IdentityServer4.AccessTokenValidation\IdentityServerAuthenticationHandler.cs:line 68
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)**

**Comment by ramanathants** [comment]
@brockallen 

I did not get anything in the inner exception, just the stack trace below.

**Comment by brockallen** [comment]
Then it's hard to say.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
