### ISSUE TITLE
Invalid authorization code error when trying to use Authorization Code and Google Plus

### ISSUE THREAD

**Issue by ArhiChief** [IdentityServer/IdentityServer4#2667]
Hello.

I'm trying to obtain **id** and **access** tokens using IdentityServer and `Authorization Code` grant. For start point I decide to use [Quickstart #4: Adding external Authentication](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/4_ImplicitFlowAuthenticationWithExternal). I modify `Config.cs` `GetClients` in **QuickstartIdentityServer** like this:

```[csharp]
// OpenID Connect implicit flow client (MVC)
new Client
{
    ClientId = "mvc",
    ClientName = "MVC Client",
    AllowedGrantTypes = GrantTypes.CodeAndClientCredentials,

    RedirectUris =
    {
        "http://localhost:5002/signin-oidc",
        "http://localhost:5002"
    },
    PostLogoutRedirectUris =
    {
        "http://localhost:5002/signout-callback-oidc"
    },
    
    ClientSecrets =
    {
        new Secret("secret".Sha256())
    },

    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        "api1"
    },
    AllowAccessTokensViaBrowser = true
}
```
I used **Postman** to test **IdentityServer** like this:

![image](https://user-images.githubusercontent.com/1463326/46343095-f37a0e00-c63c-11e8-9668-ffba9911e48f.png)

It works fine when I use **Local Login**. I mean, **Postman** shows me Login page of IdentityServer and then I put user credentials and press login I get **access** and **id** tokens.

But if I try to login using Google, I get an error. **Postman Console** shows me `invalid_grant` and in logs of my example I get this:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/connect/authorize?response_type=code&state=abc&client_id=mvc&scope=api1%20openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A5002
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
info: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      ValidatedAuthorizeRequest
      {
        "ClientId": "mvc",
        "ClientName": "MVC Client",
        "RedirectUri": "http://localhost:5002",
        "AllowedRedirectUris": [
          "http://localhost:5002/signin-oidc",
          "http://localhost:5002"
        ],
        "SubjectId": "anonymous",
        "ResponseType": "code",
        "ResponseMode": "query",
        "GrantType": "authorization_code",
        "RequestedScopes": "api1 openid profile",
        "State": "abc",
        "Raw": {
          "response_type": "code",
          "state": "abc",
          "client_id": "mvc",
          "scope": "api1 openid profile",
          "redirect_uri": "http://localhost:5002"
        }
      }
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      Showing login: User is not authenticated
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 24.1604ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dcode%26state%3Dabc%26client_id%3Dmvc%26scope%3Dapi1%2520openid%2520profile%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5002
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityServer4.Quickstart.UI.AccountController.Login (QuickstartIdentityServer) with arguments (/connect/authorize/callback?response_type=code&state=abc&client_id=mvc&scope=api1%20openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A5002) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Account/Login.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityServer4.Quickstart.UI.AccountController.Login (QuickstartIdentityServer) in 6.3777ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 14.9031ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/account/ExternalLogin?provider=Google&returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dcode%26state%3Dabc%26client_id%3Dmvc%26scope%3Dapi1%2520openid%2520profile%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5002
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityServer4.Quickstart.UI.AccountController.ExternalLogin (QuickstartIdentityServer) with arguments (Google, /connect/authorize/callback?response_type=code&state=abc&client_id=mvc&scope=api1%20openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A5002) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes (Google).
info: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[12]
      AuthenticationScheme: Google was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityServer4.Quickstart.UI.AccountController.ExternalLogin (QuickstartIdentityServer) in 10.2061ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 17.0712ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/signin-google?state=CfDJ8D18SQlTys9FuXQ2gkLHrQFC6pFw-Hs7gxWXqQCkXU8uQcpelI2glpKjxBB4SSND5P57Itsi2uunsLzAA82T9pMhJ-fbPiEiIkd4CIhU-pfzs0XUF8VYrlM4lDLRaKaS_pF93siHgmfyeOqHvs_Cs7pxTBcr8einu0_hjIdvONyG7ikU6XFXvB5Gd17xOqA93APrEk6LsZXk-IhJI_cKrMPfFBFX1eRIAj_0fQSI22TzAgsTHC3xLpqN5qxs2lh7TtON5w8gjXcWBJYOL00zyx9r1BoQ_t9P1nFuR0tapfq1fhehuYbARBiOkbXKukJYOo7ZiJN_1aXi0SQDsVSRxovw_hnvyXuphpXOwDUbyYh1HefjgVksYSNGq4vZq1uGjfDv7SmuCtrJE6hf6ZptOI9FqZMaaTQIsSLnUbqqlFVJgBuPTUX2SflDWaJppxmojfT14cHkx4xNuEHUFzSNxvs&code=4/bAC1a7zWvGEDa-7ONZPE0136LjxPLw8LYyv5JsV-YOsV9girmQYOP4CnTu0Um6B4ihB02I9LEfaNqt1J6hM5cac&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/plus.me+https://www.googleapis.com/auth/userinfo.profile&authuser=0&session_state=e9342ff00a0022520cf75cc984bf4514836e5bcd..ef0b&prompt=none
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/connect/token application/x-www-form-urlencoded 204
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      Invalid authorization code: 4/bAC1a7zWvGEDa-7ONZPE0136LjxPLw8LYyv5JsV-YOsV9girmQYOP4CnTu0Um6B4ihB02I9LEfaNqt1J6hM5cac
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      {
        "ClientId": "mvc",
        "ClientName": "MVC Client",
        "GrantType": "authorization_code",
        "AuthorizationCode": "4/bAC1a7zWvGEDa-7ONZPE0136LjxPLw8LYyv5JsV-YOsV9girmQYOP4CnTu0Um6B4ihB02I9LEfaNqt1J6hM5cac",
        "Raw": {
          "grant_type": "authorization_code",
          "code": "4/bAC1a7zWvGEDa-7ONZPE0136LjxPLw8LYyv5JsV-YOsV9girmQYOP4CnTu0Um6B4ihB02I9LEfaNqt1J6hM5cac",
          "redirect_uri": "http://localhost:5002",
          "client_id": "mvc",
          "client_secret": "***REDACTED***"
        }
      }
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 46.0099ms 400 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[4]
      Error from RemoteAuthentication: A task was canceled..
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLH8A0UTL1CO", Request id "0HLH8A0UTL1CO:00000004": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.<HandleRequestAsync>d__6.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\FederatedSignOut\AuthenticationRequestHandlerWrapper.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\Hosting\BaseUrlMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 737.4864ms 0
```

If I change `MVC Client` allowed grant types to `Implicit` and use **Postman** with `Implicit` Grant Type everything works well, but I receive **access** token only. 

Is it normal behaviour for IdentityServer? I read documentation about [OpenID Connect Authentication](https://openid.net/specs/openid-connect-core-1_0.html#Authentication) and it seems like that everything should work well because this type of flow is supported by OpenID Connect.

**Comment by brockallen** [comment]
Can you see if our samples work properly? It's difficult when using postman to know if the issue is postman or not.

**Comment by ArhiChief** [comment]
I've tried [ConsoleClientWithBrowser](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src/ConsoleHybridWithPkce) and modify it like this:

```
private static async Task SignIn()
{
    // create a redirect URI using an available port on the loopback address.
    // requires the OP to allow random ports on 127.0.0.1 - otherwise set a static port
    var browser = new SystemBrowser(5002);
    string redirectUri = string.Format($"http://127.0.0.1:{browser.Port}");

    var options = new OidcClientOptions
    {
        Authority = Constants.Authority,
        ClientId = "mvc",
        RedirectUri = redirectUri,
        Scope = "openid profile api1",
        FilterClaims = false,
        Browser = browser,
        ClientSecret = "secret",
        Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode
    };

    var serilog = new LoggerConfiguration()
        .MinimumLevel.Error()
        .Enrich.FromLogContext()
        .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message}{NewLine}{Exception}{NewLine}")
        .CreateLogger();

    options.LoggerFactory.AddSerilog(serilog);

    _oidcClient = new OidcClient(options);
    var result = await _oidcClient.LoginAsync(new LoginRequest());

    ShowResult(result);
    await NextSteps(result);
}
```
And also add `http://127.0.0.1:5002` to the `RedirectUris` of `Clients` in IdentityServer and everything works! When I changed **Callback URL** in **Postman** to `http://127.0.0.1:5002` it's also start working!! I don't know why... Can you explain it to me?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
