### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by KarenTazayan** [IdentityServer/IdentityServer4#2684]
Hello,

I try to validate JWT token with TokenIntrospectionRequest and get the exception mentioned in the title. 

### Issue / Steps to reproduce the problem

[Please see the image for more details](https://1drv.ms/u/s!Al_YQqJFT6HQg0qq5tQPpuyOqHEL)

### Relevant parts of the log file

```
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at IdentityModel.Client.Response..ctor(String raw) in C:\local\identity\model\IdentityModel2\src\Client\Messages\Response.cs:line 22
```

**Comment by brockallen** [comment]
You should capture a http trace of that failing call to better understand what's being returned. Sounds like html, not json.

**Comment by KarenTazayan** [comment]
Thank you for the response. The issue is mine, I forget to put **connect/introspect** after the man URL.
