### ISSUE TITLE
 Duplicate API scopes found. This is an invalid configuration. Use different names for API scopes. Scopes found: read, custom.profile

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#2703]
I have two `scope `s on all my `ApiResource`s (`read`, `custom.profile`)
The api resource scopes must be unique accross all apiresources?!
If `GetAllResourcesAsync()` get apiname as parameter help me to filter scopes to the resource.

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: Duplicate API scopes found. This is an invalid configuration. Use different names for API scopes. Scopes found: read, custom.profile
 at IdentityServer4.Stores.IResourceStoreExtensions.CheckForDuplicates(String[] identityScopeNames, String[] apiScopeNames) in ...\IdentityServer4\src\Extensions\IResourceStoreExtensions.cs:line 85
 at IdentityServer4.Stores.IResourceStoreExtensions.Validate(IEnumerable`1 identity, IEnumerable`1 apiResources) in ...\IdentityServer4\src\Extensions\IResourceStoreExtensions.cs:line 52
   at IdentityServer4.Stores.IResourceStoreExtensions.GetAllEnabledResourcesAsync(IResourceStore store) in ...\IdentityServer4\src\Extensions\IResourceStoreExtensions.cs:line 106
```

**Comment by brockallen** [comment]
>  The api resource scopes must be unique accross all apiresources?!

Yes. How would the token server know which API was being used when requests came in for "read"?

**Comment by mikeandersun** [comment]
What I try to do is a solution that client owners can define own api and api scopes.
So how they can care about duplication one api scopes?

**Comment by leastprivilege** [comment]
prefix them with an "owner id".

**Comment by mikeandersun** [comment]
The owner of api and scopes  is the `client `.
I will try it.
