### ISSUE TITLE
jwks null reference when using net461

### ISSUE THREAD

**Issue by RolandGuijt** [IdentityServer/IdentityServer4#275]
With the provided sample application (minimal config), configured for net461 (quickstart)
When invoking the URL http://localhost:5000/.well-known/openid-configuration/jwks 
A null reference occurs

crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at IdentityServer4.Endpoints.DiscoveryEndpoint.<ExecuteJwksAsync>d__10.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()

**Comment by RolandGuijt** [comment]
Duplicate of #269
