### ISSUE TITLE
EndpointDiscovery Null Reference Exception

### ISSUE THREAD

**Issue by svg3171** [IdentityServer/IdentityServer4#281]
Hello,

I am new to identity server and using IdentityServer4 build version 1.0.0-rc1-build00312. Please help me in resolving the endpoint discovery issue -

IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
         at IdentityServer4.Endpoints.DiscoveryEndpoint.<ExecuteJwksAsync>d__10.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()

Exception is thrown when I try to create TokenClient as below -
var disco = await DiscoveryClient.GetAsync("http://localhost:5000/");
var tokenClient = new TokenClient(disco.TokenEndpoint, "client", "secret");

However when I try following it works fine -
var tokenClient = new TokenClient("http://localhost:5000/connect/token", "password.client", "secret");

**Comment by leastprivilege** [comment]
Update the RC package to update1

**Comment by svg3171** [comment]
Thanks you Dominic!
