### ISSUE TITLE
.NET Core 2.1 Docker: Unable to obtain configuration from: 'https://integrity.identity/.well-known/openid-configuration'.

### ISSUE THREAD

**Issue by KSYMEK** [IdentityServer/IdentityServer4#2857]
Welcome,
It is my first try of using Docker containers to host to services. I have two services: `Integrity-Identity` and `Integrity-API`.

### Issue / Steps to reproduce the problem

`Integrity-Identity` is using the latest version of IdentityServer4. Here is `Integrity-Identity` `Startup.cs` configuration:

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services) {
            services.AddDbContext<IntegrityIdentityContext>(options =>
                options.UseSqlServer(Configuration["connectionString"]));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<IntegrityIdentityContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();

            services.AddIdentityServer(options => {
                    options.IssuerUri = null;
                })
                .AddSigningCredential(Certificate.Certificate.Get())
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddAspNetIdentity<ApplicationUser>()
                .AddCorsPolicyService<InMemoryCorsPolicyService>();

            RegisterEventBus(services);
            services.AddTransient<Seeder>();

            var container = new ContainerBuilder();
            container.Populate(services);

            return new AutofacServiceProvider(container.Build());
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            if (env.IsDevelopment()) {
                app.UseDeveloperExceptionPage();
            }

            app.UseCors(builder => builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod().AllowCredentials());
            app.UseIdentityServer();
            ConfigureEventBus(app);
            app.UseMvcWithDefaultRoute();
        }
```

Here is `Integrity-API` `Startup` class:

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services) {
            services.AddDbContext<IntegrityApiContext>(options =>
                options.UseSqlServer(Configuration["secrets:connectionString"]));

            services.AddMvcCore()
                .AddAuthorization()
                .AddJsonFormatters();

            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Configuration["IdentityUrl"];
                    options.ApiName = "integrity_api";
                    options.RequireHttpsMetadata = false;
                });

            services.AddCors(options => { 
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                        .AllowAnyMethod()
                        .AllowAnyHeader()
                        .AllowCredentials());
            });

            var container = new ContainerBuilder();
            container.Populate(services);

            return new AutofacServiceProvider(container.Build());
        }
```

`docker-compose.override.yml` (I am attaching it but I do not know is this importent for this problem)

```docker
    integrity.identity:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://0.0.0.0:443
        - ASPNETCORE_HTTPS_PORT=443
        - EventBusConnection=rabbitmq
      ports:
        - "5105:443"
      volumes:
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    integrity.api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443
        - ASPNETCORE_HTTPS_PORT=443
        - EventBusConnection=rabbitmq
        - IdentityUrl=https://integrity.identity
        - ApiUrl=https://integrity.api
      ports:
        - "5115:443"
      volumes:
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
```

When I am trying to get resource from controller with `[Authorize]` property and with generated token, `Identity-API` returns this:

### Relevant parts of the log file

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://integrity.identity/.well-known/openid-configuration'.
       at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
       at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
       at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync() in C:\local\identity\server4\AccessTokenValidation\src\IdentityServerAuthenticationHandler.cs:line 61
       at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
       at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
       at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

/.well-known/openid-configuration` opens in browser and certificate/https is correct and working without any warnings. This problem I have also written on [stackoverflow](https://stackoverflow.com/questions/53483600/unable-to-obtain-configuration-from-identityserver4)

**Comment by brockallen** [comment]
That's a DNS issue unrelated to IdentityServer.

**Comment by KSYMEK** [comment]
I found solution for this issue. The problem was caused for self signed local certificate. For local development I only need to change from HTTPS to HTTP. And that was it.

**Comment by sohahm** [comment]
I had similar issue and resolved by using RequireSsl and PublicOrigin in IdentityServerOptions. I have listed relevant links below.

https://leastprivilege.com/2017/10/09/new-in-identityserver4-v2-simplified-configuration-behind-load-balancers-or-reverse-proxies/
https://identityserver.github.io/Documentation/docsv2/advanced/deployment.html
https://identityserver.github.io/Documentation/docsv2/configuration/identityServerOptions.html
http://docs.identityserver.io/en/release/reference/options.html
