### ISSUE TITLE
Unable To Create Migrations Unsupported Pattern

### ISSUE THREAD

**Issue by danwize** [IdentityServer/IdentityServer4#2980]
After upgrading to IdentityServer4 2.3.2 I found that I need to add migrations to update my IdentityServer database.  When I try to create a migration to add the new Identity Server columns, I get this error:

Unable to create an object of type 'PersistedGrantDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

The verbose option tells me:
System.MissingMethodException: No parameterless constructor defined for this object.

### Issue / Steps to reproduce the problem
Run this command:
C:\Users\dan\source\repos\IdentityServer\IdentityServer.Core\WebApi\Authorization.IdentityServer>dotnet ef migrations add IdentityServerVersionUpdate -c PersistedGrantDbContext -o Migrations/IdentityServer/PersistedGrantDb --verbose

### Relevant parts of the log file
Using application service provider from IWebHost accessor on 'Program'.
Finding DbContext classes in the project...
Found DbContext 'PersistedGrantDbContext'.
Found DbContext 'ConfigurationDbContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'PersistedGrantDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 ---> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to create an object of type 'PersistedGrantDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by danwize** [comment]
I found my problem:  This is my SetUpIdentityServerService called by my ConfigureServices method:

private void SetUpIdentityServerService(IServiceCollection services, string connectionString, string migrationsAssembly)
        {
            var idServerService = services.AddIdentityServer()
                .AddSigningCredential(GetSigningCertificate())
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>();
            if (_env.IsDevelopment())
            {
                idServerService
                .AddInMemoryClients(InMemoryConfiguration.Clients(_env))
                .AddInMemoryIdentityResources(InMemoryConfiguration.IdentityResources())
                .AddInMemoryApiResources(InMemoryConfiguration.ApiResources());
            }
            else
            {
                idServerService
                    .AddConfigurationStore(options =>
                    {
                        options.ConfigureDbContext = builder =>
                            builder.UseSqlServer(connectionString,
                                sql => sql.MigrationsAssembly(migrationsAssembly));
                        options.DefaultSchema = IdentityServerDatabaseSchema;
                    })
                    .AddOperationalStore(options =>
                    {
                        options.ConfigureDbContext = builder =>
                            builder.UseSqlServer(connectionString,
                                sql => sql.MigrationsAssembly(migrationsAssembly));
                        options.DefaultSchema = IdentityServerDatabaseSchema;
                    });
            }
        }

I had to comment out the  if(_env.IsDevelopment() ) block.

That got me further, now I'm having build issues.  The build does not like the new PersistedGrantDbContextModelSnapshot that entity framework created.

**Comment by danwize** [comment]
Oops, I had the wrong path when I ran the add-migration command.  It should have been Data/Migrations/IdentityServer/PersistedGrantDb. When I had the wrong path, a new file with

partial class ConfigurationDbContextModelSnapshot was created with caused my conflicts.
