### ISSUE TITLE
Error Update IdentitySErver4 2.2.0 to 2.3.2 what is wrong?

### ISSUE THREAD

**Issue by xiarha** [IdentityServer/IdentityServer4#2986]
2019-01-28 15:52:26.612 +01:00 [WRN] Using an in-memory repository. Keys will not be persisted to storage.
2019-01-28 15:52:26.639 +01:00 [WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2019-01-28 15:52:26.653 +01:00 [WRN] No XML encryptor configured. Key "9e429ae6-13fb-4c42-b815-f433eeeaa24f" may be persisted to storage in unencrypted form.
2019-01-28 15:52:27.206 +01:00 [ERR] Failed executing DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
CREATE TABLE [ApiResources] (
    [Id] int NOT NULL IDENTITY,
    [Description] nvarchar(1000) NULL,
    [DisplayName] nvarchar(200) NULL,
    [Enabled] bit NOT NULL,
    [Name] nvarchar(200) NOT NULL,
    CONSTRAINT [PK_ApiResources] PRIMARY KEY ([Id])
);
System.Data.SqlClient.SqlException (0x80131904): Nel database esiste già un oggetto con il nome 'ApiResources'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:b35364a9-2dbe-47dc-97fc-1bc7eedb3556
Error Number:2714,State:6,Class:16
2019-01-28 15:52:27.236 +01:00 [INF] Starting IdentityServer4 version 2.3.2.0
2019-01-28 15:52:27.260 +01:00 [INF] Using the default authentication scheme KSMWeb for IdentityServer
2019-01-28 15:52:27.260 +01:00 [DBG] Using KSMWeb as default ASP.NET Core scheme for authentication
2019-01-28 15:52:27.260 +01:00 [DBG] Using KSMWeb as default ASP.NET Core scheme for sign-in
2019-01-28 15:52:27.260 +01:00 [DBG] Using KSMWeb as default ASP.NET Core scheme for sign-out
2019-01-28 15:52:27.260 +01:00 [DBG] Using KSMWeb as default ASP.NET Core scheme for challenge
2019-01-28 15:52:27.260 +01:00 [DBG] Using KSMWeb as default ASP.NET Core scheme for forbid
2019-01-28 15:52:27.275 +01:00 [DBG] Starting grant removal
2019-01-28 15:52:27.324 +01:00 [DBG] Login Url: /Account/Login
2019-01-28 15:52:27.326 +01:00 [DBG] Login Return Url Parameter: ReturnUrl
2019-01-28 15:52:27.326 +01:00 [DBG] Logout Url: /Account/Logout
2019-01-28 15:52:27.326 +01:00 [DBG] ConsentUrl Url: /consent
2019-01-28 15:52:27.326 +01:00 [DBG] Consent Return Url Parameter: returnUrl
2019-01-28 15:52:27.326 +01:00 [DBG] Error Url: /home/error
2019-01-28 15:52:27.326 +01:00 [DBG] Error Id Parameter: errorId
2019-01-28 15:52:27.351 +01:00 [DBG] Request path /connect/token matched to endpoint type Token
2019-01-28 15:52:27.361 +01:00 [DBG] Endpoint enabled: Token, successfully created handler: IdentityServer4.Endpoints.TokenEndpoint
2019-01-28 15:52:27.361 +01:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
2019-01-28 15:52:27.369 +01:00 [DBG] Start token request.
2019-01-28 15:52:27.375 +01:00 [DBG] Start client validation
2019-01-28 15:52:27.381 +01:00 [DBG] Start parsing Basic Authentication secret
2019-01-28 15:52:27.381 +01:00 [DBG] Parser found secret: BasicAuthenticationSecretParser
2019-01-28 15:52:27.381 +01:00 [DBG] Secret id found: KSMWeb
2019-01-28 15:52:27.637 +01:00 [DBG] KSMWeb found in database: false
2019-01-28 15:52:27.640 +01:00 [ERR] No client with id 'KSMWeb' found. aborting
2019-01-28 15:52:57.299 +01:00 [INF] Removing 0 grants
2019-01-28 15:53:27.306 +01:00 [INF] Removing 0 grants
2019-01-28 15:53:57.321 +01:00 [INF] Removing 0 grants
2019-01-28 15:54:27.335 +01:00 [INF] Removing 0 grants
2019-01-28 15:54:57.340 +01:00 [INF] Removing 0 grants
2019-01-28 15:55:27.351 +01:00 [INF] Removing 0 grants
2019-01-28 15:55:57.359 +01:00 [INF] Removing 0 grants
2019-01-28 15:56:27.373 +01:00 [INF] Removing 0 grants
2019-01-28 15:56:57.374 +01:00 [INF] Removing 0 grants

**Comment by leastprivilege** [comment]
2019-01-28 15:52:27.637 +01:00 [DBG] KSMWeb found in database: false
2019-01-28 15:52:27.640 +01:00 [ERR] No client with id 'KSMWeb' found. aborting

That looks like it's the problem.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
