### ISSUE TITLE
Unable to host ASP.NET Core as Windows Service

### ISSUE THREAD

**Issue by PingPongSet** [IdentityServer/IdentityServer4#2989]
I have problem setting up the app from the link below as Windows service

https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Quickstarts/2_ResourceOwnerPasswords/src/IdentityServer

Whenever the first request is sent to the Windows Service, it is stopped, and the error is generated:
Error from ResourceOwnerClient:
`Error connecting to http://localhost:1234/.well-known/openid-configuration/jwks: An error occurred while sending the request.`

Event log:
```
Application: IdentityServer.exe
CoreCLR Version: 4.6.27110.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: 'overlapped' has already been freed.
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

```
The code below follows [link](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)

```
public class Program
    {
        public static void Main(string[] args)
        {
            WinServices(args);
        }
        public static void WinServices(string[] args)
        {
            var isService = !(Debugger.IsAttached || args.Contains("--console"));
            var builder = CreateWebHostBuilder(args.Where(arg => arg != "--console").ToArray());


            if (isService)
            {
                var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
                var pathToContentRoot = Path.GetDirectoryName(pathToExe);
                //use a path to the app's published location instead of Directory.GetCurrentDirectory().
                builder.UseContentRoot(pathToContentRoot);
            }

            var host = builder.Build();

            if (isService)
            {
                host.RunAsCustomService();
            }
            else
            {
                host.Run();

            }
        }
        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                    .UseStartup<Startup>()
                    .UseUrls("http://localhost:1234")
                    .UseSerilog((context, configuration) =>
                    {
                        configuration
                            .MinimumLevel.Debug()
                            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                            .MinimumLevel.Override("System", LogEventLevel.Warning)
                            .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
                            .Enrich.FromLogContext()
                            .WriteTo.File(@"C:\Logs\\identityserver_log.txt")
                            .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}", theme: AnsiConsoleTheme.Literate);
                    });
        }

```   
ASP.NET CORE 2.2

Please note that it works when lauched as self-hosted from visual studio.

Added` AddDeveloperSigningCredential() `to below to fix other issue.
 ```
public class Startup
    {
        public IHostingEnvironment Environment { get; }

        public Startup(IHostingEnvironment environment)
        {
            Environment = environment;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            // uncomment, if you wan to add an MVC-based UI
            services.AddMvc().SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Version_2_1);

            var builder = services.AddIdentityServer()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApis())
                .AddInMemoryClients(Config.GetClients())
                .AddTestUsers(Config.GetUsers())
                .AddDeveloperSigningCredential();

            if (Environment.IsDevelopment())
            {
                builder.AddDeveloperSigningCredential();
            }
            else
            {            
                
            }      
        }

        public void Configure(IApplicationBuilder app)
        {
            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // uncomment if you want to support static files
            //app.UseStaticFiles();

            app.UseIdentityServer();           
            // uncomment, if you wan to add an MVC-based UI
            app.UseMvcWithDefaultRoute();
        }
    }
```

**Update:**

**Settings on *.csproj file**

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>
 
```
**Build and Setup script:**
 

      dotnet publish --configuration Release --self-contained -r win-x64 --output C:\myApp
    	
    	
    sc create "SSO" binPath= "c:\myApp\IdentityServer.exe"
    sc start "SSO"
    
    sc stop "SSO"
    sc delete "SSO"

**Update 2**

It turns out that the issue is caused when the Resource Owner Password client sends the request.
It works when Postman is used instead.
https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Quickstarts/2_ResourceOwnerPasswords/src/ResourceOwnerClient

Any idea?

**Comment by brockallen** [comment]
Have you gotten a plain ASP.NET Core App hosted as a windows service? Sounds unrelated to IS.

**Comment by PingPongSet** [comment]
yes, the same code works for other app. it is strange.

**Comment by PingPongSet** [comment]
Please see update 2 on OP

**Comment by brockallen** [comment]
Any update?
