### ISSUE TITLE
 Unable to resolve service for type IClientStore while attempting to activate AuthorizeRequestValidator

### ISSUE THREAD

**Issue by iberodev** [IdentityServer/IdentityServer4#306]
I am trying to have a basic IdentityServer4 (using  with AspNet Identity and EF Core)

This is a quick project I have created to show the issue: 
[https://github.com/iberodev/Iberodevis](https://github.com/iberodev/Iberodevis)

I am not using the IdentityServer4.EntityFramework because I want to have customized entities and mappings, but I am imitating its entity relational model.

This is how I add IdentityServer (although it can be viewed at my repository above)
            
           services.AddIdentityServer(config =>
            {
                //TODO customize Identity Server 4
            })
            .AddInMemoryStores()
            .AddAspNetIdentity<User>();

I have implemented and registered `IClientStore`, `IPersistedGrantStore`, `IScopeStore` and the Identity's `IUserStore<User>` for my User that extends the Identity `IdentityUser<Guid>`

What am I missing? This is the error I get when starting the app:
All the services are configured without error and the middleware plugged into the pipeline without error but my Home and Account Controller never get instantiated.
```
System.InvalidOperationException: Unable to resolve service for type 'IdentityServer4.Stores.IClientStore' while attempting to activate 'IdentityServer4.Validation.AuthorizeRequestValidator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.FederatedSignOutMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

I guess this is related to this:
https://github.com/IdentityServer/IdentityServer4/issues/246

**Comment by brockallen** [comment]
You'd not be using the `InMemoryUserLoginService` on your account controller -- that's only designed to work if you're using `InMemoryUser`s, which you're not.

**Comment by iberodev** [comment]
I am not using `InMemoryUserLoginService`, I am aware it's not to be used when not using in memory stores. 
By mistake I created this issue with that title and edited it later on so maybe you've read that in your notification email. Sorry about that.

This problem is for the error `InvalidOperationException: Unable to resolve service for type 'IdentityServer4.Stores.IClientStore' while attempting to activate 'IdentityServer4.Validation.AuthorizeRequestValidator'.`

**I have now found out that this error happens when I inject the `IIdentityServerInteractionService` into my controller**. I have simplified the scenario to the minimum at [my repo here](https://github.com/iberodev/Iberodevis) with the full description. But basically I have only one controller:

    public class HomeController : Controller
    {
        private readonly IIdentityServerInteractionService _interaction;

        public HomeController(IIdentityServerInteractionService interaction)
        {
            _interaction = interaction;
        }
        
        public IActionResult Index()
        {
            return Json("Hello World");
        }
    }

Four custom services to extend the interfaces that need to be implemented when not using in memory stores:

    public interface IClientService : IClientStore
    {
    }
    public class ClientService : IClientService
    {
        // all IClientStore methods implemented here with a throw new NotImplementedException();
    }
    public interface IGrantService : IPersistedGrantStore
    {
    }
    public class GrantService : IGrantService
    {
        // all IPersistedGrantStore methods here with a throw new NotImplementedException();
    }
    public interface IScopeService : IScopeStore
    {
    }
    public class ScopeService : IScopeService
    {
        // all IScopeStore methods here with a throw new NotImplementedException();
    }
    public interface IUserService : IUserStore<User>
    {
    }
    public class UserService : IUserService 
    {
        // all IUserStore<User> method implemented here with a throw new NotImplementedException();
    }

And then I register the services interfaces and implementations in my DI
 
    // in Startup.cs ConfigureServices section
    services.AddScoped<IUserService, UserService>();
    services.AddScoped<IClientService, ClientService>();
    services.AddScoped<IScopeService, ScopeService>();
    services.AddScoped<IGrantService, GrantService>();

I also configure Identity, IdentityServer and EF and plug its middleware into the pipeline
           
	// Configure services
	// AspNet Core Identity
	services.AddIdentity<User, Role>()
		.AddEntityFrameworkStores<IberodevContext, Guid>()
		.AddDefaultTokenProviders()
		.AddUserStore<UserStore<User, Role, IberodevContext, Guid>>();

	// Identity Server 4.
	services.AddDeveloperIdentityServer()
	.AddInMemoryStores()
	.AddAspNetIdentity<User>();

	//Add EF services
	services.AddDbContext<IberodevContext>(options =>
	{
		options.UseSqlServer(connectionString, 
			sqlServerOptions => sqlServerOptions.MigrationsAssembly(migrationsAssembly));
	});

	// AspNet Core MVC
	services.AddMvc();

and finally pipeline middleware 
          
     app.UseIdentity();
     app.UseIdentityServer();
     app.UseStaticFiles();
     app.UseMvcWithDefaultRoute();

That simple scenario fails complaining about `AuthorizeRequestValidator` which I don't really know what's for.

**Comment by iberodev** [comment]
Also if I replace `services.AddDeveloperIdentityServer()` with `services.AddIdentityServer()` there is an error when plugging identity server middleware and it tells me
`No storage mechanism for grants specified. Use the 'AddInMemoryStores' extension method to register a development version`

but if I add that it also complains about the `Unable to resolve service for type 'IdentityServer4.Stores.IClientStore' while attempting to activate 'IdentityServer4.Validation.AuthorizeRequestValidator'.`

Any advice would be much appreciated!

**Comment by brockallen** [comment]
As we work more on documentation, some of these things will be better explained.

**Comment by D252874** [comment]
i got at the moment kind of the same problem using identityserver 4 quickstart guide with the 3 tutorial page and i don't know where i should add those services it kind of looks the same services
