### ISSUE TITLE
No authentication handler is configured to authenticate for the scheme: Identity.Application

### ISSUE THREAD

**Issue by dknaack** [IdentityServer/IdentityServer4#307]
Ive updated to dotnet core 1.0.1 today and receive now the following exception 

```
System.InvalidOperationException: No authentication handler is configured to authenticate for the scheme: Identity.Application
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<GetAuthenticateInfoAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Extensions.HttpContextExtensions.<GetIdentityServerUserInfoAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Services.Default.DefaultSessionIdService.<GetCurrentSessionIdAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Services.Default.DefaultSessionIdService.<EnsureSessionCookieAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationHandler.<InitAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.SwaggerUi.Application.SwaggerUiMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.SwaggerUi.Application.RedirectMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.Swagger.Application.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.AspNetCore.ScopeValidation.ScopeValidationMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

Any ideas on how to solve this?

**Comment by kdaveid** [comment]
Looks like you are using ASP.NET Identity. Have you added the [AspNetIdentity](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity) package as well? Where is this being thrown, at startup or when you try to log in?

**Comment by dknaack** [comment]
Thanks for your response! Yes i have added aspnet identity using 

```
// enable aspnet identity
services.AddIdentity<ApplicationUser, IdentityRole<long>>()
            .AddEntityFrameworkStores<MyDbContext, long>()
            .AddDefaultTokenProviders();
```

**Comment by kdaveid** [comment]
The second parameter in `services.AddIdentity<,>` takes the AuthenticationScheme (which is "Identity.Application" for ASP.NET Identity). You are (wrongly) overriding the default value with 'IdentityRole<long>'. 

See here the method [declaration](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs#L22) and here the [default value](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs#L19) definition. 

To correct, just wire up the things like this:

```
services.AddIdentity<ApplicationUser, IdentityRole>(
    options =>
    {
        // options
    })
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();
```
and then add IdentityServer like this:
```
// Identity Server
var idsvrBuilder = services.AddIdentityServer(setup =>
{
    // options
})
.AddAspNetIdentity<ApplicationUser>()
.SetSigningCredential(cert)
.AddInMemoryStores()
.AddInMemoryClients(Clients.Get())
.AddInMemoryScopes(Scopes.Get());
```

**Comment by brockallen** [comment]
@dknaack you're saying it was working pre-1.0.1?

**Comment by brockallen** [comment]
Also, can you put in this code in `ConfigureServices` and tell me what `scheme` it reports?

```
services.Configure<IdentityOptions>(options =>
{
    var scheme = options.Cookies.ApplicationCookieAuthenticationScheme;
});

```

**Comment by dknaack** [comment]
@kdaveid 

I don't see any difference besides that i use `long` as the key. 
And i use identity server side by side with my api. 

Here is my setup.

        public void ConfigureServices(IServiceCollection services)
        {
            // configure swagger
            services.ConfigureSwagger();
            // enable authorization
            services.AddAuthorization(options =>
            {
                options.AddPolicy("DevelopersOnly", policy => policy.RequireClaim("Role", "Developer"));
            });
            // set db context
            services.AddDbContext<MyDbContext>(ServiceLifetime.Scoped);
            // enable aspnet identity
            services.AddIdentity<ApplicationUser, IdentityRole<long>>()
                .AddEntityFrameworkStores<MyDbContext, long>()
                .AddDefaultTokenProviders();
            // add mvc
            services.AddMvc();
            // add identity server
            var cert = new X509Certificate2(Path.Combine(environment.ContentRootPath, "idsvr3test.pfx"), "idsrv3test");
            var builder = services.AddIdentityServer()
                .AddAspNetIdentity<ApplicationUser>()
                .SetSigningCredential(cert)
                .AddInMemoryStores()
                .AddInMemoryClients(Clients.Get())
                .AddInMemoryScopes(Scopes.Get());
        }

@brockallen 

Yes, i don't see any difference in my code it just worked on 1.0.0. 
If you interested, i could go back to my last working commit to make it sure. 

If i put your code at the end of my ConfigureServices method. 
`var scheme = options.Cookies.ApplicationCookieAuthenticationScheme;`
does not get called.

**Comment by brockallen** [comment]
Well, then that might explain why you don't have the authenticate scheme. Do you have `app.UseIdentity()` in your `Configure`?

**Comment by dknaack** [comment]
No, i didnt. Now its working as expected.

Ive looked into my older version (1.0.0) and i can confirm that it does not have the 
call for `app.UseIdentity()` too.

**Comment by brockallen** [comment]
> Ive looked into my older version (1.0.0) and i can confirm that it does not have the
call for app.UseIdentity() either.

Odd.

**Comment by Drishy** [comment]
The order is different in 1.1
Just add the configure function code in the following order

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(LogLevel.Debug);
            loggerFactory.AddConsole();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseStaticFiles();
            app.UseIdentity();
            app.UseIdentityServer();
            app.UseMvcWithDefaultRoute();
            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
//Reference   https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-1.1#order
