### ISSUE TITLE
Circular dependency when injecting IClientStore into IEventSink

### ISSUE THREAD

**Issue by sgtfrankieboy** [IdentityServer/IdentityServer4#3156]
### Issue / Steps to reproduce the problem

Create a custom implementation of `IEventSink` and register it in DI. Then inject `IClientStore` into the custom implementation.

I need access to the ClientStore in the EventSink because I need additional client information when the TokenIssuedSuccess event is fired, using:

```
var client = await _clientStore.FindClientByIdAsync(tisEvent.ClientId);
```

### Relevant parts of the log file

```
A circular dependency was detected for the service of type 'IdentityServer4.Stores.IClientStore'.
IdentityServer4.Stores.IClientStore(IdentityServer4.Stores.ValidatingClientStore<IdentityServer4.Stores.InMemoryClientStore>) -> IdentityServer4.Services.IEventService(IdentityServer4.Events.DefaultEventService) -> IdentityServer4.Services.IEventSink(Foo.Is4EventSink) -> IdentityServer4.Stores.IClientStore

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain.CheckCircularDependency(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.TestService(IServiceProvider serviceProvider, Type service, ILogger logger, String message, Boolean doThrow) in C:\local\identity\server4\IdentityServer4\src\Configuration\IdentityServerApplicationBuilderExtensions.cs:line 148
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app) in C:\local\identity\server4\IdentityServer4\src\Configuration\IdentityServerApplicationBuilderExtensions.cs:line 59
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app) in C:\local\identity\server4\IdentityServer4\src\Configuration\IdentityServerApplicationBuilderExtensions.cs:line 29
   at Foo.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in F:\src\Foo\Startup.cs:line 174
```

**Comment by brockallen** [comment]
Yea, there's not much I can do to help you here. You will have to break down your dependency graph to make that work.

**Comment by lwansbrough** [comment]
@brockallen Is it your opinion that `IEventSink` should never access `IClientStore`? Is it unreasonable for `IEventSink.PersistAsync` to need information about a client given `TokenIssuedSuccessEvent.ClientId`? How would you recommend solving this? Is there another way to reliably access the full `Client` instance for a given client ID?

**Comment by brockallen** [comment]
Well, the issue is that it seems the client store has some indirect dependency on the event sink, right?

**Comment by sgtfrankieboy** [comment]
The client store I'm using is the build-in `InMemoryClientStore`. However after looking into source code and StackTrace a bit deeper, what's actually causing the circular dependency is the `ValidatingClientStore<T>` wrapping it, as its using the events to raise one in case of an issue.
