### ISSUE TITLE
Failing at IdentityServer when running XUnit Integration Tests

### ISSUE THREAD

**Issue by ramanathants** [IdentityServer/IdentityServer4#3187]
### Issue / Steps to reproduce the problem
 Upgraded to .Net Core library Microsoft.AspNetCore.All 2.2.4 and IdentityServer4 2.4.0.  When running the Xunit Integration tests with Identity Server, I am getting an error:-
```` 
Message: System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.
````

Though the same tests work fine when I use the previous version Microsoft.AspNetCore.All 2.2.1 

### Relevant parts of the log file

```
   at IdentityServer4.Services.DefaultUserSession.RemoveSessionIdCookieAsync() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Services\Default\DefaultUserSession.cs:line 237
   at IdentityServer4.Services.DefaultUserSession.EnsureSessionIdCookieAsync() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Services\Default\DefaultUserSession.cs:line 227
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 45
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\MtlsTokenEndpointMiddleware.cs:line 60
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

Has anybody came across this issue?  Thanks in Advance!

**Comment by ramanathants** [comment]
Just an update,  I resolved this issue by fixing the order of execution of the Middleware ``app.UseIdentityServer`` within my test. It was earlier injected before ``app.UseAuthentication`` call as I need inject it after, then it resolved my issue.  So this wasn't an version upgrade issue.  Thanks!
