### ISSUE TITLE
IDX20803: Unable to obtain configuration from: '[PII is hidden]

### ISSUE THREAD

**Issue by yujiajunbmj** [IdentityServer/IdentityServer4#3341]
Hi
I encounter a very strange problem. I put identityserver 4 server and client in the same web project. In the LAN environment, they can work normally. When I publish to the external network environment, and configure the verification address to the external network IP address, I can get token normally, but the verification can not pass. The specific error information is as follows. Please help me see this problem, I can't get token. Accurate positioning of this problem

IDX20803: Unable to obtain configuration from: '[PII is hidden]'.
at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Util.Webs.Middlewares.ErrorLogMiddleware.Invoke(HttpContext context)

**Comment by leastprivilege** [comment]
> IDX20803: Unable to obtain configuration from: '[PII is hidden]'.

Typically points at HTTPS configuration problems on the server.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
