### ISSUE TITLE
Invalid Handle Possibly Due to MS IdentityModel v5.5

### ISSUE THREAD

**Issue by MCFHTAGENTS** [IdentityServer/IdentityServer4#3384]
I am observing the following stack trace when I try and validate an authorization token:
```
2019-07-02 10:16:54.052 +01:00 [FTL] Unhandled exception: m_safeCertContext is an invalid handle.
System.Security.Cryptography.CryptographicException: m_safeCertContext is an invalid handle.
   at System.Security.Cryptography.X509Certificates.X509Certificate.ThrowIfInvalid()
   at System.Security.Cryptography.X509Certificates.X509Certificate.GetNotAfter()
   at IdentityServer4.Services.DefaultTokenCreationService.CreateHeaderAsync(Token token)
   at IdentityServer4.Services.DefaultTokenCreationService.CreateTokenAsync(Token token)
   at IdentityServer4.Services.DefaultTokenService.CreateSecurityTokenAsync(Token token)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.CreateAccessTokenAsync(ValidatedTokenRequest request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAuthorizationCodeRequestAsync(TokenRequestValidationResult request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```
I think this is probably with the new MS IdentityModel library.
https://referencesource.microsoft.com/#system/security/system/security/cryptography/x509/x509certificate2.cs,0b24cd2e7cd99b75
However it is possible it is private key related (I do have the PK for this certificate and the webserver should be permissioned to use it)

**Comment by MCFHTAGENTS** [comment]
Ok - worked out what happened here. I had been tidying code and the certificate passed into services.AddIdentityServer.AddSigningCredential was moved inside a using block and hence disposed at the end of ConfigureServices. 
It would have thought that your code should clone that object and manage it itself.

**Comment by Luis-Palacios** [comment]
I fall into the same trap, there was warning about disposable item so I implemented `using` and ran into the same error this issue really help me as I had no idea what was wrong, I believe adding this somewhere in the docs would be a good idea
