### ISSUE TITLE
ID4-preview EF issue.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [IdentityServer/IdentityServer4#3403]
Lib version:
![图片](https://user-images.githubusercontent.com/10345361/60891040-1ce05e00-a28f-11e9-82c8-7032be8c474c.png)

### Question / Steps to reproduce the problem
Use below startup.cs and ef migration command, if access `.well-known/openid-configuration` will throw exception:
```log
Microsoft.Data.SqlClient.SqlException (0x80131904): 无法绑定由多个部分组成的标识符 "a1.Id"。

无法绑定由多个部分组成的标识符 "a1.Id"。

   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()

   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()

   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)

   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)

   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)

   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)

   at System.Data.Common.DbCommand.ExecuteReader()

   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, IDiagnosticsLogger`1 logger)

   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, IDiagnosticsLogger`1 logger)

   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()

   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)

   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)

   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()

   at IdentityServer4.Stores.IResourceStoreExtensions.GetAllEnabledResourcesAsync(IResourceStore store)

   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri)

   at IdentityServer4.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context)

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)

   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

ClientConnectionId:faae4abc-30b8-4c0e-b7c3-a937e04b7f93

Error Number:4104,State:1,Class:16
```

```cmd
dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb
dotnet ef migrations add InitialIdentityServerConfigurationDbMigration -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb
```

Startup.cs:
```C#
public class Startup
{
	public IConfiguration Configuration { get; }

	public Startup(IConfiguration configuration)
	{
		Configuration = configuration;
	}

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddSingleton(Configuration);

		services.AddResponseCompression();
		services.Configure<GzipCompressionProviderOptions>(options =>
		{
			options.Level = CompressionLevel.Optimal;
		});
		//
		string useSql = Configuration.GetConnectionString("UseSql");
		string connection = Configuration.GetConnectionString(useSql);
		//
		var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
		services.AddIdentityServer()
		.AddDeveloperSigningCredential()
		.AddConfigurationStore(options =>
		{
			options.ConfigureDbContext = b => b.UseSqlServer(connection, sql => sql.MigrationsAssembly(migrationsAssembly));
		})
		.AddOperationalStore(options =>
		{
			options.ConfigureDbContext = b => b.UseSqlServer(connection, sql => sql.MigrationsAssembly(migrationsAssembly));
			options.EnableTokenCleanup = true;
		});
	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
		}

		InitializeDatabase(app);

		app.UseIdentityServer();
	}

	private void InitializeDatabase(IApplicationBuilder app)
	{
		using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
		{
			serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();

			var context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
			context.Database.Migrate();
		}
	}
}
```

**Comment by brockallen** [comment]
@javiercn

**Comment by javiercn** [comment]
@brockallen Seems like its failing to connect to the db. 

Not sure exactly what the bits being used are, but from those versions, at least it works for the operational store in the ASP.NET Core E2E tests. (We explicitly run migrations and we run the auth flow).

Not sure what can be happening here. I could take a quick look if there was a repro project available.

**Comment by MiyamuraMiyako** [comment]
@javiercn I pushed project to github: https://github.com/MiyamuraMiyako/SayedAuthService

**Comment by brockallen** [comment]
Any update?

**Comment by MiyamuraMiyako** [comment]
Only simple ID4-preview With EF Storage demo.

**Comment by thederyligh** [comment]
@javiercn:

Note the ```GetAllResourcesAsync()``` method, this method is the one that creates the Sql query through Linq
```        /// <summary>
        /// Gets all resources.
        /// </summary>
        /// <returns></returns>
        public virtual Task<Resources> GetAllResourcesAsync()
        {
            var identity = Context.IdentityResources
              .Include(x => x.UserClaims)
              .Include(x => x.Properties);

            var apis = Context.ApiResources
                .Include(x => x.Secrets)
                .Include(x => x.Scopes)
                    .ThenInclude(s => s.UserClaims)
                .Include(x => x.UserClaims)
                .Include(x => x.Properties)
                .AsNoTracking();

            var result = new Resources(
                identity.ToArray().Select(x => x.ToModel()).AsEnumerable(),
                apis.ToArray().Select(x => x.ToModel()).AsEnumerable());

            Logger.LogDebug("Found {scopes} as all scopes in database", result.IdentityResources.Select(x=>x.Name).Union(result.ApiResources.SelectMany(x=>x.Scopes).Select(x=>x.Name)));

            return Task.FromResult(result);
        }
```
That method executes the following sql query:

```
SELECT
	[a].[Id], 
	[a].[Created], 
	[a].[Description],
	[a].[DisplayName], 
	[a].[Enabled], 
	[a].[LastAccessed], 
	[a].[Name], 
	[a].[NonEditable], 
	[a].[Updated], 
	[a0].[Id], 
	[a0].[ApiResourceId], 
	[a0].[Created], 
	[a0].[Description], 
	[a0].[Expiration], 
	[a0].[Type], 
	[a0].[Value], 
	[a0].[Id], 
	[t].[Id], 
	[t].[ApiResourceId], 
	[t].[Description], 
	[t].[DisplayName], 
	[t].[Emphasize], 
	[t].[Name], 
	[t].[Required], 
	[t].[ShowInDiscoveryDocument], 
	[t].[Id0], 
	[t].[ApiScopeId], 
	[t].[Type], 
	[a1].[Id], <------
	[a3].[Id], 
	[a3].[ApiResourceId], 
	[a3].[Type], 
	[a3].[Id], 
	[a4].[Id], 
	[a4].[ApiResourceId], 
	[a4].[Key], 
	[a4].[Value]
FROM 
	[ApiResources] AS [a]
	LEFT JOIN [ApiSecrets] AS [a0] ON [a].[Id] = [a0].[ApiResourceId]
	LEFT JOIN 
	(
		SELECT
			[a1].[Id], 
			[a1].[ApiResourceId], 
			[a1].[Description], 
			[a1].[DisplayName], 
			[a1].[Emphasize], 
			[a1].[Name], 
			[a1].[Required], 
			[a1].[ShowInDiscoveryDocument], 
			[a2].[Id] AS Id0, 
			[a2].[ApiScopeId], 
			[a2].[Type]
		FROM
			[ApiScopes] AS [a1] <-----
			LEFT JOIN [ApiScopeClaims] AS [a2] ON [a1].[Id] = [a2].[ApiScopeId]
	) AS [t] <----- ON [a].[Id] = [t].[ApiResourceId]
	LEFT JOIN [ApiClaims] AS [a3] ON [a].[Id] = [a3].[ApiResourceId]
	LEFT JOIN [ApiProperties] AS [a4] ON [a].[Id] = [a4].[ApiResourceId]
ORDER BY 
	[a].[Id], 
	[a0].[Id], 
	[a1].[Id], <----
	[a3].[Id]
```
The error refers to the field ```[a1].[Id] ```
could not be bound, if you run the query manually and change the alias to ```[t]. [Id]``` the query is successful

**Comment by thederyligh** [comment]
@javiercn In this other [project ](https://github.com/thederyligh/IDP4)you can see exactly what happens when you try to access to discovery document:

![image](https://user-images.githubusercontent.com/34658596/61177080-85cf1b00-a59a-11e9-8e1f-871788bccc13.png)

**Comment by leastprivilege** [comment]
We will soon have a new version for ASP.NET Core 3. Something might be out of sync.

In the meanwhile you could use one of the SPA templates in ASP.NET Core 3 preview to get a working starting point.
