### ISSUE TITLE
Api Discovery Document: SqlException: The multi-part identifier "a1.Id" could not be bound.

### ISSUE THREAD

**Issue by thederyligh** [IdentityServer/IdentityServer4#3408]
When consulting the discovery API, a query is made to the database that throw an error

### Output
```
IdentityServer4.Hosting.EndpointRouter: Debug: Request path /.well-known/openid-configuration matched to endpoint type Discovery
IdentityServer4.Hosting.EndpointRouter: Debug: Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
IdentityServer4.Hosting.IdentityServerMiddleware: Information: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
IdentityServer4.Endpoints.DiscoveryEndpoint: Debug: Start discovery request
Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.0.0-preview6.19304.10 initialized 'ConfigurationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=Heco.IDP 
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

SELECT
	[a].[Id], 
	[a].[Created], 
	[a].[Description],
	[a].[DisplayName], 
	[a].[Enabled], 
	[a].[LastAccessed], 
	[a].[Name], 
	[a].[NonEditable], 
	[a].[Updated], 
	[a0].[Id], 
	[a0].[ApiResourceId], 
	[a0].[Created], 
	[a0].[Description], 
	[a0].[Expiration], 
	[a0].[Type], 
	[a0].[Value], 
	[a0].[Id], 
	[t].[Id], 
	[t].[ApiResourceId], 
	[t].[Description], 
	[t].[DisplayName], 
	[t].[Emphasize], 
	[t].[Name], 
	[t].[Required], 
	[t].[ShowInDiscoveryDocument], 
	[t].[Id0], 
	[t].[ApiScopeId], 
	[t].[Type], 
	[a1].[Id],
	[a3].[Id], 
	[a3].[ApiResourceId], 
	[a3].[Type], 
	[a3].[Id], 
	[a4].[Id], 
	[a4].[ApiResourceId], 
	[a4].[Key], 
	[a4].[Value]
FROM 
	[ApiResources] AS [a]
	LEFT JOIN [ApiSecrets] AS [a0] ON [a].[Id] = [a0].[ApiResourceId]
	LEFT JOIN 
	(
		SELECT
			[a1].[Id], 
			[a1].[ApiResourceId], 
			[a1].[Description], 
			[a1].[DisplayName], 
			[a1].[Emphasize], 
			[a1].[Name], 
			[a1].[Required], 
			[a1].[ShowInDiscoveryDocument], 
			[a2].[Id] AS Id0, 
			[a2].[ApiScopeId], 
			[a2].[Type]
		FROM
			[ApiScopes] AS [a1]
			LEFT JOIN [ApiScopeClaims] AS [a2] ON [a1].[Id] = [a2].[ApiScopeId]
	) AS [t] ON [a].[Id] = [t].[ApiResourceId]
	LEFT JOIN [ApiClaims] AS [a3] ON [a].[Id] = [a3].[ApiResourceId]
	LEFT JOIN [ApiProperties] AS [a4] ON [a].[Id] = [a4].[ApiResourceId]
ORDER BY 
	[a].[Id], 
	[a0].[Id], 
	[a1].[Id],
	[a3].[Id]
```

### Relevant parts of the log file

```
Microsoft.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "a1.Id" could not be bound.
The multi-part identifier "a1.Id" could not be bound.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()
   at IdentityServer4.Stores.IResourceStoreExtensions.GetAllEnabledResourcesAsync(IResourceStore store)
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:97b73f74-88ab-4de3-bb36-a66aefa3361f
Error Number:4104,State:1,Class:16
```

**Comment by MiyamuraMiyako** [comment]
Also have this issue.

**Comment by thederyligh** [comment]
@MiyamuraMiyako Did you find a solution?

**Comment by brockallen** [comment]
Not enough info.

**Comment by thederyligh** [comment]
@brockallen I will upload the project to github

**Comment by thederyligh** [comment]
Hi @brockallen, here is the project, maybe I can give you more information. [](https://github.com/thederyligh/IDP4)

**Comment by brockallen** [comment]
Sorry, I'm not going to debug your code. I'd ask that you dig a bit more into it and let us know if/why/where we have a bug.

**Comment by MiyamuraMiyako** [comment]
@thederyligh No,still not resolve. I used preview version,may be this is bug.

**Comment by MiyamuraMiyako** [comment]
@brockallen Use preview version ID4 to create simple ef storage sample, bug will display

**Comment by henk787** [comment]
It is related to (caused by) this EF issue: https://github.com/aspnet/EntityFrameworkCore/issues/12251

**Comment by brockallen** [comment]
It's an EF issue. We'll be release soon against their RTM (on the 23rd). Hopefully they have fixed it by then.
