### ISSUE TITLE
HttpResponseExtensions.SetCache Unhandled exception: An item with the same key has already been added.

### ISSUE THREAD

**Issue by dotli** [IdentityServer/IdentityServer4#3457]
```C#
System.ArgumentException: An item with the same key has already been added.
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
    at Microsoft.AspNetCore.Http.HttpResponseExtensions.SetCache(HttpResponse response, Int32 maxAge, String[] varyBy) in IdentityServer4\src\Extensions\HttpResponseExtensions.cs:line 49
    at IdentityServer4.Endpoints.Results.DiscoveryDocumentResult.ExecuteAsync(HttpContext context) in IdentityServer4\src\Endpoints\Results\DiscoveryDocumentResult.cs:line 56
```
#3282

**Comment by brockallen** [comment]
I think this is hitting this line:

```
response.Headers.Add("Vary", vary);
```

Why would there already be a `Vary` header on the response? Any thoughts?

**Comment by brockallen** [comment]
Tracked here: #3879
