### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by baskovli** [IdentityServer/IdentityServer4#3622]
Hello. 
When i am using on start up .AddAspNetIdentity<ApplicationUser>();
I get error.

System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at IdentityServer4.ResponseHandling.UserInfoResponseGenerator.ProcessAsync(UserInfoRequestValidationResult validationResult)
   at IdentityServer4.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context)

There is an authirization bearer but i get 500 error code from url /connect/userinfo

Thank you in advance.

**Comment by baskovli** [comment]
When i am comment out the line 
.AddAspNetIdentity<ApplicationUser>();

There is no problem.
But. When i am trying to refresh token i get error Idp claim is missing...

**Comment by baskovli** [comment]
Found the error. There where multiple sub claims.

**Comment by R4ZuL** [comment]
Hello baskovli,
i am new to the identiy server space and getting the same error as you mentioned. How did you fix the problem?

// Startup.cs
` services.AddIdentityServer()              
                .AddDeveloperSigningCredential()
                .AddInMemoryApiResources(Config.GetApis())
                .AddInMemoryClients(Config.GetClients())
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddAspNetIdentity<UserEntity>();`

// Kestrel console
`dbug: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Scopes in access token: openid email profile coreapi
dbug: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Scopes in access token: openid email profile coreapi
dbug: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Requested claim types: sub email email_verified name family_name given_name middle_name nickname preferred_username profile picture website gender birthdate zoneinfo locale updated_at
dbug: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Scopes in access token: openid email profile coreapi
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__user_Id_0='?' (Size = 255)], CommandType='Text', CommandTimeout='30']
      SELECT `u`.`Id`, `u`.`ClaimType`, `u`.`ClaimValue`, `u`.`UserId`
      FROM `UserClaims` AS `u`
      WHERE (`u`.`UserId` = @__user_Id_0) AND @__user_Id_0 IS NOT NULL
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__userId_0='?' (Size = 255)], CommandType='Text', CommandTimeout='30']
      SELECT `r`.`Name`
      FROM `UserRoles` AS `u`
      INNER JOIN `Roles` AS `r` ON `u`.`RoleId` = `r`.`Id`
      WHERE (`u`.`UserId` = @__userId_0) AND @__userId_0 IS NOT NULL
info: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Profile service returned the following claim types: sub sub given_name family_name email email_verified preferred_username name email email_verified
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: Sequence contains more than one matching element
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at IdentityServer4.ResponseHandling.UserInfoResponseGenerator.ProcessAsync(UserInfoRequestValidationResult validationResult)
   at IdentityServer4.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at IdentityServer4.ResponseHandling.UserInfoResponseGenerator.ProcessAsync(UserInfoRequestValidationResult validationResult)
   at IdentityServer4.Endpoints.UserInfoEndpoint.ProcessUserInfoRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.UserInfoEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`
