### ISSUE TITLE
'Cannot drop the index 'PersistedGrants.IX_PersistedGrants_SubjectId_ClientId_Type', because it does not exist or you do not have permission.'

### ISSUE THREAD

**Issue by daz1761** [IdentityServer/IdentityServer4#3684]
I am trying to follow the Entity Framework tutorial from the docs using .NET Core 2.2 (have not managed to upgrade to 3 just yet).

I have tried with the template (.NET Core 2.1) and started a new project (.NET Core 2.2) and I keep getting the SQL exception on this line of code:

`serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();`

Here is the exception:

```
System.Data.SqlClient.SqlException (0x80131904): Cannot drop the index 'PersistedGrants.IX_PersistedGrants_SubjectId_ClientId_Type', because it does not exist or you do not have permission.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:0b9437d5-97c0-4719-8a07-60e828f69206
Error Number:3701,State:6,Class:11
Exception thrown: 'System.Data.SqlClient.SqlException' in Microsoft.EntityFrameworkCore.Relational.dll
An exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
Cannot drop the index 'PersistedGrants.IX_PersistedGrants_SubjectId_ClientId_Type', because it does not exist or you do not have permission.
```

I've been looking at the migration code in `ConfigurationDB` and `PersistedGrantDB`, in conjunction with other people experiencing similar EF issues, but I can't figure out whats wrong.

**Update**

I have been further investigating the aforementioned code today, and it appears that there is no `migrationBuilder.CreateTable()` for the table `PersistedGrants` in `Data\Migrations\IdentityServer\ConfigurationDb\20190928165028_InitialIdentityServerConfigurationDbMigration.Designer.cs`.  Is this why this is falling over when trying to drop/create indexes? 

It is definitely connecting to my SQL Server Docker Instance as it does create the database and adds the migration table `[dbo].[__EFMigrationsHistory]`, but that is it.

**Update 2**

I think I have fixed the issue..  It appears the `20190928164923_InitialIdentityServerPersistedGrantDbMigration` that is generated is not inline with the Persisted Grant SQL script provided.  I have now changed it to:

```
public partial class InitialIdentityServerPersistedGrantDbMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            //create PersistedGrants table
            migrationBuilder.CreateTable(
                name: "PersistedGrants",
                columns: table => new
                {
                    Key = table.Column<string>(maxLength: 200, nullable: false),
                    Type = table.Column<string>(maxLength: 50, nullable: false),
                    SubjectId = table.Column<string>(maxLength: 200, nullable: true),
                    ClientId = table.Column<string>(maxLength: 200, nullable: false),
                    CreationTime = table.Column<DateTime>(nullable: false),
                    Expiration = table.Column<DateTime>(nullable: true),
                    Data = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PersistedGrants", x => x.Key);
                });

            //create DeviceCodes table
            migrationBuilder.CreateTable(
                name: "DeviceCodes",
                columns: table => new
                {
                    UserCode = table.Column<string>(maxLength: 200, nullable: false),
                    DeviceCode = table.Column<string>(maxLength: 200, nullable: false),
                    SubjectId = table.Column<string>(maxLength: 200, nullable: true),
                    ClientId = table.Column<string>(maxLength: 200, nullable: false),
                    CreationTime = table.Column<DateTime>(nullable: false),
                    Expiration = table.Column<DateTime>(nullable: false),
                    Data = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DeviceCodes", x => x.UserCode);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DeviceCodes_DeviceCode",
                table: "DeviceCodes",
                column: "DeviceCode",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_DeviceCodes_Expiration",
                table: "DeviceCodes",
                column: "Expiration");

            migrationBuilder.CreateIndex(
                name: "IX_PersistedGrants_Expiration",
                table: "PersistedGrants",
                column: "Expiration");

            migrationBuilder.CreateIndex(
                name: "IX_PersistedGrants_SubjectId_ClientId_Type",
                table: "PersistedGrants",
                columns: new[] { "SubjectId", "ClientId", "Type" });

            //migrationBuilder.CreateIndex(
            //    name: "IX_DeviceCodes_UserCode",
            //    table: "DeviceCodes",
            //    column: "UserCode",
            //    unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
               name: "PersistedGrants");

            migrationBuilder.DropTable(
                name: "DeviceCodes");
        }
    }
```

I basically copied the SQL script; however, I have left the index `IX_DeviceCodes_UserCode` commented as its not in the Persisted Grant SQL script, but wasn't sure if it was required.

I would of been happy just using the two SQL scripts in SSMS to create the tables, but I need the migration code to work as I want to be able to create this DB and all it's tables in Postgres.  If this is correct, maybe it should be addressed so a rewrite of the code isn't necessary when running the `ef migration` commands.

**Comment by khertg** [comment]
@daz1761  try this approach.

Delete the migrations of your IdentityServer.
Then run this migration command in order

1.`dotnet ef migrations add InitialIdentityServerConfigurationDbMigration -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb`
2.`dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb`
 
Base on my observation when I had same error, it was because of the order in running the above migration commands.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
