### ISSUE TITLE
Configuring FormOptions results in token endpoint exception

### ISSUE THREAD

**Issue by mtinnes** [IdentityServer/IdentityServer4#3751]
### Issue / Steps to reproduce the problem

Configuring FormOptions in the startup.cs for allowing large file uploads results in the token endpoint failing. The form options we are using are as follows:

```
            services.Configure<FormOptions>(x =>
            {
                x.KeyLengthLimit = int.MaxValue;
                x.ValueLengthLimit = int.MaxValue;
                x.MultipartBodyLengthLimit = int.MaxValue; // In case of multipart
            });
```

### Relevant parts of the log file

```
System.IO.InvalidDataException: Form key length limit 2147483647 or value length limit 2147483647 exceeded.
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ThrowKeyOrValueTooLargeException()
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at IdentityServer4.Validation.PostBodySecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.SecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by leastprivilege** [comment]
We need to have a look.

Why are you changing the form options?

**Comment by mtinnes** [comment]
Changed to allow for uploading large files.

**Comment by leastprivilege** [comment]
To the authentication system? Why?

**Comment by mtinnes** [comment]
The auth is included as a part of a larger app, it's not a separate component.

**Comment by leastprivilege** [comment]
OK - our recommendation is to separate it. For a couple of reasons - the main being re-usability and lowering the attack surface.
