### ISSUE TITLE
HttpContext  is null when calling  _identityServerTools.IssueClientJwtAsync() 

### ISSUE THREAD

**Issue by CyberProgs** [IdentityServer/IdentityServer4#3826]
I am trying to use IdentityServerTools to generate token in MVC project, everything works as expected as long as I am calling the _identityServerTools.IssueClientJwtAsync() inside the controller class, but any time I call this method in any other class (not controller) I get `System.ArgumentNullException` error, the issue related to the `HttpContext context` parameter in GetIdentityServerIssuerUri(HttpContext context), the context is null so there is no way to get the IssuerUri 
the error as the following:
```
System.ArgumentNullException
Value cannot be null. Parameter name: context

System.ArgumentNullException: Value cannot be null.
Parameter name: context
   at IdentityServer4.Extensions.HttpContextExtensions.GetIdentityServerIssuerUri(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Extensions\HttpContextExtensions.cs:line 122
   at IdentityServer4.IdentityServerToolsExtensions.IssueClientJwtAsync(IdentityServerTools tools, String clientId, Int32 lifetime, IEnumerable`1 scopes, IEnumerable`1 audiences) in C:\local\identity\server4\IdentityServer4\src\Extensions\IdentityServerToolsExtensions.cs:line 34
```
I think if we have an overload method of IssueClientJwtAsync() with IssuerUri parameter  so we can generate token in classes without context by passing the IssuerUri  value  might resolve this issue.

**Comment by leastprivilege** [comment]
It feels wrong to "officially" allow issuing tokens with arbitrary issuer names.

If you need that level of flexibility - simply call the `ITokenCreationService` directly.

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/IdentityServerTools.cs#L53-L62
