### ISSUE TITLE
ApiResources properties - same key for one resource

### ISSUE THREAD

**Issue by KacaAvramovic** [IdentityServer/IdentityServer4#3846]
### Issue / Steps to reproduce the problem
- Insert multiple properties for one api resource with same key and different values.
- Restart the server
- Open /.well-known/openid-configuration

Clients support having multiple properties with same key. 
The problem does not occur if the server is already running.

### Relevant parts of the log file

```
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ApiResource -> ApiResource
IdentityServer4.EntityFramework.Entities.ApiResource -> IdentityServer4.Models.ApiResource

Type Map configuration:
ApiResource -> ApiResource
IdentityServer4.EntityFramework.Entities.ApiResource -> IdentityServer4.Models.ApiResource

Destination Member:
Properties

 ---> System.ArgumentException: An item with the same key has already been added. Key: Team
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(KeyValuePair`2 keyValuePair)
   at lambda_method(Closure , ApiResource , ApiResource , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , ApiResource , ApiResource , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at IdentityServer4.EntityFramework.Mappers.ApiResourceMappers.ToModel(ApiResource entity)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.<>c.<GetAllResourcesAsync>b__6_8(ApiResource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at IdentityServer4.Models.Resources..ctor(IEnumerable`1 identityResources, IEnumerable`1 apiResources)
   at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResourcesAsync()
   at IdentityServer4.Stores.CachingResourceStore`1.<GetAllResourcesAsync>b__10_0()
   at IdentityServer4.Extensions.ICacheExtensions.GetAsync[T](ICache`1 cache, String key, TimeSpan duration, Func`1 get, ILogger logger)
   at IdentityServer4.Stores.CachingResourceStore`1.GetAllResourcesAsync()
   at IdentityServer4.Stores.IResourceStoreExtensions.GetAllEnabledResourcesAsync(IResourceStore store)
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.CreateDiscoveryDocumentAsync(String baseUrl, String issuerUri)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

**Comment by leastprivilege** [comment]
Not sure I follow - both are dictionaries, so keys must be unique

https://github.com/IdentityServer/IdentityServer4/blob/master/src/Storage/src/Models/Resource.cs#L49
and
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Storage/src/Models/Client.cs#L304

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
