### ISSUE TITLE
Uncaught exceptions thrown from DistributedDeviceFlowThrottlingService due to creating cache options that have already expired

### ISSUE THREAD

**Issue by chrisvanderpennen** [IdentityServer/IdentityServer4#3860]
### Issue / Steps to reproduce the problem
We are occasionally seeing `DistributedDeviceFlowThrottlingService` throw uncaught exceptions, due to assigning `DistributedCacheEntryOptions.AbsoluteExpiration` a value that ends up being in the past when it reaches the cache.  This is checked in both the official [Redis](https://github.com/aspnet/Extensions/blob/v2.1.14/src/Caching/Redis/src/RedisCache.cs#L400) and [SQL Server](https://github.com/aspnet/Extensions/blob/v2.1.14/src/Caching/SqlServer/src/DatabaseOperations.cs#L347) distributed cache implementations, but does not appear to be checked in the in-memory "distributed" cache.

I believe this is caused by order of [these two checks](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Validation/Default/DeviceCodeValidator.cs#L73-L86) in `DeviceCodeValidator`, which appears to allow for the throttling service to be queried about an expired code.  Moving the code expiry check in front of the throttle check should resolve the issue.

### Relevant parts of the log file

```
System.ArgumentOutOfRangeException: The absolute expiration value must be in the future.
Parameter name: AbsoluteExpiration
Actual value was 11/27/2019 02:28:39 +00:00.
   at Microsoft.Extensions.Caching.Redis.RedisCache.GetAbsoluteExpiration(DateTimeOffset creationTime, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.Redis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)
   at IdentityServer4.Services.DistributedDeviceFlowThrottlingService.ShouldSlowDown(String deviceCode, DeviceCode details)
   at IdentityServer4.Validation.DeviceCodeValidator.ValidateAsync(DeviceCodeValidationContext context)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateDeviceCodeRequestAsync(NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters)
   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

**Comment by scottbrady91** [comment]
That's definitely exceptional behavior.

Good idea about swapping the checks, but it looks like there will still be a race condition, albeit a small one. Perhaps a better approach would be to change the [cache expiration](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Services/Default/DistributedDeviceFlowThrottlingService.cs#L54)?

I'm thinking we should change the absolute expiration to be the current time + device code lifetime.

It means that items in the cache are for a bit longer than necessary, but I don't see that being a big issue. What do you think?

**Comment by chrisvanderpennen** [comment]
Good point about there still being a small race.  How about a sliding expiration of say `_options.DeviceFlow.Interval * 5` seconds, with no absolute expiration?  That combined with the check swap should ensure the cache entry is expired shortly after either the token expires or the device is authenticated.

**Comment by brockallen** [comment]
Status on this @scottbrady91?

**Comment by brockallen** [comment]
PR merged. Thanks
