### ISSUE TITLE
DefaultGrantStore.GetItemAsync NullReferenceException when refresh token no longer exists in store

### ISSUE THREAD

**Issue by TechLiam** [IdentityServer/IdentityServer4#4133]
### Issue
When validating a refresh token that no longer exists in the store GetItemAsync throws a null reference exception this courses the exception bubble all the way through the code coursing error logs to be written by my web application.

The application is using Redis to store tokens.

### Steps to reproduce the problem
- Get a refresh token
- Find the refresh token in the data store (e.g. Redis key)
- Delete the refresh token from the store
- Make a request that processes the token this courses the exception to be thrown

### Relevant parts of the log file
![image](https://user-images.githubusercontent.com/5720952/75674049-313cf500-5c7c-11ea-9294-081c253cdc86.png)
Sorry I don't have true logs for this

**Comment by brockallen** [comment]
I don't see this in either our in-memory or EF grant store implementations. I don't have a redis setup, so you will need to debug into that to see if it's a redis problem, please.

**Comment by TechLiam** [comment]
Sorry about the slow response to this I have tried to think of ways I could debug the Redis cache but there not really anyway I can do that.

I got a better stack trace for this issue today
``
System.NullReferenceException: Object reference not set to an instance of an object.

   at IdentityServer4.Stores.DefaultGrantStore`1.GetItemAsync(String key) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Stores\Default\DefaultGrantStore.cs:line 89

   at IdentityServer4.Validation.TokenValidator.ValidateRefreshTokenAsync(String tokenHandle, Client client) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Validation\Default\TokenValidator.cs:line 379

   at IdentityServer4.Validation.TokenRequestValidator.ValidateRefreshTokenRequestAsync(NameValueCollection parameters) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Validation\Default\TokenRequestValidator.cs:line 490

   at IdentityServer4.Validation.TokenRequestValidator.RunValidationAsync(Func`2 validationFunc, NameValueCollection parameters) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Validation\Default\TokenRequestValidator.cs:line 151

   at IdentityServer4.Validation.TokenRequestValidator.ValidateRequestAsync(NameValueCollection parameters, ClientSecretValidationResult clientValidationResult) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Validation\Default\TokenRequestValidator.cs:line 140

   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Endpoints\TokenEndpoint.cs:line 88

   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Endpoints\TokenEndpoint.cs:line 70

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 54

   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 69

   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\MtlsTokenEndpointMiddleware.cs:line 60

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36

   at {*Company Name*}.IdP.Infrastructure.Saml.SamlApplicationBuilderExtensions.<>c.<<UseSamlWithCustomizations>b__0_4>d.MoveNext() in C:\...\{*Company Name*}.IdP\{*Company Name*}.IdP\Infrastructure\Saml\SamlApplicationBuilderExtensions.cs:line 100

``
Not sure if that will help you but worth you seeing.

Also this is the setup for the .Net Core Service for Identity Server
```
var applicationConnectionString = Configuration.GetConnectionString("ApplicationConnection");
            var migrationsAssemblyName = Assembly.GetExecutingAssembly().GetName().Name;

            if (Environment.IsDevelopment())
            {
                IdentityModelEventSource.ShowPII = true;
            }

            AddCustomServices(services);

            services.AddIdentityServer(Configuration, options =>
                {
                    options.UserInteraction.LoginUrl = "/Account/Login";
                    options.UserInteraction.LogoutUrl = "/Account/Logout";
                    options.UserInteraction.ErrorUrl = "/IdentityServerError";
                    options.Caching.ClientStoreExpiration = TimeSpan.FromMinutes(1);
                    options.Caching.ResourceStoreExpiration = TimeSpan.FromMinutes(1);
                    options.Caching.CorsExpiration = TimeSpan.FromMinutes(1);
                })
                .AddRedirectUriValidator<StrictIgnoreQueryStringRedirectUriValidator>()
                .AddAspNetIdentity<User>()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder => builder.UseSqlServer(
                        applicationConnectionString,
                        sql => sql.MigrationsAssembly(migrationsAssemblyName)
                    );
                })
                .AddInMemoryCaching()
                .AddClientStoreCacheWithDynamicTenantUris<ClientStore>()
                .AddResourceStoreCache<ResourceStore>()
                .AddCorsPolicyCache<CorsPolicyService>()
                .AddSigningCredentialStoreCache<DatabaseSigningCredentialStore>()
                .AddValidationKeysStoreCache<DatabaseValidationKeysStore>();

            services.AddSingleton<IPostConfigureOptions<SamlAuthenticationOptions>, SamlPartnerPostConfigureOptions>();
            services.AddSamlServices();
```

And this is the setup of the distributed cache which we set to be Redis and then for easy of reproducing the issue manually delete the keys from Reids when a brake point is hit in our application that is authenticating with the IdP.

```
var distributedCacheProviderConfig = Configuration.GetSection("Caching:DistributedCacheProvider");
            if (!distributedCacheProviderConfig.Exists())
            {
                return;
            }

            var providerName = distributedCacheProviderConfig["Name"];

            if ("InMemory".Equals(providerName, StringComparison.OrdinalIgnoreCase))
            {
                services.AddDistributedMemoryCache();
            }
            else if ("Redis".Equals(providerName, StringComparison.OrdinalIgnoreCase))
            {
                var providerOptions = distributedCacheProviderConfig.GetSection("Options");
                if (!providerOptions.Exists())
                {
                    throw new InvalidOperationException($"Options for distributed cache provider '{providerName}' not found.");
                }

                var providerConnectionStringName = providerOptions["ConnectionStringName"];
                var providerConnectionString = Configuration.GetConnectionString(providerConnectionStringName);
                if (string.IsNullOrWhiteSpace(providerConnectionString))
                {
                    throw new InvalidOperationException($"Connection string for distributed cache provider '{providerName}' not configured or connection string with name '{providerConnectionStringName ?? "null"}' not found.");
                }

                services.AddDistributedRedisCache(o =>
                {
                    o.Configuration = providerConnectionString;
                });
            }
            else
            {
                throw new NotSupportedException($"Distributed cache provider '{providerName ?? "null"}' not supported.");
            }

            services.AddTransient<IPersistedGrantStore, PersistedGrantStore>();
```

Hopefully that gives a bit more context.

I have not tried with the InMemory cache but I guess you could probably clear that at the same point we clear the Redis one using some cleaver extra call to the IdP from the client

**Comment by dplarina** [comment]
I was having this exact issue while implementing my own PersistedGrantStore. Took me cloning the repo and debugging this myself to figure out what was going on.

Basically I was returning null from the method with the following signature in my PersistedGrantStore.
`public Task<PersistedGrant> GetAsync(string key)`
Returning null is perfectly valid as long as the method is marked async as that will return a Task with a null value.

Without async this line in DefaultGrantStore gets a null back from Store.GetAsync and the await throws an NRE. 
`var grant = await Store.GetAsync(hashedKey);`
Since you cannot await null, it's expecting a Task.

When I changed the method to:
`public async Task<PersistedGrant> GetAsync(string key)`
Everything started working correctly for me as it will now return a Task with a null value.

HTH

**Comment by brockallen** [comment]
I've not had a chance to try to repro, but could this be the issue @TechLiam?

**Comment by TechLiam** [comment]
That is interesting this is what we have for the GetAsync method

``` csharp
public Task<PersistedGrant> GetAsync(string value)
        {
            string key = GetKey(value);
            string serializedGrant = distributedCache.GetString(key);

            if (!string.IsNullOrEmpty(serializedGrant))
            {
                var grant = JsonConvert.DeserializeObject<PersistedGrant>(serializedGrant);

                if (grant.Expiration < DateTime.UtcNow)
                {
                    RemoveAsync(key);
                    logger.LogWarning($"Grant with key {key} expired and was deleted");
                    return Task.FromResult((PersistedGrant)null);
                }
                return Task.FromResult(JsonConvert.DeserializeObject<PersistedGrant>(serializedGrant));
            }

            logger.LogDebug($"No grant found with key {key}");
            return Task.FromResult((PersistedGrant)null);
        }
```
Is there anything wrong about this? I think we have done what @dplarina suggested

And for clarity here the whole class
``` csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IdentityServer4.Models;
using IdentityServer4.Stores;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Pierbridge.IdP.Data;

namespace Pierbridge.IdP.Infrastructure.IdentityServer
{
    public class PersistedGrantStore : IPersistedGrantStore
    {
        private readonly IDistributedCache distributedCache;
        private readonly IApplicationDbContext applicationDbContext;
        private readonly ILogger<IPersistedGrantStore> logger;

        public static string GetKey(string key) => $"{Constants.DistributedCacheKeyPrefix}:{key}";

        public static string GetSubjectKey(PersistedGrant grant) => GetSubjectKey(grant.SubjectId);

        private static string GetSubjectKey(string subjectId) => $"{Constants.DistributedCacheKeyPrefix}:{subjectId}";

        private static string GetClientKey(string subjectId, string clientId) => $"{Constants.DistributedCacheKeyPrefix}:{subjectId}:{clientId}";

        public static string GetClientKey(PersistedGrant grant) => GetClientKey(grant.SubjectId, grant.ClientId);

        private static string GetTypeKey(string subjectId, string clientId, string type) => $"{Constants.DistributedCacheKeyPrefix}:{subjectId}:{clientId}:{type}";

        public static string GetTypeKey(PersistedGrant grant) => GetTypeKey(grant.SubjectId, grant.ClientId, grant.Type);

        public PersistedGrantStore(IDistributedCache distributedCache,
            IApplicationDbContext applicationDbContext,
            ILogger<IPersistedGrantStore> logger)
        {
            this.distributedCache = distributedCache;
            this.applicationDbContext = applicationDbContext;
            this.logger = logger;
        }

        public Task StoreAsync(PersistedGrant grant)
        {
            if (grant == null)
            {
                throw new ArgumentNullException(nameof(grant));
            }

            try
            {
                string key = GetKey(grant.Key);
                var options = new DistributedCacheEntryOptions
                {
                      AbsoluteExpiration = grant.Expiration
                };

                if (!string.IsNullOrEmpty(grant.SubjectId))
                {
                    using (var transactionScope = applicationDbContext.BeginTransactionScope())
                    {
                        distributedCache.SetString(key, JsonConvert.SerializeObject(grant), options);
                        AddGrantToMap(grant.Key, GetSubjectKey(grant));
                        AddGrantToMap(grant.Key, GetClientKey(grant));
                        AddGrantToMap(grant.Key, GetTypeKey(grant), options);
                        transactionScope.Complete();
                    }
                }
                else
                {
                    distributedCache.SetString(key, JsonConvert.SerializeObject(grant), options);
                }
                return Task.FromResult(0);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error while storing new grant");
                throw;
            }
        }

        public Task<PersistedGrant> GetAsync(string value)
        {
            string key = GetKey(value);
            string serializedGrant = distributedCache.GetString(key);

            if (!string.IsNullOrEmpty(serializedGrant))
            {
                var grant = JsonConvert.DeserializeObject<PersistedGrant>(serializedGrant);

                if (grant.Expiration < DateTime.UtcNow)
                {
                    RemoveAsync(key);
                    logger.LogWarning($"Grant with key {key} expired and was deleted");
                    return Task.FromResult((PersistedGrant)null);
                }
                return Task.FromResult(JsonConvert.DeserializeObject<PersistedGrant>(serializedGrant));
            }

            logger.LogDebug($"No grant found with key {key}");
            return Task.FromResult((PersistedGrant)null);
        }

        public Task<IEnumerable<PersistedGrant>> GetAllAsync(string subjectId)
        {
            string subjectKey = GetSubjectKey(subjectId);
            string serializedSubjectMap = distributedCache.GetString(subjectKey);

            if (!string.IsNullOrEmpty(serializedSubjectMap))
            {
                var subjectMap = JsonConvert.DeserializeObject<List<string>>(serializedSubjectMap);
                var grants = new List<PersistedGrant>();

                foreach (string key in subjectMap)
                {
                    string grantKey = GetKey(key);
                    string serializedGrant = distributedCache.GetString(grantKey);

                    if (!string.IsNullOrEmpty(serializedGrant))
                    {
                        var grant = JsonConvert.DeserializeObject<PersistedGrant>(serializedGrant);

                        if (grant.Expiration < DateTime.UtcNow)
                        {
                            RemoveAsync(grantKey);
                            logger.LogWarning($"Grant with key {key} expired and was deleted");
                        }
                        else
                        {
                            grants.Add(grant);
                        }
                    }
                    else
                    {
                        logger.LogWarning($"No grant found with subjectId {subjectId} and key {grantKey}");
                    }
                }
                return Task.FromResult(grants.AsEnumerable());
            }

            logger.LogDebug($"No grant found with subjectId {subjectId}");
            return Task.FromResult((IEnumerable<PersistedGrant>)null);
        }

        public Task RemoveAsync(string value)
        {
            try
            {
                string key = GetKey(value);
                string serializedGrant = distributedCache.GetString(key);

                if (serializedGrant == null)
                {
                    logger.LogError($"No grant found with key {key}");
                    return Task.CompletedTask;
                }

                var grant = JsonConvert.DeserializeObject<PersistedGrant>(serializedGrant);

                if (!string.IsNullOrEmpty(grant.SubjectId))
                {
                    var options = new DistributedCacheEntryOptions { AbsoluteExpiration = grant.Expiration };

                    using (var transactionScope = applicationDbContext.BeginTransactionScope())
                    {
                        distributedCache.Remove(GetKey(grant.Key));
                        RemoveGrantFromMap(grant.Key, GetSubjectKey(grant));
                        RemoveGrantFromMap(grant.Key, GetClientKey(grant));
                        RemoveGrantFromMap(grant.Key, GetTypeKey(grant), options);
                        transactionScope.Complete();
                    }
                }
                else
                {
                    distributedCache.Remove(grant.Key);
                }
                return Task.CompletedTask;
            }
            catch (Exception e)
            {
                logger.LogError(e, $"Error while removing grant with key {value}");
                throw;
            }
        }

        public Task RemoveAllAsync(string subjectId, string clientId)
        {
            string clientKey = GetClientKey(subjectId, clientId);
            string serializedMap = distributedCache.GetString(clientKey);

            if (!string.IsNullOrEmpty(serializedMap))
            {
                var map = JsonConvert.DeserializeObject<List<string>>(serializedMap);

                foreach (string grantKey in map)
                {
                    RemoveAsync(grantKey);
                }
                return Task.CompletedTask;
            }

            logger.LogError($"No grant found with subjectId {subjectId} and clientId {clientId}");
            return Task.CompletedTask;
        }

        public Task RemoveAllAsync(string subjectId, string clientId, string type)
        {
            string key = GetTypeKey(subjectId, clientId, type);
            string serializedMap = distributedCache.GetString(key);

            if (!string.IsNullOrEmpty(serializedMap))
            {
                var map = JsonConvert.DeserializeObject<List<string>>(serializedMap);

                foreach (string grantKey in map)
                {
                    RemoveAsync(grantKey);
                }
                return Task.CompletedTask;
            }

            logger.LogError($"No grant found with subjectId {subjectId}, clientId {clientId} and type {type}");
            return Task.CompletedTask;
        }

        private void AddGrantToMap(string grantKey, string mapKey)
        {
            AddGrantToMap(grantKey, mapKey, null);
        }

        private void AddGrantToMap(string grantKey, string mapKey, DistributedCacheEntryOptions options)
        {
            string serializedMap = distributedCache.GetString(mapKey);
            List<string> map;

            if (!string.IsNullOrEmpty(serializedMap))
            {
                map = JsonConvert.DeserializeObject<List<string>>(serializedMap);

                if (!map.Contains(grantKey))
                {
                    map.Add(grantKey);
                }
            }
            else
            {
                map = new List<string> { grantKey };                
            }

            var data = JsonConvert.SerializeObject(map);

            if (options != null)
            {
                RemoveExpiredGrants(map);
                distributedCache.SetString(mapKey, data, options);
            }
            else
            {
                distributedCache.SetString(mapKey, data);
            }
        }

        private void RemoveExpiredGrants(List<string> map)
        {
            for (int i=map.Count-1; i>=0; --i)
            {
                PersistedGrant grant = GetAsync(map[i]).Result;

                if (grant == null || grant.Expiration < DateTime.UtcNow)
                {
                    map.RemoveAt(i);
                }
            }
        }

        private void RemoveGrantFromMap(string grantKey, string mapKey)
        {
            RemoveGrantFromMap(grantKey, mapKey, null);
        }

        private void RemoveGrantFromMap(string grantKey, string mapKey, DistributedCacheEntryOptions options)
        {
            string serializedMap = distributedCache.GetString(mapKey);

            if (string.IsNullOrEmpty(serializedMap))
            {
                logger.LogWarning($"No value found with key {mapKey}");
                return;
            }

            var map = JsonConvert.DeserializeObject<List<string>>(serializedMap);

            if (map.Contains(grantKey))
            {
                map.Remove(grantKey);

                if (map.Count == 0)
                {
                    distributedCache.Remove(mapKey);
                }
                else
                {
                    if (options != null)
                    {
                        RemoveExpiredGrants(map);
                        distributedCache.SetString(mapKey, JsonConvert.SerializeObject(map), options);
                    }
                    else
                    {
                        distributedCache.SetString(mapKey, JsonConvert.SerializeObject(map));
                    }
                }
            }
        }
    }
}
```

**Comment by brockallen** [comment]
I don't know where this stands. Form what I can tell, there's no update to IdentityServer, so I'll close unless we get something more concrete to fix.
