### ISSUE TITLE
Issuer name is missing

### ISSUE THREAD

**Issue by mihaimyh** [IdentityServer/IdentityServer4#4161]
I am trying to secure an API but I see the following entries in API's logs and I do not know how to handle this or what is it referring to:

```
[09:15:03 Information] IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
AuthenticationScheme: Bearer was challenged.

[20:07:32 Error] IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
Policy error while contacting the discovery endpoint https://idp.example.com: Issuer name is missing
System.InvalidOperationException: Policy error while contacting the discovery endpoint https://idp.example.com: Issuer name is missing
   at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.GetIntrospectionEndpointFromDiscoveryDocument(OAuth2IntrospectionOptions options)
   at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.InitializeIntrospectionClient(OAuth2IntrospectionOptions options)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()

[20:07:32 Information] IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
Bearer was not authenticated. Failure message: Policy error while contacting the discovery endpoint https://idp.example.com: Issuer name is missing

[20:07:32 Information] IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler
AuthenticationScheme: BearerIdentityServerAuthenticationIntrospection was challenged.

[20:07:32 Information] IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
AuthenticationScheme: Bearer was challenged.
```

**Comment by brockallen** [comment]
Is `https://idp.example.com` really the authority you've configured?

**Comment by mihaimyh** [comment]
> Is `https://idp.example.com` really the authority you've configured?

Here I've just masked the real URL with `example.com`, but yes, the authority it is configured properly.

**Comment by brockallen** [comment]
Well, the error is pretty much clear: it can't connect to `https://idp.example.com/.well-known/openid-configuration`. Do you know why?

**Comment by mihaimyh** [comment]
@brockallen Thank you, it seems there was a miss-configuration in resolving IP address of idp.example.com.
