### ISSUE TITLE
Size of data columns exceeds maximum allowed size for SQL Server columns

### ISSUE THREAD

**Issue by nmehlei** [IdentityServer/IdentityServer4#4189]
### Issue / Steps to reproduce the problem
The example projects and documentation use mostly SQLite when using Entity Framework. When one switches that to an SQL database (or rather two, since there are two contexts) then the EF migration for the PersistedGrant DB fails with the error message "The size (50000) given to the column 'Data' exceeds the maximum allowed for any data type (8000)". This can potentially be fixed with switching to nvarchar(max) instead of nvarchar(50000), but this should then (if it actually works, didn't test it yet) probably be fixed in the example project and noted in the documentation. Is there any official guidance for this?

### Relevant parts of the log file
During execution of the is4ef example project (with small changes for switching SQLite to SQL Server) invoked with the /seed command line argument.
```
Seeding database...

[23:53:01 Fatal]
Host terminated unexpectedly.
Microsoft.Data.SqlClient.SqlException (0x80131904): The size (50000) given to the column 'Data' exceeds the maximum allowed for any data type (8000).
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
[shortened]
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at NAble_Identity.SeedData.EnsureSeedData(String configurationConnectionString, String operationalConnectionString) in C:\Users\NMehl\Source\Repos\NAble-Identity\NAble-Identity\SeedData.cs:line 36
   at NAble_Identity.Program.Main(String[] args) in C:\Users\NMehl\Source\Repos\NAble-Identity\NAble-Identity\Program.cs:line 54
```

**Comment by nmehlei** [comment]
Well, crap, my mistake. Seems like I tried to re-use the migrations that came with the example project, which are specific to SQLite. After deleting these and re-creating new migrations everything works.
