### ISSUE TITLE
Token endpoint accepts multipart/form content type

### ISSUE THREAD

**Issue by bderveni** [IdentityServer/IdentityServer4#4340]
### Issue / Steps to reproduce the problem
Use the following curl request against the token endpoint of a running instance of IdentityServer4 v 3.1.2:

```bash
curl -F "grant=1" -F "grant=2" https://identityserveruri/connect/token
```

The response will be:

400 Bad Request
```json
{"error":"invalid_client"}
```

According to OpenID Connect Core spec, section [3.1.3.1](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.3.1), this endpoint should be called via a POST and Form Serialization as described in section [13.2](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.13.2):
| "... using the **application/x-www-form-urlencoded** format..."

Based on this the response should have been:
400 Bad Request
```json
{"error":"invalid_request"}
```
If my understanding of the protocol is correct and current, this issue arises when using `HasFromContentType` property on the request as in this [line](https://github.com/IdentityServer/IdentityServer4/blob/6b8d39fa0ca03e40564801864775a4d229e18286/src/IdentityServer4/src/Endpoints/TokenEndpoint.cs#L64). The [current implementation](https://github.com/dotnet/aspnetcore/blob/1815d37d752ec1066726c1be7c52e808b11145f1/src/Http/Http/src/Features/FormFeature.cs#L72) of the property results in True for either **application/x-www-form-urlencoded** or **multipart/form-data**.

If a client makes a Multipart Form, POST request without specifying the boundary parameter as required by the Multipart Form [spec](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html#z0), IdentityServer4 throws an *InvalidDataException*. 

The Exception is thrown at this [line](https://github.com/IdentityServer/IdentityServer4/blob/6b8d39fa0ca03e40564801864775a4d229e18286/src/IdentityServer4/src/Validation/Default/PostBodySecretParser.cs#L60). As it turns out, the presence of the boundary parameter is not validated until [ReadFormAsync()](https://github.com/dotnet/aspnetcore/blob/1815d37d752ec1066726c1be7c52e808b11145f1/src/Http/Http/src/Features/FormFeature.cs#L164), where the exception is also [thrown](https://github.com/dotnet/aspnetcore/blob/1815d37d752ec1066726c1be7c52e808b11145f1/src/Http/Http/src/Features/FormFeature.cs#L316).

Use the following curl request against the token endpoint of a running instance of IdentityServer4 v 3.1.2, will result in this exception:

```bash
curl --data "grant=1" -H 'Content-Type:multipart/form-data' https://identityserveruri/connect/token
```

### Relevant parts of the log file

```
System.IO.InvalidDataException: Missing content-type boundary.
   at Microsoft.AspNetCore.Http.Features.FormFeature.GetBoundary(MediaTypeHeaderValue contentType, Int32 lengthLimit)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at IdentityServer4.Validation.PostBodySecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.SecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

**Comment by brockallen** [comment]
Is this currently causing you an issue?

**Comment by bderveni** [comment]
@brockallen we were getting hits with "Content-Type:multipart/form-data" in our production authorization service and the customer was getting a 500 response back. I have introduced a temporary fix using a middle-ware.

If this an issue and a fix is pushed, I will remove our custom fix.

**Comment by brockallen** [comment]
Why is your customer sending multipart/form-data in the first place?

**Comment by bderveni** [comment]
My assumption is that this call is being made by a web scanning tool.

**Comment by bderveni** [comment]
@brockallen we have encountered another issue with multipart/form-data to the token endpoint. In this case, if the boundary on the body does not match the boundary parameter on the header it results on the following error:

`System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component. 
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at IdentityServer4.Validation.PostBodySecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.SecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)`

The following curl script will reproduce the issue:

`curl -v --data "KeyMissingBoundary=ValueMissingBoundary" -H 'Content-Type:multipart/form-data; boundary=X-Test-Boundary' https://demo.identityserver.io/connect/token`

**Comment by brockallen** [comment]
Given that we reply upon ASP.NET Core to do the form processing, I think about the only check we could add is to compare the content-type header in addition to everything we're already doing.

**Comment by bderveni** [comment]
If the solution is to only allow **application/x-www-form-urlencoded**, replacing `context.Request.HasFormContentType` at this [line](https://github.com/IdentityServer/IdentityServer4/blob/6b8d39fa0ca03e40564801864775a4d229e18286/src/IdentityServer4/src/Endpoints/TokenEndpoint.cs#L64) with your own implementation of [this](https://github.com/dotnet/aspnetcore/blob/1815d37d752ec1066726c1be7c52e808b11145f1/src/Http/Http/src/Features/FormFeature.cs#L283) private function from AspNetCore.

**Comment by brockallen** [comment]
PR merged. THanks
