### ISSUE TITLE
IDX10000: The parameter 'algorithm' cannot be a 'null' or an empty object. (Parameter 'algorithm')

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#4379]
I update `IdentityServer4 `packages to `4.0.0-preview.4.3` and get the error.
My application have not this error with `4.0.0-preview.3`.
What is the **breaking changes** related to this error?

**Comment by leastprivilege** [comment]
More info required

**Comment by mikeandersun** [comment]
This is the StackTrace:
```
 at Microsoft.IdentityModel.Tokens.SigningCredentials.set_Algorithm(String value) in C:\agent1\_work\161\s\src\Microsoft.IdentityModel.Tokens\SigningCredentials.cs:line 115
   at Microsoft.IdentityModel.Tokens.SigningCredentials..ctor(SecurityKey key, String algorithm) in C:\agent1\_work\161\s\src\Microsoft.IdentityModel.Tokens\SigningCredentials.cs:line 90
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddSigningCredential(IIdentityServerBuilder builder, SecurityKey key, String signingAlgorithm)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddDeveloperSigningCredential(IIdentityServerBuilder builder, Boolean persistKey, String filename, RsaSigningAlgorithm signingAlgorithm)
   at vn.IdServer.WebServer.Startup.ConfigureServices(IServiceCollection services) in C:\IDServer\src\vn.IDServer.Host\Startup.cs:line 91

```


It seems the error occurs when call `AddDeveloperSigningCredential `method.

**Comment by mikeandersun** [comment]
I changed this lines :
```
  var tmpKeyPath = Path.Combine(environment.ContentRootPath, "tempkey.rsa");
  builder.AddDeveloperSigningCredential(true, tmpKeyPath);
```

To this :
`                builder.AddDeveloperSigningCredential();
`
and worked.
