### ISSUE TITLE
TokenCleanupHost: One or more hosted services failed to stop on app shutdown.

### ISSUE THREAD

**Issue by msschl** [IdentityServer/IdentityServer4#4403]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

IdentityServer4 v3.1.3
IdentityServer4.AspNetIdentity v3.1.3
IdentityServer4.EntityFramework v3.1.3

### Issue / Steps to reproduce the problem

Tokens get not cleaned up due to the `TokenCleanupHost` not getting started.

```cs
public static IServiceCollection AddDataStoreLayer(this IServiceCollection services,
    IWebHostEnvironment environment,
    IConfiguration configuration,
    IdentityBuilder identityBuilder,
    IIdentityServerBuilder identityServerBuilder)
{
    var connectionString = configuration.GetConnectionString("Identity");
    var migrationsAssembly = typeof(ApplicationDbContext).Assembly.FullName;

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(connectionString, configure =>
        {
            configure.MigrationsAssembly(migrationsAssembly);
        })
    );

    identityBuilder.AddEntityFrameworkStores<ApplicationDbContext>();

    identityServerBuilder.AddConfigurationStore(options =>
    {
        options.ConfigureDbContext = builder =>
        {
            builder.UseSqlServer(connectionString, configure =>
            {
                configure.MigrationsAssembly(migrationsAssembly);
            });
        };
    }).AddOperationalStore(options =>
    {
        options.ConfigureDbContext = builder =>
        {
            builder.UseSqlServer(connectionString, configure =>
            {
                configure.MigrationsAssembly(migrationsAssembly);
            });

            options.EnableTokenCleanup = true;
            options.TokenCleanupInterval = TimeSpan.FromDays(10).Seconds;
        };
    });

    return services;
}
```

The `TokenCleanupHost` is added to the `IServiceCollection`, but it looks like it is never started.
Also, trying to receive the `TokenCleanupHost` from the `IServiceProvider` results in an exception been thrown:

```
System.InvalidOperationException: No service for type 'Microsoft.Extensions.DependencyInjection.TokenCleanupHost' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Company.XYZ.Service.Identity.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment environment, ILogger`1 logger) in W:\service\Identity\src\Company.XYZ.Service.Identity\Startup.cs:line 45
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

### Relevant parts of the log file

```
`watch : Shutdown requested. Press Ctrl+C again to force exit.
[15:04:15 FTL] Host terminated unexpectedly {}
System.AggregateException: One or more hosted services failed to stop. (Not started. Call Start first.)
 ---> System.InvalidOperationException: Not started. Call Start first.
   at Microsoft.Extensions.DependencyInjection.TokenCleanupHost.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Company.XYZ.Service.Identity.Program.Main(String[] args) in W:\service\Identity\src\Company.XYZ.Service.Identity\Program.cs:line 36
watch : Exited
```

**Comment by msschl** [comment]
It's nearly the same. I don't add test users and I don't add developer signing credentials.
Furhter, for the user store I use AspNetCore.Identity.

The app is hosted in IIS as in process application. Maybe it's something related to that?
