### ISSUE TITLE
Redirection after login behind reverse proxy results in exception

### ISSUE THREAD

**Issue by kitohe** [IdentityServer/IdentityServer4#4410]
### Question
I am trying to deploy my app which uses IS4. When user logs in successfully to the service redirection from https://accounts.example.com to the https://example.com/signin-oidc results with internal server error code (500), and exception: `System.Exception: An error was encountered while handling the remote login.
System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty`. To host site I use example.com and IS4 lives at accounts.example.com. To run application I use Apache Server in reverse proxy configuration and docker to host actual apps. When I'm not using https signing user in works correctly. 

What I've tried already: 
- Changing scheme values of ClientRedirectUris in client config file on IdentityServer side
- Changing values of ClientRedirectUris in database from http to https
- Setting PublicOrigin to https://accounts.example.com/

Unfortunately none of those helped. I'll be grateful for any hint on how I can address this issue.

### Identity Server App:

```csharp

// Startup.Configure
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

//Startup.ConfigureServices
services.AddIdentityServer(x =>
            {
                x.IssuerUri = "null";
                x.Authentication.CookieLifetime = TimeSpan.FromHours(2);
                x.PublicOrigin = "https://accounts.example.com/";
            })
            .AddTestUsers(TestUsers.Users)
            .AddAspNetIdentity<ApplicationUser>()
            .AddSigningCredential(Certificate.Certificate.Get())
            .AddProfileService<ProfileService>() ...
```

### Client App

```csharp
// identityUrl = https://accounts.example.com

services.AddAuthentication(options =>
    {
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = "oidc";
    })
    .AddCookie("Cookies")
    .AddOpenIdConnect("oidc", options =>
    {
        options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.Authority = identityUrl;
        options.SignedOutRedirectUri = callBackUrl;
        options.RequireHttpsMetadata = false;
        options.GetClaimsFromUserInfoEndpoint = true;
        options.ClientId = "example";
        options.ClientSecret = "secret";
        options.ResponseType = "code";
        options.SaveTokens = true;
        options.Scope.Add("offline_access");
        options.ClaimActions.Add(new JsonKeyClaimAction("role", null, "role"));
        options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
        {
            NameClaimType = "name",
            RoleClaimType = "role"
        };
    });
```
### Apache reverse proxy config

```
<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

<VirtualHost *:80>
  ProxyPreserveHost On
  ServerName accounts.example.com

 <Location />
  ProxyPass http://127.0.0.1:5000/
  ProxyPassReverse http://127.0.0.1:5000/
 </Location>
RewriteEngine on
RewriteCond %{SERVER_NAME} =accounts.example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:80>
  ProxyPreserveHost On
  ServerName example.com
<Location />
  ProxyPass http://127.0.0.1:5001/
  ProxyPassReverse http://127.0.0.1:5001/
</Location>
RewriteEngine on
RewriteCond %{SERVER_NAME} =example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ProxyPreserveHost On
    ServerName example.com
<Location />
    ProxyPass http://127.0.0.1:5001/
    ProxyPassReverse http://127.0.0.1:5001/
</Location>


SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ProxyPreserveHost On
    ServerName accounts.example.com

    <Location />
    ProxyPass http://127.0.0.1:5000/
    ProxyPassReverse http://127.0.0.1:5000/
    </Location>

SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
```

### docker-compose

```docker-compose
identity:
environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://0.0.0.0:80
    - MvcClient=http://${EXAMPLE_EXTERNAL_DNS_NAME_OR_IP} # http://example.com
ports:
    - "5000:80"

app:
environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://0.0.0.0:80
    - identityUrl=http://${EXAMPLE_IDENTITY_DNS_NAME_OR_IP} # http://accounts.example.com
ports:
    - "5001:80"
```

### Logs

[image](https://i.stack.imgur.com/JFhHh.png)

```
identity_1        | [22:30:17 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
identity_1        | [22:30:18 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
minerfusionmvc_1  | [22:30:19 INF] AuthenticationScheme: OpenIdConnect was challenged.
minerfusionmvc_1  | [22:30:19 INF] Request finished in 1877.3383ms 302
identity_1        | [22:30:19 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
identity_1        | [22:30:19 INF] Showing login: User is not authenticated
identity_1        | [22:30:30 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
minerfusionmvc_1  | [22:30:31 INF] Request starting HTTP/1.1 GET http://minerfusion.com/signin-oidc
minerfusionmvc_1  | [22:30:31 INF] Error from RemoteAuthentication: OpenIdConnectAuthenticationHandler: message.State is null or empty..
minerfusionmvc_1  | [22:30:31 ERR] An unhandled exception has occurred while executing the request.
minerfusionmvc_1  | System.Exception: An error was encountered while handling the remote login.
minerfusionmvc_1  |  ---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
minerfusionmvc_1  |    --- End of inner exception stack trace ---
minerfusionmvc_1  |    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
minerfusionmvc_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
minerfusionmvc_1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
minerfusionmvc_1  |    at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
minerfusionmvc_1  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by kitohe** [comment]
Fixed it, it wasn't reverse proxy setup as I've also tried nginx with the same result. My config was wrong and I don't know exactly which change of code did the trick but here is what I did:

(This was fixed by editing only Startup.cs of client and IS4 file and Config.cs of IS4)

- Changed all redirect uris to https scheme, same in database

- Moved: 

```csharp
// Startup.Configure
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});
```
to:

```csharp
//Startup.ConfigureServices
services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders =
        ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;

    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

//Startup.Configure 
app.UseForwardedHeaders()
```

- In docker-compose file changed scheme from http to https
