### ISSUE TITLE
Use IdentityServer4 for Windows AD 

### ISSUE THREAD

**Issue by Demon520-coder** [IdentityServer/IdentityServer4#4484]
### 
The users of our project are in the same Windows domain. The customer requires to login with a domain account. Our authentication server is identityserver4 which deploy on Ubuntu,In identityServer4, I have made the following configuration:
```csharp
public void ConfigureServices(IServiceCollection services)
 {
            services.AddControllersWithViews();           
 services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate("Negotiate", options =>
            {
                
            });          
            services.AddIdentityServer()
               .AddDeveloperSigningCredential()             
               .AddInMemoryIdentityResources(Config.Ids)
               .AddInMemoryApiResources(Config.Apis)
               .AddInMemoryClients(Config.Clients);              
 }
```
The code for getting user information in WPF desktop application is as follows:
```csharp
public partial class MainWindow : Window
    {
        private OidcClient _oidcClient = null;
        public MainWindow()
        {
            InitializeComponent();
            Loaded += Start;
        }

        public async void Start(object sender, RoutedEventArgs e)
        {
            var policy = new Policy();
            policy.Discovery.RequireHttps = false;
            var options = new OidcClientOptions()
            {
                Authority = "http://ubuntu.domain237.org:5008",
                ClientId = "native.wpf.code",
                Scope = "openid profile email api1",
                RedirectUri = "http://127.0.0.1/sample-wpf-app",
                Policy = policy,
                Browser = new Systembrowser(),
                ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormPost,
                Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode
            };
            _oidcClient = new OidcClient(options);
            LoginResult result;
            string apiResult = string.Empty;
            try
            {
                result = await _oidcClient.LoginAsync();
                //访问api
                HttpClient apiClient = new HttpClient(/*new HttpClientHandler { UseDefaultCredentials = true }*/);
                apiClient.SetBearerToken(result.AccessToken);
                //apiResult = await apiClient.GetStringAsync("http://sk-20200401voje.domain237.org:5006/Home/Get");
                apiResult = await apiClient.GetStringAsync("http://ubuntu.domain237.org:5006/Home/Get");
            }

            catch (Exception ex)
            {
                Message.Text = $"Unexpected Error: {ex.Message}";
                return;
            }

            if (result.IsError)
            {
                Message.Text = result.Error == "UserCancel" ? "The sign-in window was closed before authorization was completed." : result.Error;
            }
            else
            {
                var name = result.User.Identity.Name;
                //Message.Text = $"Hello {name}";
                Message.Text = $"userName={result.User.Identity.Name},apiResult={apiResult}";
            }
        }
    }
```
But when I run the Wpfapp I have come with some errors on IdentityServer4 on Ubuntu:
```csharp
    Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler[5]
      An exception occurred while processing the authentication request.
Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An unsupported mechanism was requested.
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - An unsupported mechanism was requested.
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```
Thank you very much for looking at this problem for me.

**Comment by leastprivilege** [comment]
I have never tried the (new) negotiate handler. So I don't know how it works.

**Comment by leastprivilege** [comment]
That being said - this is not IdentityServer specific - so you can ask Microsoft how that works.

**Comment by zzlProject** [comment]
However,when I deploy IdentityServer4 on the Windows,it's works well. When I deploy IdentityServer on the Ubuntu,It dose not work.

**Comment by leastprivilege** [comment]
Sure - you are missing some OS specific configuration in ASP.NET Core.

**Comment by balkarov** [comment]
@Demon520-coder hello.
Could you show some example how you use AddNegotiate with AddIdentityServer please?

I tried this:
```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews()
        .AddRazorRuntimeCompilation();

    services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
        .AddNegotiate();

    var config = new Config(_staticConfiguration);
    services.AddIdentityServer()
        .AddInMemoryIdentityResources(config.GetIdentityResources())
        .AddInMemoryApiResources(config.GetApiResources())
        .AddInMemoryApiScopes(config.GetApiScopes())
        .AddInMemoryClients(config.GetClients())
        .AddPersistedGrants()
        .AddUserStore()
        .AddDeveloperSigningCredential();
}
```

```C#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseRouting();
    app.UseStaticFiles();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseIdentityServer();
    app.UseIdentityServerTokenCleanup(applicationLifetime);

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapDefaultControllerRoute();
    });
}
```

And I added `[Authorize]` attribute for example method:
```
[HttpGet]
        public IActionResult Example()
        {
            return Redirect("~/");
        }
```

But when I open Example in browser it redirects to /Account/Login.
It only works when I remove `AddIdentityServer()`

But I want implement AddNegotiate when user go to Windows Authorozation.
Sorry, but IdentityServer has not documentation about AddNegotiate with IdentityServer(
