### ISSUE TITLE
[Possible breaking change in v4.0.0] IDX10000: The parameter 'algorithm' cannot be a 'null' or an empty object. (Parameter 'algorithm')

### ISSUE THREAD

**Issue by 8jigarpatel** [IdentityServer/IdentityServer4#4579]
**Details**
I was in process of upgrading IdentityServer to 4.0.0 from 3.1.3
Trying to run the application threw `IDX10000: The parameter 'algorithm' cannot be a 'null' or an empty object. (Parameter 'algorithm')` exception in the startup class (StackTrace attached below). These lines throw exception:

```
     serverBuilder.AddDeveloperSigningCredential(
          filename: _appSettings.IdentityServer.KeysLocation + "/tempkey.rsa",
      );
```

**StackTrace**
```
   at Microsoft.IdentityModel.Tokens.SigningCredentials.set_Algorithm(String value)
   at Microsoft.IdentityModel.Tokens.SigningCredentials..ctor(SecurityKey key, String algorithm)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddSigningCredential(IIdentityServerBuilder builder, SecurityKey key, String signingAlgorithm)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddDeveloperSigningCredential(IIdentityServerBuilder builder, Boolean persistKey, String filename, RsaSigningAlgorithm signingAlgorithm)
   at IdentityServer.Startup.ConfigureServices(IServiceCollection services) in ...\IdentityServer\Startup.cs:line 111
```

**Fix**
The `filename` parameter required to be something with `.jwk` extension, rather than previously `.rsa`.

*Request / Suggestion*
This should probably go into breaking changes if my observation is valid.

**Comment by 8jigarpatel** [comment]
Hi @leastprivilege, Just for my understanding, do you consider this a bug? (I.e., should IdentityServer be able to work with `.rsa` filenames as before?) Or is it going to be addressed by updating the docs (E.g., Version 4 onward requires `.jwk` instead of the `.rsa` extension for the `filename` parameter? Thank you 😊

**Comment by leastprivilege** [comment]
Hey, 

OK - I see what's going on.

We changed the file format in v4 and switched to the JSON Web Key format, because this will also support EC in the future.

Normally this is not a problem, since the developer key is supposed to be temporary. Your usage indicates that you are treating the dev key as a stable key - am I right?

**Comment by 8jigarpatel** [comment]
Thank you for further information!

And yes, I persist the dev key so the same key can be used even after application restarts etc.

I understand this approach isn’t a scalable solution (E.g., probably won’t work in load balanced system maybe?) But works fine for me for development and testing. 😁
