### ISSUE TITLE
IdentityServer4 4.0.0 appears to be incompatible with Rsk.IdentityServer4.Saml 2.10

### ISSUE THREAD

**Issue by jigneshpanchal22** [IdentityServer/IdentityServer4#4584]
### Issue / Steps to reproduce the problem

using Identityserver4 version 4.0.0 with Rsk.IdentityServer4.Saml 2.10

### Relevant parts of the log file

```
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.IReadableStringCollectionExtensions' from assembly 'IdentityServer4, Version=4.0.0.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b'.
   at Rsk.AspNetCore.Authentication.Saml2p.Saml2pAuthenticationHandler.ExtractBindingTypeAndParameters(String& bindingType, NameValueCollection& parameters)
   at Rsk.AspNetCore.Authentication.Saml2p.Saml2pAuthenticationHandler.HandleRemoteAuthenticateAsync()
```

**Comment by brockallen** [comment]
Please open an issue with Rock Solid Knowledge. // @scottbrady91

**Comment by brockallen** [comment]
Since this is not an IdentityServer issue, I will close this.

**Comment by scottbrady91** [comment]
FYI: We've just released our first preview for v4 https://www.nuget.org/packages/Rsk.IdentityServer4.Saml/4.0.0-preview1
