### ISSUE TITLE
Error getting logout context after updating to v4

### ISSUE THREAD

**Issue by rubo** [IdentityServer/IdentityServer4#4590]
After updating to the v4, invoking `GetLogoutContextAsync(logoutId)` returns an empty context while logging the following:
```
System.InvalidOperationException: Each parameter in constructor 'Void .ctor(IdentityServer4.Models.LogoutMessage, System.DateTime)' on type 'IdentityServer4.Models.Message`1[IdentityServer4.Models.LogoutMessage]' must bind to an object member on deserialization. Each parameter name must be the camel case equivalent of an object member named with the pascal case naming convention.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(ConstructorInfo constructorInfo, Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at IdentityServer4.ObjectSerializer.FromString[T](String value)
   at IdentityServer4.Stores.ProtectedDataMessageStore`1.ReadAsync(String value)
```
End session endpoint succeeds with log `Success validating end session request from...` and returns logout id.
I wasn't able to find any info about what has been changed in logout in the v4.

_Downgrading to v3 works just fine._

Could someone please shed more light on this? What additional info do I need to provide?

**Comment by rubo** [comment]
As the new IdentityServer4 v4 mostly relies on System.Text.Json, it turned out the problem is with System.Text.Json 5.0.0-preview that my .NET Core 3.1-based project uses under the hood.
With this said, I don't expect this issue to be prioritized. Nevertheless, I believe this issue needs some attention as the problem exists with all currently available preview versions of System.Text.Json 5.0.0, and it seems like there are some permanent changes that are most likely going to stay.

**Comment by leastprivilege** [comment]
IdentityServer4 targets .NET Core 3.1.

Future versions of .NET might not be compatible.

**Comment by ibrahimmsam** [comment]
Knowing IdentityServer4 V4 not compatible with .NET 5 saved me a lot time, as I was testing IdentityServer4 on .NET 5 prior to upgrade to IndentityServer4 V4 there was no problem, but after the upgrade to V4, I received the above error, but reverting back to .NET Core 3.1, everything went back as expected.
