### ISSUE TITLE
AutoMapper package conflict

### ISSUE THREAD

**Issue by nimrod46** [IdentityServer/IdentityServer4#4662]
**We can only help you if you are on the latest version. Either use the latest 3.x or 4.x**
Using the latest version - 3.1.6
### Issue / Steps to reproduce the problem
- Creating a new blazor webassembly app (can confirm the issue exists also in blazor PWA).
- I scaffolded all the Identities files though I not sure if it's mandatory in order to reproduce this problem.
- Add `@RenderSection("Scripts", required: false)` in server's `_Layout.cshtml` so the app won't crash after scaffolding
- **Install `AutoMapper.Extensions.Microsoft.DependencyIn` package - _ver 8.0.0_**
- Register
- Then, finally, try to log in, you will get the following exception:

```
Test2.Server.Areas.Identity.Pages.Account.LoginModel: Information: User logged in.
IdentityServer4.Hosting.IdentityServerMiddleware: Information: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
Exception thrown: 'System.MissingMethodException' in IdentityServer4.EntityFramework.Storage.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Diagnostics.StackTrace.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Reflection.Metadata.dll'. 
IdentityServer4.Events.DefaultEventService: Information: {
  "Name": "Unhandled Exception",
  "Category": "Error",
  "EventType": "Error",
  "Id": 3000,
  "Details": "System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.\r\n   at IdentityServer4.EntityFramework.Mappers.PersistedGrantMappers.ToEntity(PersistedGrant model)\r\n   at IdentityServer4.EntityFramework.Stores.PersistedGrantStore.StoreAsync(PersistedGrant token)\r\n   at IdentityServer4.Stores.DefaultGrantStore`1.StoreItemAsync(String key, T item, String clientId, String subjectId, DateTime created, Nullable`1 expiration)\r\n   at IdentityServer4.Stores.DefaultGrantStore`1.CreateItemAsync(T item, String clientId, String subjectId, DateTime created, Int32 lifetime)\r\n   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateCodeFlowResponseAsync(ValidatedAuthorizeRequest request)\r\n   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateResponseAsync(ValidatedAuthorizeRequest request)\r\n   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent)\r\n   at IdentityServer4.Endpoints.AuthorizeCallbackEndpoint.ProcessAsync(HttpContext context)\r\n   at IdentityServer4.Endpoints.AuthorizeCallbackEndpoint.ProcessAsync(HttpContext context)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)",
  "Message": "Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.",
  "ActivityId": "800002ed-0002-e500-b63f-84710c7967bb",
  "TimeStamp": "2020-07-15T13:16:34Z",
  "ProcessId": 26564,
  "LocalIpAddress": "::1:44323",
  "RemoteIpAddress": "::1"
}
IdentityServer4.Hosting.IdentityServerMiddleware: Critical: Unhandled exception: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.

System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.
   at IdentityServer4.EntityFramework.Mappers.PersistedGrantMappers.ToEntity(PersistedGrant model)
   at IdentityServer4.EntityFramework.Stores.PersistedGrantStore.StoreAsync(PersistedGrant token)
   at IdentityServer4.Stores.DefaultGrantStore`1.StoreItemAsync(String key, T item, String clientId, String subjectId, DateTime created, Nullable`1 expiration)
   at IdentityServer4.Stores.DefaultGrantStore`1.CreateItemAsync(T item, String clientId, String subjectId, DateTime created, Int32 lifetime)
   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateCodeFlowResponseAsync(ValidatedAuthorizeRequest request)
   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateResponseAsync(ValidatedAuthorizeRequest request)
   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent)
   at IdentityServer4.Endpoints.AuthorizeCallbackEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Endpoints.AuthorizeCallbackEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

**Comment by brockallen** [comment]
I tested the latest version and it seems to be working.

**Comment by djary** [comment]
I have the same Issue
