### ISSUE TITLE
TypeLoadException: Method 'GetAllAsync' in type 'IdentityServer4.Stores.InMemoryPersistedGrantStore' from assembly 'IdentityServer4, Version=3.0.0.0, ...' does not have an implementation.

### ISSUE THREAD

**Issue by jonasarcangel** [IdentityServer/IdentityServer4#4669]
After updating Microsoft.AspNetCore.ApiAuthorization.IdentityServer to 3.1.6, I started to get the following error during Startup. Downgrading back to 3.1.5, even after clean build, I still get the error now.

```
System.TypeLoadException: Method 'GetAllAsync' in type 'IdentityServer4.Stores.InMemoryPersistedGrantStore' from assembly 'IdentityServer4, Version=3.0.0.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsInMemory.AddInMemoryPersistedGrants(IIdentityServerBuilder builder)
   at Microsoft.Extensions.DependencyInjection.IdentityServerServiceCollectionExtensions.AddIdentityServer(IServiceCollection services)
   at MyProject.Web.Server.Startup.ConfigureServices(IServiceCollection services) in C:\MyProject\src\MyProject.Web.Server\Startup.cs:line 40
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MyProject.Web.Server.Program.Main(String[] args) in C:\MyProject\src\MyProject.Web.Server\Program.cs:line 11
```

**Comment by leastprivilege** [comment]
This seems to be related to Microsoft's IdentityServer integration. Please open an issue on their issuer tracker instead. @javiercn @blowdart

https://github.com/aspnet/aspnetcore/issues

**Comment by javiercn** [comment]
@leastprivilege We plan to update the version of Identity Server we use for 5.0, we haven't got to it yet.
