### ISSUE TITLE
Internal redirect not work

### ISSUE THREAD

**Issue by rafaelgfirmino** [IdentityServer/IdentityServer4#4769]
I have been spending a lot of time trying to fix this particular problem of mine.
So I need help.

 I tray put my project in the server of production but not a success. I try to access the router for recovery logged user in this route api/app/configuration.

I can login in the application, but when I try to get any request this error is printed in my console(I'm using docker)

Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler
Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://SERVER/qa-identity/.well-known/openid-configuration'.

when I use localhost this application work's fine.

My nginx proxy has this configuration
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection keep-alive;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_cache_bypass $http_upgrade;

**Comment by rafaelgfirmino** [comment]
Hi guys, I finally managed to solve this issue.
As I am using microservices in docker containers, I was making requests from different places. With that, I needed to fix my IssuerUri.

services.AddIdentityServer (x =>
{
x.IssuerUri = "my_auth";
})
I solved my problem-based in this question in StackOverflow

**Comment by RaiBnod** [comment]
I have a linux server with `NGINX` which proxies `https://mydomain.com` request to the `https://localhost:8080` -- this backend is running on a docker instance. 

But, I got issue like this.

```
backend_1  | info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
backend_1  |       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
backend_1  | fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
backend_1  |       Exception occurred while processing message.
backend_1  | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  |  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://127.0.0.1:8080/.well-known/openid-configuration/jwks'.
backend_1  |  ---> System.Net.Http.HttpRequestException: Connection refused
backend_1  |  ---> System.Net.Sockets.SocketException (111): Connection refused
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
backend_1  | fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
backend_1  |       IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  |  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://127.0.0.1:8080/.well-known/openid-configuration/jwks'.
backend_1  |  ---> System.Net.Http.HttpRequestException: Connection refused
backend_1  |  ---> System.Net.Sockets.SocketException (111): Connection refused
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
backend_1  |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
backend_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
backend_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
backend_1  |    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
backend_1  |       Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
backend_1  |       Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
backend_1  |       Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[12]
backend_1  |       AuthenticationScheme: Bearer was challenged.
```

**Note:** Currently I set IdentityServerAuthentication > Authoriy as `https://mydomain.com`
