### ISSUE TITLE
logoutId is always NULL

### ISSUE THREAD

**Issue by nareshkathi** [IdentityServer/IdentityServer4#4771]
LogoutId is always coming as NULL. 

I have my application project set as below
IdentityServer app : SampleIdentityApp
AngularClient : SampleUI

**Version using:**
netcore : 3.1
IdentityServer4  : 4.0.4
Angular: 10
oidc-client: 1.9.1

I am having this issue directly on Identity Server 4 application(SampleIdentityApp) when i initiate Logout.

And just to verify, i tried with Angular oidc-client(SampleUI) as well but i see the same issue. 

**Code:**

```
[HttpGet]
public async Task<IActionResult> Logout(string logoutId)
        {
            var context = await _interaction.GetLogoutContextAsync(logoutId);
            if (context?.ShowSignoutPrompt == false)
            {
                // it's safe to automatically sign-out
                return await Logout(new LogoutViewModel { LogoutId = logoutId });
            }

            // build a model so the logout page knows what to display
            var vm = await BuildLogoutViewModelAsync(logoutId);

            if (vm.ShowLogoutPrompt == false)
            {
                // if the request for logout was properly authenticated from IdentityServer, then
                // we don't need to show the prompt and can just log the user out directly.
                return await Logout(new LogoutViewModel { LogoutId = logoutId });
            }

            return View(vm);
        }
```

### Relevant parts of the log file

System.ArgumentException: Value cannot be null or empty. (Parameter 'url')
   at Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(String url)
   at Identity.Controllers.AccountController.Logout(LogoutInputModel model) in \Identity\Controllers\AccountController.cs:line 918
   at Identity.Controllers.AccountController.Logout(String logoutId) in \Identity\Controllers\AccountController.cs:line 860
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)

**Comment by brockallen** [comment]
Check your IdentityServer logs during the end session request.

**Comment by nareshkathi** [comment]
I am having this is not only when i initiate logout from Angular client but also from Identity Server as well like below.

Below is my Identity Server app (runs on https://localhost:44310) and LogoutId is coming as null when i click on "Logout" shown in screenshot.
![image](https://user-images.githubusercontent.com/40530509/90849039-31f93e80-e323-11ea-95b8-db9f39ee2bbb.png)


And my Angular app runs on http://localhost:4200

Below is the complete log for "connect/endsession" call

`      Request starting HTTP/2 GET https://localhost:44310/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6IjAwQkM4OTQ1QTBCN0M0RjA3RERGQUE1NzI1MTlEOUFCIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1OTc5Nzg5ODEsImV4cCI6MTU5Nzk4MTk4MSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTAiLCJhdWQiOiJlQ3J5cHRfZmVfb2lkYyIsImlhdCI6MTU5Nzk3ODk4MSwiYXRfaGFzaCI6Ilc4WFpIS1RxaGNaZExfVG5pQ0JOZEEiLCJzX2hhc2giOiJFMkVyTUdnWXkyQjBFLWV5eHFSN3FRIiwic2lkIjoiNDI2M0QxMjU3QkREMjc5OTdFNTYyN0REMzgwQkU3MDgiLCJzdWIiOiJlOGI5YjY1Mi1lMTIzLTQ2MDktOTUwYy1hNGUzZDI5NTFkYWQiLCJhdXRoX3RpbWUiOjE1OTc5Nzg5NzksImlkcCI6ImxvY2FsIiwiYW1yIjpbInB3ZCJdfQ.TGAcFzqYe1GI8GoQ1-82aw3vqqMNCpLN3vHI6CegWc66ZzFj-_E-tRA-KyUW4Wv5E35xWGe_OEsfWE0lrOo3_jlpnXGCiV9LAUOERfOgg4r2u0tXQJHbuoiu4-dOPqQp5vjq1hL0cNW8aCEDji-tVIdZ7Aiv1VXLxeovtYrsnjXaHNsvHJ6_V_SaGlpa8a17-BA4ym9KOEUvj269tjAHqiLhdSatrBaDBzVT6l22WXchl0hcVyAfFGNpjE8z09_WJmnQsyYIepZ8uX79GMuNb-Z7PjiBBiJj7Mk5pwuSDsjFAi0ozPM34jmYGgEbDCMMwnNkIRtBjF8qZUIzxIPUjA&post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauthentication%2Flogout-callback&state=3fcb6334e8d44964b7d3502de7ac2c14
info: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.EndSessionEndpoint for /connect/endsession
info: IdentityServer4.Validation.EndSessionRequestValidator[0]
      End session request validation success
      {
        "ClientId": "Angular_fe_oidc",
        "ClientName": "Interactive client with short token lifetime (Code with PKCE)",
        "SubjectId": "e8b9b652-e123-4609-950c-a4e3d2951dad",
        "PostLogOutUri": "http://localhost:4200/authentication/logout-callback",
        "State": "3fcb6334e8d44964b7d3502de7ac2c14",
        "Raw": {
          "id_token_hint": "***REDACTED***",
          "post_logout_redirect_uri": "http://localhost:4200/authentication/logout-callback",
          "state": "3fcb6334e8d44964b7d3502de7ac2c14"
        }
      }
info: Request starting HTTP/2 GET https://localhost:44310/Account/Logout?/Account/Login=CfDJ8P0h-BVvoURKgAVBNLKKCxdsBRHreO7br50czVWxp5TLbfZvU4MNxAmm3Wjzf3-FchcSJwe7I2HRXhh-rvF86dakZ9SLukXubqV9_yineBSYBUKoDVImQwD1LUvf07rHnaC-VVucegm6Gi9y2ZvoNYB0XHTU4D3h48EeVipV-RSzG-cyMgw84g_zMt6abuAsXnADgwkrYV9h42N0qV30EyTM7slhOQDN-oaVCQ6jsbHVRBQIUfEP0sWJJ6FCMT_CgBmC4RpbwG1p-o3cobqucgz4I9VHLZn9ShZgEbfk1CSxCnkT-kUczzxnB07i-PF-2KPu6vEt1a7nJrixNZo7KW0F5c_9k7YGUssjRjz0obrgThLmL--vLb7tdBwpwHJixzqTI3HU9EUcAo6hFA2xZyBRXhEDKVd5GStzzFQCqMFbisTrZsr5zaFuOU_35d2AEVew18YrzxKtN2Auo2NCLathnadTzi86AB0PyG1iwP37MHmIR-yQcYh3gvLuPvyNt1ch6G532fMOdl8dVnjwYX-7-nwGqkqMuuUpmPjQi0FB0mQGlipMz-SWQlRcU4ElMIl30Ax_zH6FlmbYa1In8W1QuQa661-46EYeFPgilnFPAEtkzKYYKiHLRah9yfAAv2h0BxP97-psGrtqRincIdk
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.Application signed out.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.TwoFactorUserId signed out.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
info: IdentityServer4.Events.DefaultEventService[0]
      {
        "SubjectId": "e8b9b652-e123-4609-950c-a4e3d2951dad",
        "DisplayName": "testuser9",
        "Category": "Authentication",
        "Name": "User Logout Success",
        "EventType": "Success",
        "Id": 1002,
        "ActivityId": "0HM25FQFK81KD:00000003",
        "TimeStamp": "2020-08-21T03:06:14Z",
        "ProcessId": 10572,
        "LocalIpAddress": "::1:44310",
        "RemoteIpAddress": "::1"
      }
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Identity.Controllers.AccountController.Logout (Identity) in 72275.6259ms
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentException: Value cannot be null or empty. (Parameter 'url')
   at Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(String url)
   at Identity.Controllers.AccountController.Logout(LogoutInputModel model) in D:\IdentityTestApp\Identity\Controllers\AccountController.cs:line 920
   at Identity.Controllers.AccountController.Logout(String logoutId) in D:\IdentityTestApp\Identity\Controllers\AccountController.cs:line 861
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
  	  
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:44310/connect/endsession?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauthentication%2Flogout-callback&state=6c3f1127bac644e9b1807a0e8a3b2fde
info: IdentityServer4.Validation.EndSessionRequestValidator[0]
      End session request validation success
      {
        "SubjectId": "e8b9b652-e123-4609-950c-a4e3d2951dad",
        "Raw": {
          "post_logout_redirect_uri": "http://localhost:4200/authentication/logout-callback",
          "state": "6c3f1127bac644e9b1807a0e8a3b2fde"
        }
      }
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:44310/Account/Logout?/Account/Login=CfDJ8P0h-BVvoURKgAVBNLKKCxeiJgFQE0Addv19P17CKl0BIwk0izRWGd6w6zLvQYC8KxfKCAjOQMQ6ZQfgoMPBhLUoahkLNmh6-wC36MyqntGXIjzYbHwMHT9-8D-wbBHknDkaf1EM0u-imxGm3CmvOOC263TViyEr2Qbovaodnu6novvYmIEz8lW0dh6rVc8TGSesG109fW__LRSGDIkWeSL1vurNjZIT987t7dYc32MI8T17dgTL-kAmOwnpKFLge3tOA58m8c_HXGq1eH-6YPNFlAwYukP4rFgqixo_HmMHhuqKjQH4cwUk49hUPi4FHrQ_9Bf6waZF13pLDmqd-gW0I8QwKm3ZXSpKtodKTCjS

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentException: Value cannot be null or empty. (Parameter 'url')
   at Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(String url)
   at Identity.Controllers.AccountController.Logout(LogoutInputModel model) in D:\IdentityTestApp\Identity\Controllers\AccountController.cs:line 920
   at Identity.Controllers.AccountController.Logout(String logoutId) in D:\IdentityTestApp\Identity\Controllers\AccountController.cs:line 861
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
 `
