### ISSUE TITLE
Using ADFS as external OIDC authentication and passing on claims

### ISSUE THREAD

**Issue by unipeg** [IdentityServer/IdentityServer4#4875]
### Question

I have a trusted asp.net core web application with a webapi backend and I want to protect this backend so ajax calls include OIDC access tokens.
I looked at Scott's nice [getting started guide](https://www.scottbrady91.com/Identity-Server/Getting-Started-with-IdentityServer-4#Entity-Framework-Core) to create a new IdentityServer4-application, and connect it with my asp.net app.

So I would like both id_token and access_token to be exposed in redirect url fragements in the callback to my application.

### ConfigureServices from Startup.cs of my asp.net core application

```csharp
     public void ConfigureServices(IServiceCollection services)
        {
            IdentityModelEventSource.ShowPII = true;

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "cookie";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("cookie")
            .AddOpenIdConnect("oidc", options =>
            {
                options.Authority = <<URL_of_IdentityServer_application>>;
                options.ClientId = "<<my_clientId>>";
                options.ClientSecret = "<<my_client_secret>>";

                options.ResponseType = "token id_token";
                options.UsePkce = true;

                options.Scope.Add("api1");

                // keeps id_token smaller
                options.GetClaimsFromUserInfoEndpoint = true;
                options.SaveTokens = true;

                options.Events.OnRedirectToIdentityProvider = async context =>
                {
                    context.ProtocolMessage.RedirectUri = "<<redirection_url_of_application>>";
                    await Task.FromResult(0);
                };
            });

            services.AddControllersWithViews();
        }
```

### ConfigureServices from Startup.cs of IdentityServer application contains the following:

```csharp
        services.AddIdentityServer()
                .AddInMemoryClients(Clients.Get())
                .AddInMemoryIdentityResources(Resources.GetIdentityResources())
                .AddInMemoryApiResources(Resources.GetApiResources())
                .AddInMemoryApiScopes(Resources.GetApiScopes())
                .AddTestUsers(Users.Get())
                .AddDeveloperSigningCredential();
```

I've defined a couple of users. But I don't seem to get details of the user in the id_token. How do I get e.g. Email and Role claims passed on to the resulting claim from IdSvr to my application?

Secondly, I've added a ADFS as external OIDC provider, by adding this to IdentityServer's Startup.cs ConfigureServices:

```csharp
        services.AddAuthentication()
                .AddOpenIdConnect("oidc_adfs", "ADFS", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                    options.SaveTokens = true;

                    options.Authority = "<<url_of_my_ADFS_instance>>";
                    options.ClientId = "<<clientId_of_RelayParty_defined_in_ADFS>>";
                    options.ClientSecret = "<<clientSecret_of_RelayParty_defined_in_ADFS>>";
                    options.Resource = "<<relaying_party_identifier_in_ADFS>>"; // <-- is this necessary?

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };

                    options.ResponseType = "id_token"; // <-- correct?
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.Scope.Add("openid");
                    options.Scope.Add("profile");
                });
```

Authication goes fine, but IdentityServer reports the following and I'm not redirected back to my app:

### Error log:

```
[INF] AuthenticationScheme: oidc_adfs was challenged.
[DBG] CORS request made for path: /signin-oidc from origin: <<base_url_of_my_ADFS_instance>> but was ignored because path was not for an allowed IdentityServer CORS endpoint
[INF] Error from RemoteAuthentication: Unable to unprotect the message.State..
[ERR] An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Unable to unprotect the message.State.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
I've tried to mitigate this by adding the following to IdentityServer's Startup.cs ConfigureServices:

```csharp
            services.AddCors(options => {
                options.AddPolicy("default", policy =>
                {
                    policy.WithOrigins("<<endpoint_of_my_ADFS_instance>>")
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials();
                });
            });
```
and subsequently in Configure method:
```csharp
            app.UseCors("default");
```

Am I using wrong flows from app -> IdSvr (requesting "token id_token") and IdSvr -> ADFS (requesting "id_token")?
My end goal is to pass on role/group claims as well as user information such as full name, username etc.

**Comment by unipeg** [comment]
The issue with IdP claims not being transferred was due to Client setting: `AlwaysIncludeUserClaimsInIdToken `which needed to be `true`.
I close this and open another one specific to the ADFS issue.
