### ISSUE TITLE
System.Text.Json deserialization fails in .NET5 RC1 

### ISSUE THREAD

**Issue by andreasblinzler** [IdentityServer/IdentityServer4#4912]
Moved my project to .NET5 RC1.

Lib versions:

- IdentityModel: 5.0.0-preview.0
- IdentityServer4: 4.1.0
- IdentityServer4.Storage: 4.1.0

I get the following exception during authentication (after confirming consent view):

Each parameter in constructor 'Void .ctor(IdentityServer4.Models.ConsentResponse, System.DateTime)' on type 'IdentityServer4.Models.Message`1[IdentityServer4.Models.ConsentResponse]' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.

Stack trace:

   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(ConstructorInfo constructorInfo, Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at IdentityServer4.ObjectSerializer.FromString[T](String value)
   at IdentityServer4.MessageCookie`1.Unprotect(String data)
   at IdentityServer4.MessageCookie`1.ReadByCookieName(String name)

**Comment by leastprivilege** [comment]
a) please don't use IdentityModel v5. (preview.0 ;))
b) we haven't tested against .NET 5 - it is not LTS and thus not high priority

**Comment by andreasblinzler** [comment]
a) same problem with IdentityModel 4.4.0
b) it would be nice if you could support .NET5 soon - after all, it is a major version ;-)

**Comment by ChrisKlug** [comment]
I got the same error in my IdentityServer4 project. I think this is a pretty simple fix. I just fixed the same error for another project (I think, looking at the error). It's just a mismatch between the constructor for the deserialized entity and the passed in JSON. Is this something that would be interesting to get a PR for?

**Comment by leastprivilege** [comment]
Hey @ChrisKlug - if you would give that a try, that would be cool!

Please also make sure it still works on 3.1 after the change ;)

**Comment by leastprivilege** [comment]
merged, thanks!
