### ISSUE TITLE
Failed to parse token response body as JSON. The parameter 'json' cannot be a 'null' or an empty object`

### ISSUE THREAD

**Issue by balkarov** [IdentityServer/IdentityServer4#4917]
### Question
Hello. 
After login I get error in /signin-oidc: `OpenIdConnectProtocolException.  Failed to parse token response body as JSON. The parameter 'json' cannot be a 'null' or an empty object`

This works on localhost. But does not work on my domain.
I tried to find this error in internet, but nothing found.

I use: 
Asp net core 3.1
IdentityServer4 4.0.4

### Minimal working example

My config
```csharp
new Client
{
    ClientId = "mvc",
    ClientName = "MVC Client",
    AllowedGrantTypes = GrantTypes.Code,
    RedirectUris = {new UriBuilder(_staticConfiguration.Uri).WithRelativeSegment("signin-oidc").Uri.ToString()},
    PostLogoutRedirectUris =  {new UriBuilder(_staticConfiguration.Uri).WithRelativeSegment("signout-callback-oidc").Uri.ToString()},
    RequireConsent = false,
    RequirePkce = true,
    RequireClientSecret = false,
    UpdateAccessTokenClaimsOnRefresh = true,
    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        "roles",
        "api1.scope1",
        "roles"
    },
    AllowOfflineAccess = true
},
```

Statup.cs 

```c#
services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = "oidc";
})
    .AddCookie(options =>
    {
        options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
    })
    .AddAutomaticTokenManagement()
    .AddOpenIdConnect("oidc", options =>
    {
        options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

        options.Authority = _staticConfiguration.IdentityServerUri;
        options.RequireHttpsMetadata = false;

        options.ClientId = "mvc";
        options.ResponseType = OpenIdConnectResponseType.Code;

        options.SaveTokens = true;
        options.GetClaimsFromUserInfoEndpoint = true;

        options.Scope.Clear();
        options.Scope.Add("openid");
        options.Scope.Add("profile");
        options.Scope.Add("api1.scope1");
        options.Scope.Add("roles");
        options.Scope.Add("offline_access");
        options.ClaimActions.MapJsonKey("role", "role");
        options.TokenValidationParameters = new TokenValidationParameters
        {
            NameClaimType = JwtClaimTypes.Name,
            RoleClaimType = JwtClaimTypes.Role
        };
        options.UsePkce = true;
    });

```

### Relevant parts of the log file

```
System.Exception: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Failed to parse token response body as JSON. Status Code: 500. Content-Type: 
 ---> System.ArgumentNullException: IDX10000: The parameter 'json' cannot be a 'null' or an empty object. (Parameter 'json')
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectMessage..ctor(String json)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

**Comment by balkarov** [comment]
When I run identity Server via dotnet run then it works. But via IIS does not work

**Comment by balkarov** [comment]
I fixed this problem.
Problem was in IdentityServer. It cannot read certifacite in folder. Crashed with "Keyset does not exist".
I install certficiate in local machine and change in pool Identity to localsystem.
maybe this will help someone.
