### ISSUE TITLE
EntityFramework tests fail when running build.ps1; fresh clone of 4.1.1. Am I doing it wrong?

### ISSUE THREAD

**Issue by theboojit** [IdentityServer/IdentityServer4#4992]
### Question
Hi, I'm new to IdentityServer and so I'm guessing I've missed a simple step. I've just cloned the repository and switched to the 4.1.1 tag, and ran "build.ps1". It fails here, during EF integration tests:

```EntityFramework: dotnet test -c Release --no-build
Test run for C:\Users\theboojit\source\repos\IdentityServer4\src\EntityFramework\test\IdentityServer4.EntityFramework.Tests\bin\Release\netcoreapp3.1\IdentityServer4.EntityFramework.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:15.44]     IdentityServer4.EntityFramework.IntegrationTests.Services.CorsPolicyServiceTests.IsOriginAllowedAsync_WhenOriginIsNotAllowed_ExpectFalse(options: DbContextOptions`1 { ContextType = typeof(IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext), Extensions = [CoreOptionsExtension { ... }, InMemoryOptionsExtension { ... }], IsFrozen = False }) [FAIL]
[xUnit.net 00:00:15.45]     IdentityServer4.EntityFramework.IntegrationTests.Services.CorsPolicyServiceTests.IsOriginAllowedAsync_WhenOriginIsNotAllowed_ExpectFalse(options: DbContextOptions`1 { ContextType = typeof(IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext), Extensions = [SqliteOptionsExtension { ... }, CoreOptionsExtension { ... }], IsFrozen = False }) [FAIL]
[xUnit.net 00:00:15.55]     IdentityServer4.EntityFramework.IntegrationTests.Services.CorsPolicyServiceTests.IsOriginAllowedAsync_WhenOriginIsNotAllowed_ExpectFalse(options: DbContextOptions`1 { ContextType = typeof(IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext), Extensions = [SqlServerOptionsExtension { ... }, CoreOptionsExtension { ... }], IsFrozen = False }) [FAIL]
  X IdentityServer4.EntityFramework.IntegrationTests.Services.CorsPolicyServiceTests.IsOriginAllowedAsync_WhenOriginIsNotAllowed_ExpectFalse(options: DbContextOptions`1 { ContextType = typeof(IdentityServer4.EntityFramework.DbContexts.ConfigurationDbContext), Extensions = [CoreOptionsExtension { ... }, InMemoryOptionsExtension { ... }], IsFrozen = False }) [1ms]
  Error Message:
   Microsoft.Data.SqlClient.SqlException : CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\theboojitTest.IdentityServer4.EntityFramework-3.1.0.CorsPolicyServiceTests.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
  Stack Trace:
     at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)  
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
   at IdentityServer4.EntityFramework.IntegrationTests.Services.CorsPolicyServiceTests..ctor(DatabaseProviderFixture`1 fixture) in C:\Users\theboojit\source\repos\IdentityServer4\src\EntityFramework\test\IdentityServer4.EntityFramework.Tests\Services\CorsPolicyServiceTests.cs:line 27
```

Relevant snippet:
```  Error Message:
   Microsoft.Data.SqlClient.SqlException : CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\theboojitTest.IdentityServer4.EntityFramework-3.1.0.CorsPolicyServiceTests.mdf'.
```

The path "C:\Users\theboojitTest.IdentityServer4.EntityFramework-3.1.0.CorsPolicyServiceTests.mdf'" looks suspicious to me, like it's missing a "\\" between "theboojit" and "Test.IdentityServer4."

I tried to update line 32 in src\EntityFramework\test\IdentityServer4.EntityFramework.Tests\DatabaseProviderBuilder.cs:
``` 
$@"Data Source=(LocalDb)\MSSQLLocalDB;database=Test.IdentityServer4.EntityFramework-3.1.0.{name};trusted_connection=yes;"); 
```
by putting a "\\" after "database=", but that seems to get converted to a "_" character at runtime.

I'm guessing there's something very simple I should be doing, but I can't seem to figure it out. I did try searching the issues DB but can't seem to find anyone else having the same issue. Any help is very appreciated, thanks.

**Comment by leastprivilege** [comment]
I have never seen this problem before. @brockallen ?
