### ISSUE TITLE
System.InvalidOperationException: IDX20803

### ISSUE THREAD

**Issue by RaiBnod** [IdentityServer/IdentityServer4#5042]
I have a linux server with `NGINX` which proxies `https://mydomain.com` request to the `https://localhost:8080` -- the backend is running on a docker instance and it has exposed port `8080`. 

I have gone through documentation:
- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0

& solution:

- https://github.com/IdentityServer/IdentityServer4/issues/1331#issuecomment-317049214

And able to get `JWT` token. But while accessing the API from that token,  it returns `401` status code and shows following logs on console.

```
backend_1  | info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
backend_1  |       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
backend_1  | fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
backend_1  |       Exception occurred while processing message.
backend_1  | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  |  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://127.0.0.1:8080/.well-known/openid-configuration/jwks'.
backend_1  |  ---> System.Net.Http.HttpRequestException: Connection refused
backend_1  |  ---> System.Net.Sockets.SocketException (111): Connection refused
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
backend_1  | fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
backend_1  |       IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  |  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://127.0.0.1:8080/.well-known/openid-configuration/jwks'.
backend_1  |  ---> System.Net.Http.HttpRequestException: Connection refused
backend_1  |  ---> System.Net.Sockets.SocketException (111): Connection refused
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
backend_1  |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    --- End of inner exception stack trace ---
backend_1  |    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
backend_1  |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
backend_1  |    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
backend_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
backend_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
backend_1  |    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
backend_1  |       Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
backend_1  |       Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
backend_1  |       Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://mydomain.com/.well-known/openid-configuration'.
backend_1  | info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[12]
backend_1  |       AuthenticationScheme: Bearer was challenged.
```

Any suggestions will be much appreciated.

**Note:** Currently I set `IdentityServerAuthentication > Authority` as `https://mydomain.com`

**Comment by RaiBnod** [comment]
`proxy_set_header Host $host;` was missing on my `NGINX` config.
