### ISSUE TITLE
Getting 'Unable to unprotect the message.State'

### ISSUE THREAD

**Issue by khawajaumarfarooq** [IdentityServer/IdentityServer4#5044]
### Question

The deployment scenario I am trying to enable is as follows:

* *Gateway* is the identity service that authenticates users
* *WebFrontend* is the UI service that serves content to authenticated users serving views/pages, both static as well as a React SPA
* *Backend* is the API service that has authenticated and unauthenticated resources, such as REST and GraphQL endpoints

### Minimal working example

I have a solution available in https://github.com/khawajaumarfarooq/Bakhtawar

To run the solution as configured,

* generate a CA certificate using the script `$/Scripts/generate-ca-certificate.sh`
* generate a localhost certificate using the script `$/Scripts/generate-localhost.certificate.sh`
* register the CA certificate in your machine's Trusted Root CA collection
* register the CA certificate in your browser's Trusted Root CA collection
* run `cat dev.json | dotnet user-secrets set` on Linux/macOS or `type dev.json | dotnet user-secrets set` on Windows in each of the projects for `Gateway`, `WebFrontend`, `Backend` and `Database`
* install PostgreSQL and create a user called `bakhtawar` with password `Bakhtawar123` owning an empty database `bakhtawar`
* run the `Database` project one time to create the necessary database tables

The scripts use `openssl` utility.

The script `generate-ca-certificate.sh` will generate a certificate called `huntingdonresearch.crt` under `~/Keys`.

* $ is the folder in which you have cloned the repository
* ~ is the home folder of your user account

The login on the `Gateway` itself works, but it doesn't complete the authentication process on the `Frontend`. The `state` parameter cannot be unprotected.

#### Problem

I have debugged it. The `WebFrontend` tried to unprotect is using the key-ring based data protector and that fails.

How do I configure this set up correctly? Any help would be greatly appreciated.

### Relevant parts of the log file

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Unable to unprotect the message.State.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by khawajaumarfarooq** [comment]
Bump
