### ISSUE TITLE
Key type not specified. when calling app.UseIdentityServer()

### ISSUE THREAD

**Issue by BjornEngelen** [IdentityServer/IdentityServer4#5055]
I'm using IdentityServer with Key management in the following fashion.

```
      services.AddIdentityServer()
                .AddApiAuthorization<User, MyDbContext>()
                .AddSigningKeyManagement(options =>
                {
                    options.KeyType = IdentityServer4.KeyManagement.KeyType.RSA;
                })
                .ProtectKeysWithDataProtection()
                .PersistKeysToDatabase(new DatabaseKeyManagementOptions
                {
                    ResolveDbContextOptions = (provider, builder) =>
                        builder.UseSqlServer(provider.GetRequiredService<SqlConnection>())
                })
                .EnableInMemoryCaching();
```

However, it still throws Key type not specified, when calling app.UseIdentityServer().
In the past, before using key management, I configured a key type 'file' in appsettings. But I don't see this in the samples.
Is something like this still necessary? Am I doing something wrong?

Relevant NuGets:
IdentityServer4.KeyManagement" Version=2.1.0
IdentityServer4.KeyManagement.EntityFramework" Version=2.1.0
Microsoft.AspNetCore.ApiAuthorization.IdentityServer Version=3.1.9
   
Stacktrace:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Key type not specified.
  Source=Microsoft.AspNetCore.ApiAuthorization.IdentityServer
  StackTrace:
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.LoadKey()
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.Configure(ApiAuthorizationOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderConfigurationExtensions.<>c.<AddClients>b__7_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.TestService(IServiceProvider serviceProvider, Type service, ILogger logger, String message, Boolean doThrow)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app, IdentityServerMiddlewareOptions options)
   at MyApp.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, UserManager`1 userManager, MyDbContext dataContext, ILog logger) in C:\DEV\EC\MyApp\MyApp\Startup.cs:line 134

  This exception was originally thrown at this call stack:
    [External Code]
    MyApp.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder, Microsoft.AspNetCore.Hosting.IWebHostEnvironment, Microsoft.AspNetCore.Identity.UserManager<MyApp.Domain.User>, MyApp.Data.MyDbContext, MyApp.Logging.ILog) in Startup.cs
```

**Comment by BjornEngelen** [comment]
> Do you have a call stack you can share?

I have added it to the original post

**Comment by brockallen** [comment]
Hmm, ok... I think you are mixing Microsoft's VS template extensions to IdentityServer (with `AddApiAuthorization`) and that's the issue. I don't think it's related to the `AddSigningKeyManagement`. 

Generally once you need to break out beyond Microsoft's template, we don't recommend that you stick with their abstractions (IOW, stop using their extension library).

**Comment by BjornEngelen** [comment]
Right, I already feared as much. I'll have to plan a more thorough rework then in the near future.
Thanks for taking a look, Brock.
