### ISSUE TITLE
System.InvalidOperationException: The path contains null characters.

### ISSUE THREAD

**Issue by jason-gardella-cko** [IdentityServer/IdentityServer4#5128]
### Question
I am creating this as a question instead of a bug as I'm not sure if it is intended behavior or not. We are using version 4.1.0, but I didn't see any changes related to this in the release notes for 4.1.1. 

We are seeing an `System.InvalidOperationException: The path contains null characters.` for calls to the `/connect/token` using the `client_credentials` grant type, resulting in a `500` response. I have investigated and it seems to be caused by the `client_secret` request parameter containing a null character; see the curl request to the demo API below for a reproduction of the behavior.

Is this intended behavior, and we should perform validation/catch this error in our application code, or should these null characters be handled by IdentityServer?
Related call in IdentityServer seems to be: https://github.com/IdentityServer/IdentityServer4/blob/45f8cb5d2215263528b6481ad9571729d7090c96/src/IdentityServer4/src/Validation/Default/PostBodySecretParser.cs#L60
It could also possible be a bug in ASP.NET core; it seems strange that the error message mentions a "path", as there is no path being parsed here.

And thank you for the great framework!

### Minimal working example
I was able to reproduce the behavior by calling the demo API:

```
curl -v -d "grant_type=client_credentials&client_id=test&client_secret=%00" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://demo.identityserver.io/connect/token
```

### Relevant parts of the log file

```
System.InvalidOperationException: The path contains null characters.
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeCore(Int32& sourceIndex, Int32& destinationIndex, Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeInPlace(Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.GetDecodedString(ReadOnlySpan`1 readOnlySpan)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at IdentityServer4.Validation.PostBodySecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.SecretParser.ParseAsync(HttpContext context)
   at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
```

**Comment by leastprivilege** [comment]
Telling from the stack trace, this seems to happen inside ASP.NET Core. Maybe open an issue with Microsoft?

**Comment by jason-gardella-cko** [comment]
Thanks for the quick response @leastprivilege.

I'm happy to open an issue in the ASP.NET Core repo and see if this is the intended behavior for this function. But is it correct to say from an IdentityServer perspective that this is not the intended behavior? To handle this exception gracefully from the application I believe would be non-straightforward, adding some additional middleware or something, and I would think this should be treated as a validation error with some 4XX response code instead of a 500. In any case we will learn more from the Microsoft issue.

**Comment by leastprivilege** [comment]
Well - if the underlying web platform throws - maybe there's a good reason for it...let's first see what Microsoft has to say.
