### ISSUE TITLE
Method not found when using reference tokens

### ISSUE THREAD

**Issue by TalismanicMind** [IdentityServer/IdentityServer4#5138]
### Question

Im stuck with the exception
 |url: https://localhost/api/account/login|action: Login
2021-01-22 22:57:07.2038||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|HandleAuthenticateAsync called |url: https://localhost/api/account/getusers|action: GetUsers
2021-01-22 22:57:07.2222||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Token found: 00A73A660B1F22D78C92F64BE4035AB25D98A075480766F9DF4CF6A4CDC33502 |url: https://localhost/api/account/getusers|action: GetUsers
2021-01-22 22:57:07.2342||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Token is a reference token and is supported. |url: https://localhost/api/account/getusers|action: GetUsers
2021-01-22 22:57:07.4007||ERROR|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'.
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.<>c__DisplayClass9_0.<CreateLazyIntrospection>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()|url: https://localhost/api/account/getusers|action: GetUsers

.NetCore 5

The log information you see at the bottom is from the proceeding flow using postman

=> send username and password to api, using client.RequestPasswordTokenAsync(), get a reference token back
=> check token is recognised by calling the connect/introspect endpoint (at first was recieving active: false)
=> call the authenticated method on Api, ends with 401 unauthorized

With everything being absolutely the same i will not get the above error message 
if i change AccessTokenType = AccessTokenType.Jwt and i will be able to authenticate with the api

from some fruitless googling assuming no oversights in the code, seems i may a faulty/outdated dll
i want the reference tokens so that i can revoke that, all help is appreciated

### Minimal working example

//-----IdentityServer Startup.cs-----------------------

   services.AddDbContext<AnthologyCtx>();

            services.AddIdentity<TenantUser, IdentityRole<int>>(o =>
            {
                o.SignIn.RequireConfirmedEmail = true;
                o.User.RequireUniqueEmail = false;
            })
            .AddEntityFrameworkStores<AnthologyCtx>()
            .AddDefaultTokenProviders();

            string connectionString = _configuration.GetValue<string>("localhost");
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            services.AddTransient<IProfileService, UserProfileService>();
            services.AddTransient<IHttpContextAccessor, HttpContextAccessor>();

            services.AddIdentityServer()
              .AddDeveloperSigningCredential()
              .AddConfigurationStore(options =>
              {
                  options.ConfigureDbContext = builder =>
                      builder.UseSqlServer(connectionString,
                          sql => sql.MigrationsAssembly(migrationsAssembly));
                  options.DefaultSchema = "IdentityServer";
              })
              .AddOperationalStore(options =>
              {
                  options.ConfigureDbContext = builder =>
                      builder.UseSqlServer(connectionString,
                          sql => sql.MigrationsAssembly(migrationsAssembly));

                  options.EnableTokenCleanup = true;
                  options.TokenCleanupInterval = 3600;
                  options.DefaultSchema = "IdentityServer";
              })
              .AddAspNetIdentity<TenantUser>()
              .AddResourceOwnerValidator<CustomResourceOwnerPasswordValidator>()
              .AddProfileService<UserProfileService>()
              .AddResponseGenerators();

            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy", corsBuilder =>
                {
                    corsBuilder
                        .SetIsOriginAllowedToAllowWildcardSubdomains()
                        .WithOrigins("https://*.localhost:4200", "https://localhost:4200", "http://*.localhost:4200", "http://localhost:4200")
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials();
                });
            });

            services.AddMvc();

//-----Identity Server Config.cs-----------------------
   public static string Api = "Anthology-Api";

        public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client()
                {
                    ClientId = "Angular",
                    ClientName = "Saas portal",
                    ClientSecrets=  new List<Secret>
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedGrantTypes =  GrantTypes.ResourceOwnerPassword,
                    AccessTokenType = AccessTokenType.Reference, //works if i change this to JWT with no other changes
                    AccessTokenLifetime = 60 * 10,
                    UpdateAccessTokenClaimsOnRefresh = true,
                    SlidingRefreshTokenLifetime = 30,
                    AllowOfflineAccess = true,
                    RefreshTokenExpiration = TokenExpiration.Absolute,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    AlwaysSendClientClaims = true,
                    AlwaysIncludeUserClaimsInIdToken = true,
                    Enabled = true,
                    AllowedScopes =
                    {
                        new IdentityResources.OpenId().Name,
                        new IdentityResources.Profile().Name,
                        new IdentityResources.Email().Name,
                        Api
                    },
                    RequireConsent = false
                }
            };
        }

        public static List<ApiResource> ApiResources = new List<ApiResource>()
        {
            new ApiResource
            {
                Name = Api,
                DisplayName = "Saas Api",
                ApiSecrets = new List<Secret>
                {
                    new Secret("secret".Sha256())
                },
                Scopes = new List<string>
                {
                    Api
                }
            }
        };

        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email()
            };
        }

        public static IEnumerable<ApiScope> GetApiScopes()
        {
            return new List<ApiScope>
            {
                new ApiScope(Api)
            };
        }

//--------------Resource Api Startup.cs-------------------

services.AddCors(options => {
                options.AddPolicy("CorsPolicy", corsBuilder => {
                    corsBuilder
                        .SetIsOriginAllowedToAllowWildcardSubdomains()
                        .WithOrigins(
                            "https://*.localhost:4200",
                            "https://localhost:4200",
                            "http://*.localhost:4200",
                            "http://localhost:4200")
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials();
                });
            });

            services.AddAuthentication(o =>
                {
                    o.DefaultScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme;
                    o.DefaultAuthenticateScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme;
                })
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Config.Authority;
                    options.RequireHttpsMetadata = false;
                    options.ApiName = Config.Api;
                    options.ApiSecret = "secret";
                    options.SupportedTokens= SupportedTokens.Both; 
                });

            services.AddAuthorization(o =>
                o.AddPolicy("DefaultPolicy", builder =>
                {
                    builder.RequireAuthenticatedUser();
                    builder.RequireClaim("scope", "Anthology-Api");
                }));

            services.AddDbContext<Anthology>();

            services.AddDbContext<UserCtx>();
            services.AddIdentity<TenantUser, IdentityRole<int>>(o =>
                {
                    o.SignIn.RequireConfirmedEmail = true;
                    o.User.RequireUniqueEmail = true;
                })
                .AddEntityFrameworkStores<UserCtx>()
                .AddDefaultTokenProviders();

            services.AddHttpContextAccessor();
            services.AddHttpClient();
           

            services.AddControllers()
                .AddNewtonsoftJson(opt => opt.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore);

//------------Resource APi Auth controller-----------------------------

 [Route("api/[controller]/[action]")]
    [ApiController]
    [Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme, Policy = "DefaultPolicy")]
    public class AccountController : Controller

    //authorizes if i use JWT stops authorizing if i switch to Reference
	public async Task<IActionResult> GetUsers()
        {
            var users = await _userManager.Users.ToListAsync();
            return Ok(users.Select(o => o.Email).ToList());
        }
	

//--------------Api Token Request-------------------

DiscoveryDocumentResponse discoveryDocument = await client.GetDiscoveryDocumentAsync(Config.Authority);
            var response = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = discoveryDocument.TokenEndpoint,
                ClientId = "Angular",
                ClientSecret = "secret",
                Scope = "openid email profile Anthology-Api offline_access",
                //Scope = "Anthology-Api",
                UserName = email,
                Password = password
            });

### Relevant parts of the log file

//----------------------Api log file

2021-01-22 22:56:28.1679|2|INFO|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Executed action method Api.Controllers.AccountController.Login (Api), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 7957.9029ms. 
2021-01-22 22:56:28.1746|2|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Action Filter: Before executing OnActionExecuted on filter Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter. 
2021-01-22 22:56:28.1746|3|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Action Filter: After executing OnActionExecuted on filter Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter. 
2021-01-22 22:56:28.1874|2|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Action Filter: Before executing OnActionExecuted on filter Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter. 
2021-01-22 22:56:28.1874|3|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Action Filter: After executing OnActionExecuted on filter Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter. 
2021-01-22 22:56:28.2017|3|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Action Filter: After executing OnActionExecutionAsync on filter Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter. 
2021-01-22 22:56:28.2017|2|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Result Filter: Before executing OnResultExecuting on filter Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter. 
2021-01-22 22:56:28.2182|3|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Result Filter: After executing OnResultExecuting on filter Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter. 
2021-01-22 22:56:28.2182|4|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Before executing action result Microsoft.AspNetCore.Mvc.OkObjectResult. 
2021-01-22 22:56:28.2346|11|DEBUG|Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector|List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
2021-01-22 22:56:28.2346|4|DEBUG|Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector|No information found on request to perform content negotiation. 
2021-01-22 22:56:28.2499|8|DEBUG|Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector|Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2021-01-22 22:56:28.2499|10|DEBUG|Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector|Attempting to select the first formatter in the output formatters list which can write the result. 
2021-01-22 22:56:28.2643|2|DEBUG|Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector|Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
2021-01-22 22:56:28.2643|1|INFO|Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor|Executing OkObjectResult, writing value of type 'IdentityModel.Client.TokenResponse'. 
2021-01-22 22:56:28.4185|5|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|After executing action result Microsoft.AspNetCore.Mvc.OkObjectResult. 
2021-01-22 22:56:28.4256|2|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Result Filter: Before executing OnResultExecuted on filter Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter. 
2021-01-22 22:56:28.4256|3|TRACE|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Result Filter: After executing OnResultExecuted on filter Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter. 
2021-01-22 22:56:28.4447|2|INFO|Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker|Executed action Api.Controllers.AccountController.Login (Api) in 8482.3458ms 
2021-01-22 22:56:28.4518|1|INFO|Microsoft.AspNetCore.Routing.EndpointMiddleware|Executed endpoint 'Api.Controllers.AccountController.Login (Api)' 
2021-01-22 22:56:28.4518|9|DEBUG|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HM5V53N96HIA" completed keep alive response. 
2021-01-22 22:56:28.4713|2|INFO|Microsoft.AspNetCore.Hosting.Diagnostics|Request finished HTTP/1.1 GET https://localhost:6000/api/account/login?email=king@labelstar.com&password=sdes16%23md5Kpub - - - 200 2166 application/json;+charset=utf-8 8716.8973ms 
2021-01-22 22:57:07.1501|1|INFO|Microsoft.AspNetCore.Hosting.Diagnostics|Request starting HTTP/1.1 GET https://localhost:6000/api/account/getusers - - 
2021-01-22 22:57:07.1585|2|TRACE|Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware|All hosts are allowed. 
2021-01-22 22:57:07.1585|4|DEBUG|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|The request path /api/account/getusers does not match a supported file type 
2021-01-22 22:57:07.1747|3|DEBUG|Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware|The request path  does not match the path filter 
2021-01-22 22:57:07.1747|1001|DEBUG|Microsoft.AspNetCore.Routing.Matching.DfaMatcher|1 candidate(s) found for the request path '/api/account/getusers' 
2021-01-22 22:57:07.1897|1005|DEBUG|Microsoft.AspNetCore.Routing.Matching.DfaMatcher|Endpoint 'Api.Controllers.AccountController.GetUsers (Api)' with route pattern 'api/Account/GetUsers' is valid for the request path '/api/account/getusers' 
2021-01-22 22:57:07.1897|1|DEBUG|Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware|Request matched endpoint 'Api.Controllers.AccountController.GetUsers (Api)' 
2021-01-22 22:57:07.2038|9|DEBUG|Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler|AuthenticationScheme: Identity.Application was not authenticated. 
2021-01-22 22:57:07.2038||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|HandleAuthenticateAsync called 
2021-01-22 22:57:07.2222||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Token found: 00A73A660B1F22D78C92F64BE4035AB25D98A075480766F9DF4CF6A4CDC33502 
2021-01-22 22:57:07.2342||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Token is a reference token and is supported. 
2021-01-22 22:57:07.4007||ERROR|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'.
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.<>c__DisplayClass9_0.<CreateLazyIntrospection>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
2021-01-22 22:57:07.4133|7|INFO|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Bearer was not authenticated. Failure message: Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'. 
2021-01-22 22:57:07.4287|2|INFO|Microsoft.AspNetCore.Authorization.DefaultAuthorizationService|Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
ClaimsAuthorizationRequirement:Claim.Type=scope and Claim.Value is one of the following values: (Anthology-Api) 
2021-01-22 22:57:07.4460||TRACE|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|Forwarding challenge to scheme: BearerIdentityServerAuthenticationIntrospection 
2021-01-22 22:57:07.4570|12|INFO|IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler|AuthenticationScheme: BearerIdentityServerAuthenticationIntrospection was challenged. 
2021-01-22 22:57:07.4682|12|INFO|IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler|AuthenticationScheme: Bearer was challenged. 
2021-01-22 22:57:07.4682|9|DEBUG|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HM5V53N96HIA" completed keep alive response. 
2021-01-22 22:57:07.4865|2|INFO|Microsoft.AspNetCore.Hosting.Diagnostics|Request finished HTTP/1.1 GET https://localhost:6000/api/account/getusers - - - 401 0 - 336.5739ms 

//-------------Identity Server Log file
2021-01-22 22:56:54.1722|20300|DEBUG|Microsoft.EntityFrameworkCore.Database.Command|A data reader was disposed. 
2021-01-22 22:56:54.1857|20002|DEBUG|Microsoft.EntityFrameworkCore.Database.Connection|Closing connection to database 'Anthology' on server 'localhost'. 
2021-01-22 22:56:54.1857|20003|DEBUG|Microsoft.EntityFrameworkCore.Database.Connection|Closed connection to database 'Anthology' on server 'localhost'. 
2021-01-22 22:56:54.1857||DEBUG|IdentityServer4.EntityFramework.Stores.ClientStore|Angular found in database: True 
2021-01-22 22:56:54.2104||TRACE|IdentityServer4.Stores.ValidatingClientStore|Calling into client configuration validator: IdentityServer4.Validation.DefaultClientConfigurationValidator 
2021-01-22 22:56:54.2218||DEBUG|IdentityServer4.Stores.ValidatingClientStore|client configuration validation for client Angular succeeded. 
2021-01-22 22:56:54.2396||DEBUG|IdentityServer4.Validation.TokenValidator|Calling into custom token validator: IdentityServer4.Validation.DefaultCustomTokenValidator 
2021-01-22 22:56:54.2549||DEBUG|IdentityServer4.Validation.TokenValidator|Token validation success
{"ValidateLifetime":true, "AccessTokenType":"Reference", "TokenHandle":"22B0ACB0BF1B7CBF76CCC40006A8BEB886AF1F37B3983C9242DD3005A883720B", "Claims":{"iss":"https:\/\/localhost:5001","nbf":1611356187,"exp":1611356787,"aud":"Anthology-Api","client_id":"Angular","scope":["Anthology-Api","email","openid","profile","offline_access"],"sub":"4","auth_time":1611356187,"idp":"local","amr":"pwd","username":"king","email":"kinglabelstar.com","TenantId":"1","jti":"2B86E9C3E7E7DE18470867A66742D0FC","iat":1611356187}} 
2021-01-22 22:56:54.2692||DEBUG|IdentityServer4.Validation.IntrospectionRequestValidator|Introspection request validation successful. 
2021-01-22 22:56:54.2810||TRACE|IdentityServer4.Endpoints.IntrospectionEndpoint|Calling into introspection response generator: IdentityServer4.ResponseHandling.IntrospectionResponseGenerator 
2021-01-22 22:56:54.2810||TRACE|IdentityServer4.ResponseHandling.IntrospectionResponseGenerator|Creating introspection response 
2021-01-22 22:56:54.3076||DEBUG|IdentityServer4.ResponseHandling.IntrospectionResponseGenerator|Creating introspection response for active token. 
2021-01-22 22:56:54.3211||INFO|IdentityServer4.Endpoints.IntrospectionEndpoint|Success token introspection. Token active: True, for API name: Anthology-Api 
2021-01-22 22:56:54.3339||TRACE|IdentityServer4.Hosting.IdentityServerMiddleware|Invoking result: IdentityServer4.Endpoints.Results.IntrospectionResult 
2021-01-22 22:56:54.3460|9|DEBUG|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HM5V53NSCHKH" completed keep alive response. 
2021-01-22 22:56:54.3460|10407|DEBUG|Microsoft.EntityFrameworkCore.Infrastructure|'PersistedGrantDbContext' disposed. 
2021-01-22 22:56:54.3596|10407|DEBUG|Microsoft.EntityFrameworkCore.Infrastructure|'ConfigurationDbContext' disposed. 
2021-01-22 22:56:54.3596|2|INFO|Microsoft.AspNetCore.Hosting.Diagnostics|Request finished HTTP/1.1 POST https://localhost:5001/connect/introspect application/x-www-form-urlencoded 70 - 200 - application/json;+charset=UTF-8 2407.4129ms

**Comment by leastprivilege** [comment]
Couple of things

a) we do not recommend using the `IdentityServerAuthenticationHandler` anymore. It is deprecated. See here for a better approach 

https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/

b) you seem to have upgraded IdentityModel to v5. There are some breaking changes, and that's why the old handler is not working anymore...

c) I would recommend you replace the authN handler as described above. I also published a preview of the new Introspection handler that is compatible with IdentityModel v5 

https://www.nuget.org/packages/IdentityModel.AspNetCore.OAuth2Introspection/5.0.0-preview.2

..or revert the upgrade to IdentityMode to v5, what I think got you into the situation in the first place...

**Comment by TalismanicMind** [comment]
Thank you so much
