### ISSUE TITLE
Device Flow: OnStarting cannot be set because the response has already started

### ISSUE THREAD

**Issue by DapperDeer** [IdentityServer/IdentityServer4#5145]
Hi there,

I'm trying to incorporate IdentityServer4 with my Blazor-Server application. For the most part, things have worked well up to this point. I'm using the [Device Flow Sample App](https://github.com/leastprivilege/AspNetCoreSecuritySamples/tree/aspnetcore21/DeviceFlow) for testing and am able to send an auth request, receive the User Code, input that code, and review the permissions. Once I review the permissions, check the ones I want and hit "Yes, allow," my Blazor-Server app spits out:

```
System.InvalidOperationException: OnStarting cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.OnStarting(Func`2 callback, Object state)
   at Microsoft.AspNetCore.Http.HttpResponse.OnStarting(Func`1 callback)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.InitializeHandlerAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at IdentityServer4.Hosting.FederatedSignOut.FederatedSignoutAuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at IdentityServer4.Services.DefaultUserSession.AuthenticateAsync()
   at IdentityServer4.Services.DefaultUserSession.GetUserAsync()
   at IdentityServer4.Services.DefaultDeviceFlowInteractionService.HandleRequestAsync(String userCode, ConsentResponse consent)
   at Delos.API.ConsentController.ProcessGrantedConsent(DeviceInquiry device) in C:\Users\SG102983\Documents\Work\vertex\Delos\src\API\ConsentController.cs:line 174
   at Delos.Pages.Device.PermissionConfirmation.<BuildRenderTree>b__0_4() in C:\Users\SG102983\Documents\Work\vertex\Delos\src\Pages\Device\PermissionConfirmation.razor:line 89
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

ConsentController.cs:145-179:
```csharp
if (device.ScopesConsented != null && device.ScopesConsented.Any())
			{
				var scopes = device.ScopesConsented;
				if (ConsentOptions.EnableOfflineAccess == false)
				{
					scopes = scopes.Where(x => x != IdentityServerConstants.StandardScopes.OfflineAccess);
				}

				grantedConsent = new ConsentResponse {
					RememberConsent = device.RememberConsent,
					ScopesValuesConsented = scopes.ToArray(),
					Description = device.Description
				};

				var user = this._httpContextAccessor.HttpContext.User; // Blazor replacement for this.User.GetSubjectId();
				await this._events.RaiseAsync(
						new ConsentGrantedEvent(
							user.GetSubjectId(),
							request.Client.ClientId,
							request.ValidatedResources.RawScopeValues,
							grantedConsent.ScopesValuesConsented,
							grantedConsent.RememberConsent));
			}
			else
			{
				result.ValidationError = ConsentOptions.MustChooseOneErrorMessage;
			}

			if (grantedConsent != null)
			{
				await this._interaction.HandleRequestAsync(device.UserCode, grantedConsent); // This is the calling function that ends up erroring out.

				result.RedirectUri = device.ReturnUrl;
				result.Client = request.Client;
			}
```

I have a feeling that it's related to the Blazor-Server infrastructure compared to MVC where the QuickStart UI works perfectly, but I'm not 100% sure.

Thanks

**Comment by brockallen** [comment]
What other middleware is in your pipeline?

**Comment by DapperDeer** [comment]
Inexperienced dev here, so I may be missing something, but I don't think that we actually have much middleware. We're using MSAL for Login/Logout, with a scaffolded SQLite DB. 

Here are snippets from my Services.ConfigureServices method:

```csharp
services.AddDbContext<ApplicationDbContext>(options => options.UseSqlite(connectionString));
			services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
				.AddRoles<IdentityRole>()
				.AddEntityFrameworkStores<ApplicationDbContext>();
// Controller DI

services.AddAuthentication()
				.AddGoogle(options =>
				{
					var googleAuthNSection = this.Configuration.GetSection("Authentication:Google");

					options.ClientId = googleAuthNSection["ClientId"];
					options.ClientSecret = googleAuthNSection["ClientSecret"];
				});
			services.AddIdentityServer()
				.AddAspNetIdentity<IdentityUser>()
				.AddDeveloperSigningCredential()
				.AddConfigurationStore(options => {
					options.ConfigureDbContext = builder => builder.UseSqlite(connectionString,
						opt => opt.MigrationsAssembly(migrationsAssembly));
				})
				.AddOperationalStore(options => {
					options.ConfigureDbContext = builder => builder.UseSqlite(connectionString,
						opt => opt.MigrationsAssembly(migrationsAssembly));
					options.EnableTokenCleanup = true;
				});
			services.AddControllersWithViews();
			services.AddHttpContextAccessor();
			services.AddApiVersioning(config =>
			{
				config.DefaultApiVersion = new ApiVersion(1, 0);
				config.AssumeDefaultVersionWhenUnspecified = true;
				config.ReportApiVersions = true;
			});
			services.AddRazorPages();
			services.AddServerSideBlazor().AddCircuitOptions(options => { options.DetailedErrors = true; });
			services.AddBlazorTable();
```

**Comment by brockallen** [comment]
Middleware is registered in the `Configure` method, so that will help to see.

**Comment by DapperDeer** [comment]
Got it, sorry about that.

`Startup.Configure`:
```csharp

			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
				app.UseDatabaseErrorPage();
			}
			else
			{
				app.UseExceptionHandler("/Error");
				// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
				app.UseHsts();
			}

			app.UseHttpsRedirection();
			app.UseStaticFiles();

			app.UseRouting();

			app.UseIdentityServer();
			app.UseAuthorization();

			app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllers();
				endpoints.MapBlazorHub();
				endpoints.MapFallbackToPage("/_Host");
			});
```

**Comment by brockallen** [comment]
Nothing stand out.
