### ISSUE TITLE
Token endpoint throwing 404

### ISSUE THREAD

**Issue by Kratos-og** [IdentityServer/IdentityServer4#5173]
I'm facing an issue with my current implementation of Identity Server 4.

I have a js client and I'm using oidc-client for authentication on the front-end with "code" as the grant type, I'm able to get the code back and also being redirected to my app, but fails in the following step.
` mgr.processSigninResponse(window.location.href).then(function () {
        window.location = "/";
    }).catch(function (e) {
       console.log(e)
    });`
Apparently, it works fine when I'm using Azure ad as auth provider but fails with Okta, google and basic ASP.NET Identity. The request to /connect/token endpoint fails and throws 404 when trying to fetch the access token and hence results in a redirect-loop. Adding IS4 startup below.

`var builder = services.AddIdentityServer()
        .AddMongoRepository()
        .AddClients()
        .AddIdentityApiResources()
        .AddPersistedGrants()
        .AddDeveloperSigningCredential()
        .AddProfileService<MyProfileService>();
 services.AddAuthentication()
            .AddGoogle("Google", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.ClientId = Configuration.GetValue<string>("Google:ClientId");
                options.ClientSecret = Configuration.GetValue<string>("Google:ClientSecret");
            })
            .AddOpenIdConnect("aad", "Azure AD", options =>
             {
                 options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                 options.SignOutScheme = IdentityServerConstants.SignoutScheme;

                 options.Authority = Configuration.GetValue<string>("AzureAD:Authority");
                 options.ClientId = Configuration.GetValue<string>("AzureAD:ClientId");
                 options.ClientSecret = Configuration.GetValue<string>("AzureAD:ClientSecret");
                 options.ResponseType = OpenIdConnectResponseType.IdToken;
                 options.GetClaimsFromUserInfoEndpoint = true;
                 options.Scope.Add("openid");
                 options.Scope.Add("profile");
                 options.TokenValidationParameters = new TokenValidationParameters
                 {
                     NameClaimType = "name",
                     RoleClaimType = "role"
                 };
             })
            .AddOpenIdConnect("okta","Okta",options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                
                options.Authority = Configuration.GetValue<string>("Okta:Authority") + "/oauth2/default";
                options.ClientId = Configuration.GetValue<string>("Okta:ClientId");
                options.ClientSecret = Configuration.GetValue<string>("Okta:ClientSecret");
                options.ResponseType = OpenIdConnectResponseType.IdToken;
                options.GetClaimsFromUserInfoEndpoint = true;
                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.CallbackPath = "/signin-oidc-okta";
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "groups",
                };
            });`

**Comment by Kratos-og** [comment]
Looking at the logs, there's an unhandled exception which doesn't give much info. Attaching it here for reference.

` Unhandled exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer4.Services.DefaultClaimsService.<>c.<FilterProtocolClaims>b__7_0(Claim x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at IdentityServer4.Services.DefaultClaimsService.FilterProtocolClaims(IEnumerable`1 claims)
   at IdentityServer4.Services.DefaultClaimsService.GetAccessTokenClaimsAsync(ClaimsPrincipal subject, ResourceValidationResult resourceResult, ValidatedRequest request)
   at IdentityServer4.Services.DefaultTokenService.CreateAccessTokenAsync(TokenCreationRequest request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.CreateAccessTokenAsync(ValidatedTokenRequest request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAuthorizationCodeRequestAsync(TokenRequestValidationResult request)
   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)
   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)`

[idsvr.txt](https://github.com/IdentityServer/IdentityServer4/files/6077043/idsvr.txt)

**Comment by Kratos-og** [comment]
Turns out it was an issue because of ProfileService which I had for getting user claims. Azure AD and Okta were returning claims with different keys and hence was setting null in some cases.
