### ISSUE TITLE
IDX20803 Error when using Identity Server 4 on Linux Docker containers

### ISSUE THREAD

**Issue by BradRaynaudCIC** [IdentityServer/IdentityServer4#5194]
### Question
I am encountering an IDX20803 error when I try to deploy our .NET 5 Angular application to a docker container. We have been able to successfully deploy the code locally and on Azure without any authentication issues. However, when we deploy that same code inside a docker container we get the following error: 

```
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[7]
Bearer was not authenticated. Failure message: IDX20803: Unable to obtain configuration from: 'https://localhost/.well-known/openid-configuration'.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
ClaimsAuthorizationRequirement:Claim.Type=permission and Claim.Value is one of the following values: (roles.view)
trce: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
Forwarding challenge to scheme: BearerIdentityServerAuthenticationJwt
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[12]
AuthenticationScheme: BearerIdentityServerAuthenticationJwt was challenged.
info: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[12]
```
When the container is running we are able to resolve the website "https://localhost/.well-known/openid-configuration" and view the openid-configuration. 

My current idea is that "options.authority" is being set such that I am able to access the openid-configuration externally, but that same configuration is somehow blocking access internally. 

Any Ideas?

### Minimal working example
**Dockerfile**
```csharp
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
WORKDIR /src

COPY ["DAL/DAL.csproj", "DAL/"]
COPY ["QuickApp/QuickApp.csproj", "QuickApp/"]
RUN dotnet restore "QuickApp/QuickApp.csproj"
COPY . .
WORKDIR "/src/QuickApp"
RUN dotnet build "QuickApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "QuickApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app



COPY --from=publish /app/publish .
COPY ["QuickApp/Assets", "Assets"]
COPY ["QuickApp/ClientApp", "ClientApp"]
RUN cd ClientApp && npm install

ADD conf.d/localhost.crt /usr/local/share/ca-certificates/localhost.crt
RUN chmod 644 /usr/local/share/ca-certificates/localhost.crt && update-ca-certificates

ENTRYPOINT ["dotnet", "QuickApp.dll"]
```

**Docker-Compose**
```csharp
services:
  quickapp:
    user: root
    image: quickapp
    build:
      context: .
      dockerfile: QuickApp/Dockerfile
    environment:
      - WEB_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/localhost.key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.crt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/https:ro
```

**Authentication Configuration**
```csharp
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = applicationUrl; // Set to "https://localhost"
                    options.SupportedTokens = SupportedTokens.Jwt;
                    options.RequireHttpsMetadata = false; 
                    options.ApiName = IdentityServerConfig.ApiName;
                });
```

Note: I am creating this issue here per direction of the aspnetcore issue I created.
https://github.com/dotnet/aspnetcore/issues/30942

**Comment by BradRaynaudCIC** [comment]
Figured out the issue.

I had to add this to my .AddIdentityServerAuthentication
```
options.JwtBackChannelHandler = GetHandler();
```
```
private static HttpClientHandler GetHandler()
        {
            var handler = new HttpClientHandler();
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            handler.SslProtocols = SslProtocols.Tls12;         
            handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true;
            return handler;
        }
```
