### ISSUE TITLE
An error was encountered while handling the remote login, POST requests are not supported,  No candidates found for the request path '/signin-oidc'

### ISSUE THREAD

**Issue by ahmed-i-badawi** [IdentityServer/IdentityServer4#5458]
when i login to admin ui after user is authorized i got following log
Note:
Issue happens only when running on docker using ngnix

<<<-------------------------------------------------------->>>

AuthenticationScheme: Cookies signed in.

[15:14:59 INF] Request finished HTTP/1.0 POST http://{ip}/signin-oidc application/x-www-form-urlencoded 590 - 302 0 - 540.6799ms

[15:14:59 DBG] Connection id "0HMHS0NA62L58" disconnecting.

[15:14:59 DBG] Connection id "0HMHS0NA62L58" stopped.

[15:14:59 DBG] Connection id "0HMHS0NA62L58" sending FIN because: "The Socket transport's send loop completed gracefully."

[15:15:01 DBG] Connection id "0HMHS0NA62L59" accepted.

[15:15:01 DBG] Connection id "0HMHS0NA62L59" started.

[15:15:01 INF] Request starting HTTP/1.0 GET http://{ip}/signin-oidc - -

[15:15:01 DBG] The request path /signin-oidc does not match a supported file type

[15:15:01 DBG] No candidates found for the request path '/signin-oidc'

[15:15:01 DBG] Request did not match any endpoints

[15:15:01 WRN] .AspNetCore.Correlation. state property not found.

[15:15:01 INF] Error from RemoteAuthentication: Correlation failed..

[15:15:01 ERR] An unhandled exception has occurred while executing the request.

System.Exception: An error was encountered while handling the remote login.

---> System.Exception: Correlation failed.

   --- End of inner exception stack trace ---

   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

[15:15:01 INF] Request finished HTTP/1.0 GET http://{ip}/signin-oidc - - - 500 - text/html;+charset=utf-8 38.5731ms

[15:15:01 DBG] Connection id "0HMHS0NA62L59" disconnecting.

[15:15:01 DBG] Connection id "0HMHS0NA62L59" stopped.

[15:15:01 DBG] Connection id "0HMHS0NA62L59" sending FIN because: "The Socket transport's send loop completed gracefully."

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
