### ISSUE TITLE
Do temporary certificates work on Windows 2008 RC 2/ IIS7.5

### ISSUE THREAD

**Issue by ninagran** [IdentityServer/IdentityServer4#602]
I have IdSrv4 working on Windows 2012 R2 IIS8.5 with SetTemporarySigningCredential . I transferred to Windows 2008 RC2 IIS7.5. Now  I'm able to bring up the IdSrv app and access the discovery endpoint just fine but when I try the signing endpoint at .../jwks I'm getting this error:

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Object was not found
   at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize)
   at System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle()
   at System.Security.Cryptography.RSAImplementation.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSAImplementation.RSACng.ExportParameters(Boolean includePrivateParameters)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ExecuteJwksAsync>d__10.MoveNext()

**Comment by leastprivilege** [comment]
Never tried it on that platform.

**Comment by ninagran** [comment]
.NET Core

**Comment by leastprivilege** [comment]
Not sure what platform they are using on Azure Web Apps - but both temp credentials and X509 works fine there.

Closing for now - feel free to re-open when you have more issues
