### ISSUE TITLE
Creating and validating JWT with symmetric key (hs256)

### ISSUE THREAD

**Issue by cYCL157** [IdentityServer/IdentityServer4#61]
I would like to move to using IdSvr4 for auth services for a set of existing services that are currently using HS256 signed JWTs and don't feel that I can change that signing model immediately until all of the services are updated to get and validate tokens for IdSvr.  

I have been able to implement classes for ITokenSigningService and ITokenValidator and am able to issue a token that I can use with the other existing services (not in .net) but am having a problem getting the middleware setup in my c# api to be able to validate the JWT -- I get an exception saying either:

fail: Microsoft.AspNet.Authentication.JwtBearer.JwtBearerMiddleware[0]
      Exception occurred while processing message
      System.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. There are no security keys to use to validate the signature
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)

OR:

fail: Microsoft.AspNet.Authentication.JwtBearer.JwtBearerMiddleware[0]
      Exception occurred while processing message
      System.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.X509SecurityKey , KeyId: a3rMUgMFv9tPclLa6yF3zAkfquE
      '.
Exceptions caught:
 'System.ArgumentException: IDX10640: Algorithm is not supported: 'HS256'.
         at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures)
         at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
         at System.IdentityModel.Tokens.SignatureProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
         at System.IdentityModel.Tokens.X509SecurityKey.GetSignatureProvider(String algorithm, Boolean verifyOnly)
         at System.IdentityModel.Tokens.SecurityKey.GetSignatureProviderForValidating(String algorithm)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)

depending on whether or not I have a SigningCertificate setup.

I started with an example that was using a SigningCertificate and was able to validate that I had the server and my api all setup to connect properly and to see that things did work.

I am not seeing any calls made to IdSvr in the log, so I am thinking that there needs to be something registered on the api side to know how to validate my "custom" token signature -- but not what I was expecting.  

I am sure I am missing something -- just need a helpful nudge in the right direction.  Please :)

**Comment by leastprivilege** [comment]
The main signing key needs to be asymmetric.
