### ISSUE TITLE
Authorized Access Token Always Expired

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#730]
I've had Idsvr4 and MVC client portal, I used Microsoft.AspNetCore.Authentication.OpenIdConnect to do the oidc. I ran into an weird issue is below:
After login and the authorize finished, the page would keep loading and could not redirect to the "http://clientportal/signin-oidc". Eventually it would show the "504 Gateway Time-out" page.

No error log in Idsvr side, the client portal side's log is:

fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[17]
Exception occurred while processing message.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '01/22/2017 01:00:59'
Current time: '01/22/2017 01:05:59'.
at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable1 notBefore, Nullable1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable1 notBefore, Nullable1 expires, JwtSecurityToken securityToken, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.d__20.MoveNext()
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[4]
Error from RemoteAuthentication: IDX10223: Lifetime validation failed. The token is expired.
ValidTo: '01/22/2017 01:00:59'
Current time: '01/22/2017 01:05:59'..

**Comment by leastprivilege** [comment]
Probably a clock mismatch between token issuer and consumer

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by atpyk** [comment]
@leastprivilege it's the issue from .net core 1.1.0. I have worked aroundit
[1121](https://github.com/aspnet/Security/issues/1121)
