### ISSUE TITLE
Update System.IdentityModel.Tokens.Jwt to 5.0.0-rc1-211161024

### ISSUE THREAD

**Issue by giggio** [IdentityServer/IdentityServer4#8]
You are depending on two different versions of this dependency (`5.0.0-rc1-211161024` for .NET Core and `4.0.2.202250711` for .NET 4.5.1) and this is causing conflicts.
I have noticed that most APIs on ASPNET5 RC1 are on v5. You should try to use only that version.

**Comment by giggio** [comment]
BTW, bellow you can find the error I am getting when running on .NET 4.5.1. It works perfectly with .NET Core (`dnxcore50`). I am assuming the version difference on `System.IdentityModel.Tokens.Jwt` to be the problem.

````
=> RequestId:0HKOT6M4ABETF RequestPath:/connect/authorize
      An unhandled exception has occurred while executing the request
      System.TypeLoadException: Could not load type 'System.IdentityModel.Tokens.Serializer' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.112, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
         at IdentityServer4.Core.Services.Default.DefaultTokenSigningService..cctor()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
         at IdentityServer4.Core.Hosting.EndpointRouter.Find(HttpContext context)
         at IdentityServer4.Core.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Core.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
````

**Comment by leastprivilege** [comment]
We can't do that right now because of a bug in the v5 version. We will at RC2.

**Comment by giggio** [comment]
Ok.
Do you have a workaround for this specific problem I just posted om the error log?

**Comment by leastprivilege** [comment]
Not sure what your problem is, works for us.

**Comment by giggio** [comment]
The conflict came from using `Microsoft.AspNet.Authentication.OpenIdConnect` version `1.0.0-rc1-final` on the same host. After removing, the problem was solved. I think it is using version 5 of `System.IdentityModel.Tokens.Jwt` and that is conflicting. I have solved the conflict, but this is still an issue. Let's wait for RC2, then.

**Comment by margagn** [comment]
I am having the exact same issue. Is there something we can do to get unblocked?

**Comment by giggio** [comment]
@leastprivilege I see that `System.IdentityModel.Tokens.Jwt` is still in different versions on the [latest project.json](https://github.com/IdentityServer/IdentityServer4/blob/076197f51322649ec1d62f3d2e2c21f3c8fbad49/src/IdentityServer4/project.json). This was closed as not going to be fixed, or is it being fixed some other way?

**Comment by leastprivilege** [comment]
Quoting my above answer

> We can't do that right now because of a bug in the v5 version. We will at RC2.

**Comment by giggio** [comment]
If the bug is not fixed, the issue shouldn't be closed. This is unexpected behavior, it is an open bug.

**Comment by leastprivilege** [comment]
There is an open todo issue for upgrading to the new jwt library. Feel free to re open if that helps.

**Comment by giggio** [comment]
#27, right? I assume that that will fix this one, so I will follow that one. Tks.

**Comment by leastprivilege** [comment]
this one

https://github.com/IdentityServer/IdentityServer4/issues/24

**Comment by alzdrak** [comment]
I have the same situation with having a client (webapi) and host in the same project. The problem was that package`"Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final"` uses `System.IdentityModel.Tokens.Jwt (5.0.0-rc1-211161024)` whereas `"IdentityServer4": "1.0.0-beta1"` depends on `"System.IdentityModel.Tokens.Jwt": "4.0.2.202250711"` like giggio said.

So I set a dependency for 4.0 in my project and load the JwtBearer package normally like so: 

```
"dependencies": {
   ...
   "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
   ...
},
"frameworks": {
    "dnx46": { 
      "dependencies": {
        "System.IdentityModel.Tokens.Jwt": "4.0.2.202250711"
      }
    }
  },
```

However, I am not able to call this in my Startup.cs:

`System.IdentityModel.Tokens.JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();`

Since `DefaultInboundClaimTypeMap` does not exists. 

What would be a workaround for this?

**Comment by leastprivilege** [comment]
yes - you have to wait for RC2 for this to get fixed.

**Comment by mmulhearn** [comment]
First, this is still an issue.  We're at 1.5 years on this one...

Also, I was able to downgrade to System.IdentityModel.Tokens.Jwt 4.0.4.403061554 and that seems to be working.

**Comment by parouuu** [comment]
@mmulhearn thanks you saved me.
