### ISSUE TITLE
Error while calling GetAsync method of DiscoveryClient

### ISSUE THREAD

**Issue by muffadal53** [IdentityServer/IdentityServer4#925]
Hi,

We have to two identity server setup of different machines as below.
1. https://IdentitySvr1:44333/IdentityServer4
2. https://IdentitySvr2:53535/IdentityServer4

I want to validate token issued by IdentitySvr2 using IdentitySvr1. So, I am using "AddValidationKeys" method to add keyId issued by IdentitySvr2 in list of keys of IdentitySvr1. To achieve this I have created DiscoveryClient object by passing authority value as url of other identity server i.e. "https://IdentitySvr2:53535/IdentityServer4".
Now when I call GetAsync() method to get JsonWebKey of IdentitySvr2, I get following error. Any idea why I am getting this error.

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at System.Net.Http.WinHttpHandler.d__105.MoveNext()

Thanks.

**Comment by leastprivilege** [comment]
Well - that exception doesn't tell us anything about the real reason.

**Comment by muffadal53** [comment]
Hi Dominick,

To provide more details I have pasted the code and error details for the same.

Code: var discoveryClient = new DiscoveryClient(baseUrl);
          **var doc = await discoveryClient.GetAsync();**
          RsaSecurityKey rsaSecurityKey = null;
          if (doc.KeySet != null && doc.KeySet.Keys.Count > 0)
          {
             var rsa = RSA.Create();
             rsaSecurityKey = new RsaSecurityKey(rsa);
             var jsonWebKey = doc.KeySet.Keys[0].Kid;
             rsaSecurityKey.KeyId = jsonWebKey;
      }
      return rsaSecurityKey;

Error in doc mentioned below:

Error: Error connecting to https://IdentitySvr2:53535/IdentityServer4/.well-known/openid-configuration: An error occurred while sending the request.

Exception:
  System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.Client.DiscoveryClient.<GetAsync>d__15.MoveNext()

Stack Trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

Thanks.

**Comment by leastprivilege** [comment]
> System.Net.Http.WinHttpException: A security error occurred

Sounds to me like an HTTPS problem.

-------
Dominick Baier

On 16 March 2017 at 07:25:28, muffadal53 (notifications@github.com) wrote:

System.Net.Http.WinHttpException: A security error occurred

**Comment by muffadal53** [comment]
Hi Dominick,

We also tried by setting discoveryClient.Policy.RequireHttps = false; before calling discoveryClient.GetAsync(); but no luck.

Thanks.

**Comment by leastprivilege** [comment]
I rather mean HTTPS problem at the transport layer.

**Comment by TarunVarian** [comment]
What would you suggest then?

**Comment by TarunVarian** [comment]
We are implementing a scenario where we would be consuming token generated from one server which will do authentication based on the certificate key which is used to create this token. This works fine when we do for same machine (delegation custom grant for same STS) but for token from another STS (custom delegation grant from another STS) is not working. This seemed to be blockers for us

**Comment by leastprivilege** [comment]
Sorry - I don't know what your problem is.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
