### ISSUE TITLE
Logout failed from MVC4 Client + IdSrv4 Core App

### ISSUE THREAD

**Issue by pc2910** [IdentityServer/IdentityServer4#977]
Hi, I'm trying to build IdSrv4 Core app with ASP.NET MVC 4.5.2 CLient. I have successfully authenticated application but when i'm trying to Logout, it just showing logout uri in browser like- http://localhost:5000/account/logout?logoutId=8cf84cf3a3e34bbda15d4613ae5b48ea
In MVC Clients controller's logout action, added "Request.GetOwinContext().Authentication.SignOut();", in startup 
 if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
                            n.ProtocolMessage.IdTokenHint = idTokenHint;
                        }
 i got the idTokenHint but I'm not able to Logout from application . 
Thanks..

**Comment by leastprivilege** [comment]
check the logs

**Comment by pc2910** [comment]
I have checked the log it is showing "No endpoint entry found for request path: /account/logout"

**Comment by pc2910** [comment]
Please check below Logs, It is giving error "Antiforgery token validation failed. The required antiforgery header value "RequestVerificationToken" is not present." is this the reason for not getting logout from application. 
![identityserverlogouterror](https://cloud.githubusercontent.com/assets/20540764/24451035/d607db36-149a-11e7-9d20-e2e3bb69f19a.PNG)

**Comment by brockallen** [comment]
This sounds like UI issues from custom code. Do our out of the box UI samples work?

**Comment by pc2910** [comment]
Thanks :)

**Comment by pc2910** [comment]
If application on standby for 5 mins then i try to logout i got idtokenhint null and because of I'm not able to logout. I have added id_token in claims from SecurityTokenValidated. also tried using `Request.GetOwinContext().Authentication.SignOut(new AuthenticationProperties { RedirectUri = ConfigHelper.GetConfigValue("MVCRedirectUrl") });`

Please check logs-

```
2017-06-21 14:56:58.531 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:5000/connect/endsession?post_logout_redirect_uri=https%3a%2f%2flocalhost%3a44338%2fsignin-oidc  
2017-06-21 14:56:58.570 +05:30 [Information] HttpContext.User merged via AutomaticAuthentication from authenticationScheme: "Identity.Application".
2017-06-21 14:56:58.573 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:56:58.576 +05:30 [Debug] Request path "/connect/endsession" matched to endpoint type EndSession
2017-06-21 14:56:58.577 +05:30 [Debug] Mapping found for endpoint: EndSession, creating handler: "IdentityServer4.Endpoints.EndSessionEndpoint"
2017-06-21 14:56:58.608 +05:30 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.EndSessionEndpoint" for "/connect/endsession"
2017-06-21 14:56:58.620 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:56:58.622 +05:30 [Debug] Processing signout request for "1638B9A0-6412-4862-B540-3770B91587B6"
2017-06-21 14:56:58.645 +05:30 [Debug] Start end session request validation
2017-06-21 14:56:58.690 +05:30 [Information] End session request validation success
"{
  \"SubjectId\": \"unknown\",
  \"Raw\": {
    \"post_logout_redirect_uri\": \"https://localhost:44338/signin-oidc\"
  }
}"
2017-06-21 14:56:58.692 +05:30 [Debug] Success validating end session request from null
2017-06-21 14:56:58.692 +05:30 [Verbose] Invoking result: "IdentityServer4.Endpoints.Results.EndSessionResult"
2017-06-21 14:56:58.722 +05:30 [Verbose] Purging stale cookie: "LogoutMessage.8b2d827386456146648f390d0d19d0f1"
2017-06-21 14:56:58.728 +05:30 [Verbose] Protecting message: "{\"Id\":\"aa398f779db35d033235a226d1505b22\",\"Created\":636336340186951786,\"Data\":{\"Parameters\":[{\"Key\":\"post_logout_redirect_uri\",\"Values\":[\"https://localhost:44338/signin-oidc\"]}],\"ShowSignoutPrompt\":true}}"
2017-06-21 14:56:58.732 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:56:58.736 +05:30 [Information] Request finished in 204.6141ms 302 
2017-06-21 14:56:58.738 +05:30 [Information] Request starting HTTP/1.1 GET http://localhost:5000/account/logout?logoutId=aa398f779db35d033235a226d1505b22  
2017-06-21 14:56:58.739 +05:30 [Information] HttpContext.User merged via AutomaticAuthentication from authenticationScheme: "Identity.Application".
2017-06-21 14:56:58.741 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:56:58.742 +05:30 [Verbose] No endpoint entry found for request path: "/account/logout"
2017-06-21 14:56:58.757 +05:30 [Information] Authorization was successful for user: "xxxxxxxxxxxx@gmail.com".
2017-06-21 14:56:58.851 +05:30 [Information] Executing action method "IdentityServer.Controllers.AccountController.LogOut (IdentityServer)" with arguments (["aa398f779db35d033235a226d1505b22"]) - ModelState is Valid
2017-06-21 14:57:00.024 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:57:00.035 +05:30 [Information] AuthenticationScheme: "Identity.Application" signed out.
2017-06-21 14:57:00.037 +05:30 [Information] AuthenticationScheme: "Identity.External" signed out.
2017-06-21 14:57:00.039 +05:30 [Information] AuthenticationScheme: "Identity.TwoFactorUserId" signed out.
2017-06-21 14:57:00.041 +05:30 [Information] User logged out.
2017-06-21 14:57:00.048 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:57:00.050 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:57:00.051 +05:30 [Information] AuthenticationScheme: "Identity.Application" was successfully authenticated.
2017-06-21 14:57:00.169 +05:30 [Information] Executed action "IdentityServer.Controllers.AccountController.LogOut (IdentityServer)" in 1424.6126ms
2017-06-21 14:57:00.510 +05:30 [Error] An unhandled exception has occurred while executing the request
System.ArgumentException: Value cannot be null or empty.
Parameter name: url
   at Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(String url)
   at IdentityServer.Controllers.AccountController.<LogOut>d__11.MoveNext() in E:\Source\GP.RentalManager\Development\Sprint 0\Security\IdentityServer\src\IdentityServer\Controllers\AccountController.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
